/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7db0ef85-bb14-4653-9002-2da58ff3f879

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This file defines the step function, test value, and autoconvolution ratio, and proves that the maximum test value is a lower bound on the L^infty norm of the autoconvolution of the step function (Claim 1.1).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  let norm_inf := (MeasureTheory.eLpNorm conv ⊤ MeasureTheory.volume).toReal
  let integral := MeasureTheory.integral MeasureTheory.volume f
  norm_inf / (integral ^ 2)

def discrete_autoconvolution {d : ℕ} (a : Fin d → ℝ) (k : ℕ) : ℝ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then a i * a j else 0

noncomputable def test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let a : Fin d → ℝ := fun i => (4 * n : ℝ) / m * (c i : ℝ)
  let conv := discrete_autoconvolution a
  let sum_conv := ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), conv k
  (1 / (4 * n * ℓ : ℝ)) * sum_conv

noncomputable def max_test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) : ℝ :=
  let d := 2 * n
  let range_ell := Finset.Icc 2 (2 * d)
  let range_s_lo := Finset.range (2 * d)
  let values := range_ell.biUnion (fun ℓ => range_s_lo.image (fun s_lo => test_value n m c ℓ s_lo))
  if h : values.Nonempty then values.max' h else 0

noncomputable def step_function (n m : ℕ) (c : Fin (2 * n) → ℕ) : ℝ → ℝ :=
  fun x =>
    let d := 2 * n
    let δ := 1 / (4 * n : ℝ)
    if x < -1/4 ∨ x ≥ 1/4 then 0
    else
      let i := ⌊(x + 1/4) / δ⌋.toNat
      if h : i < d then (c ⟨i, h⟩ : ℝ) / m
      else 0

lemma step_function_nonneg (n m : ℕ) (c : Fin (2 * n) → ℕ) :
  0 ≤ step_function n m c := by
    -- The step function is non-negative because it is a sum of non-negative terms.
    intros x
    simp [step_function];
    -- The step function is non-negative because it is either 0 or a positive fraction.
    split_ifs <;> norm_num;
    -- Since the numerator and denominator are both non-negative, their division is non-negative.
    apply div_nonneg; exact Nat.cast_nonneg _; exact Nat.cast_nonneg _

lemma step_function_integral (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m) :
    MeasureTheory.integral MeasureTheory.volume (step_function n m c) = 1 / (4 * n) := by
  -- We'll use the fact that the integral of the step function over $[-1/4, 1/4)$ is equal to the sum of the areas of the rectangles.
  have h_integral : ∫ x in Set.Ico (-1 / 4 : ℝ) (1 / 4), (step_function n m c) x = ∑ i : Fin (2 * n), (c i : ℝ) / m * (1 / (4 * n : ℝ)) := by
    -- We can split the integral into a sum of integrals over each subinterval where the step function is constant.
    have h_split_integral : ∫ x in Set.Ico (-1 / 4 : ℝ) (1 / 4), step_function n m c x = ∑ i : Fin (2 * n), ∫ x in Set.Ico (-1 / 4 + i.val * (1 / (4 * n : ℝ))) (-1 / 4 + (i.val + 1) * (1 / (4 * n : ℝ))), step_function n m c x := by
      rw [ ← MeasureTheory.integral_biUnion_finset ];
      · congr with x;
        -- To prove the equality of sets, we show each set is a subset of the other.
        apply Iff.intro;
        · intro hx
          obtain ⟨i, hi⟩ : ∃ i : Fin (2 * n), -1 / 4 + i.val * (1 / (4 * n : ℝ)) ≤ x ∧ x < -1 / 4 + (i.val + 1) * (1 / (4 * n : ℝ)) := by
            use ⟨ ⌊ ( x + 1 / 4 ) * ( 4 * n ) ⌋₊, by
              rw [ Nat.floor_lt ] <;> norm_num <;> nlinarith [ hx.1, hx.2, show ( n : ℝ ) ≥ 1 by norm_cast ] ⟩
            generalize_proofs at *;
            field_simp;
            constructor <;> linarith [ Nat.floor_le ( show 0 ≤ ( 4 * x + 1 ) * n by nlinarith [ hx.1, hx.2 ] ), Nat.lt_floor_add_one ( ( 4 * x + 1 ) * n ) ];
          aesop;
        · -- If $x$ is in the union of the intervals, then there exists some $i$ such that $x$ is in the interval $[-1/4 + i*(1/(4n)), -1/4 + (i+1)*(1/(4n)))$.
          intro hx
          obtain ⟨i, hi⟩ : ∃ i : Fin (2 * n), x ∈ Set.Ico (-1 / 4 + (i : ℝ) * (1 / (4 * n))) (-1 / 4 + ((i : ℝ) + 1) * (1 / (4 * n))) := by
            aesop;
          constructor <;> nlinarith [ hi.1, hi.2, show ( i : ℝ ) + 1 ≤ 2 * n by norm_cast; linarith [ Fin.is_lt i ], one_div_mul_cancel ( by positivity : ( 4 * n : ℝ ) ≠ 0 ) ];
      · exact fun _ _ => measurableSet_Ico;
      · intro i _ j _ hij; exact Set.disjoint_left.mpr fun x hx₁ hx₂ => hij <| Fin.ext <| Nat.le_antisymm ( Nat.le_of_lt_succ <| by { rw [ ← @Nat.cast_lt ℝ ] ; push_cast; nlinarith [ hx₁.1, hx₁.2, hx₂.1, hx₂.2, show ( n : ℝ ) > 0 by positivity, mul_div_cancel₀ ( 1 : ℝ ) ( by positivity : ( 4 * n : ℝ ) ≠ 0 ) ] } ) ( Nat.le_of_lt_succ <| by { rw [ ← @Nat.cast_lt ℝ ] ; push_cast; nlinarith [ hx₁.1, hx₁.2, hx₂.1, hx₂.2, show ( n : ℝ ) > 0 by positivity, mul_div_cancel₀ ( 1 : ℝ ) ( by positivity : ( 4 * n : ℝ ) ≠ 0 ) ] } ) ;
      · intro i hi
        have h_integrable : MeasureTheory.IntegrableOn (fun x => (c i : ℝ) / m) (Set.Ico (-1 / 4 + i.val * (1 / (4 * n : ℝ))) (-1 / 4 + (i.val + 1) * (1 / (4 * n : ℝ)))) MeasureTheory.MeasureSpace.volume := by
          norm_num +zetaDelta at *
        exact h_integrable.congr_fun (fun x hx => by
          -- Since $x$ is in the interval $[-1/4 + i * (1/(4n)), -1/4 + (i+1) * (1/(4n)))$, we have $\lfloor (x + 1/4) / \delta \rfloor = i$.
          have h_floor : ⌊(x + 1 / 4) / (1 / (4 * n : ℝ))⌋.toNat = i.val := by
            have h_floor : ⌊(x + 1 / 4) / (1 / (4 * n : ℝ))⌋ = i.val := by
              exact Int.floor_eq_iff.mpr ⟨ by rw [ le_div_iff₀ ( by positivity ) ] ; norm_num at *; nlinarith [ mul_inv_cancel₀ ( by positivity : ( n : ℝ ) ≠ 0 ) ], by rw [ div_lt_iff₀ ( by positivity ) ] ; norm_num at *; nlinarith [ mul_inv_cancel₀ ( by positivity : ( n : ℝ ) ≠ 0 ) ] ⟩;
            aesop;
          -- By definition of step_function, we have step_function n m c x = (c i : ℝ) / m since ⌊(x + 1/4) / (1/(4n))⌋.toNat = i.val.
          simp [step_function, h_floor];
          split_ifs <;> norm_num at *;
          · cases ‹_› <;> nlinarith [ show ( i : ℝ ) + 1 ≤ 2 * n by norm_cast; linarith [ Fin.is_lt i ], inv_mul_cancel₀ ( by positivity : ( n : ℝ ) ≠ 0 ) ];
          · aesop;
          · grind) measurableSet_Ico;
    -- On each subinterval, the step function is constant, so we can pull it out of the integral.
    have h_const_integral : ∀ i : Fin (2 * n), ∫ x in Set.Ico (-1 / 4 + i.val * (1 / (4 * n : ℝ))) (-1 / 4 + (i.val + 1) * (1 / (4 * n : ℝ))), step_function n m c x = (c i : ℝ) / m * (1 / (4 * n : ℝ)) := by
      intro i
      have h_const : ∀ x ∈ Set.Ico (-1 / 4 + i.val * (1 / (4 * n : ℝ))) (-1 / 4 + (i.val + 1) * (1 / (4 * n : ℝ))), step_function n m c x = (c i : ℝ) / m := by
        unfold step_function;
        -- By definition of $step_function$, we know that for $x$ in the interval $[-1/4 + i.val * (1/(4n)), -1/4 + (i.val + 1) * (1/(4n)))$, the value of $step_function n m c x$ is $(c i : ℝ) / m$.
        intros x hx
        have h_floor : ⌊(x + 1 / 4) / (1 / (4 * n : ℝ))⌋ = i.val := by
          norm_num [ Int.floor_eq_iff ] at *;
          exact ⟨ by rw [ le_div_iff₀ ( by positivity ) ] ; linarith, by rw [ div_lt_iff₀ ( by positivity ) ] ; linarith ⟩;
        simp_all +decide [ Fin.ext_iff ];
        rintro ( h | h ) <;> nlinarith [ show ( i : ℝ ) + 1 ≤ 2 * n by norm_cast; linarith [ Fin.is_lt i ], inv_mul_cancel₀ ( by positivity : ( n : ℝ ) ≠ 0 ) ];
      rw [ MeasureTheory.setIntegral_congr_fun measurableSet_Ico h_const, ← MeasureTheory.integral_Icc_eq_integral_Ico, MeasureTheory.integral_Icc_eq_integral_Ioc, ← intervalIntegral.integral_of_le ] <;> norm_num ; ring ; norm_num [ hn, hm ];
    grind;
  -- Since the step function is zero outside the interval $[-1/4, 1/4)$, the integral over the entire real line is equal to the integral over this interval.
  have h_integral_eq : ∫ x, (step_function n m c) x = ∫ x in Set.Ico (-1 / 4 : ℝ) (1 / 4), (step_function n m c) x := by
    rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero ] ; unfold step_function ; aesop;
  convert h_integral_eq.trans h_integral using 1 ; norm_num [ ← Finset.sum_mul _ _ _, hc ];
  rw [ ← Finset.sum_div _ _ _, ← Nat.cast_sum, hc ] ; norm_num [ hm.ne' ]

noncomputable def triangle (c h : ℝ) (x : ℝ) : ℝ :=
  max 0 (h - |x - c|)

lemma convolution_indicator_indicator (a b δ : ℝ) (hδ : 0 < δ) :
    let f := Set.indicator (Set.Ico a (a + δ)) (1 : ℝ → ℝ)
    let g := Set.indicator (Set.Ico b (b + δ)) (1 : ℝ → ℝ)
    MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume =
    fun x => triangle (a + b + δ) δ x := by
  -- By definition of convolution, we have:
  have h_conv_def : ∀ x, MeasureTheory.convolution (Set.indicator (Set.Ico a (a + δ)) 1) (Set.indicator (Set.Ico b (b + δ)) 1) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x = ∫ t in Set.Ico (max a (x - b - δ)) (min (a + δ) (x - b)), 1 := by
    intro x;
    rw [ MeasureTheory.convolution, ← MeasureTheory.integral_indicator ] <;> norm_num [ Set.indicator ];
    rw [ ← MeasureTheory.integral_congr_ae ];
    refine' MeasureTheory.measure_mono_null _ _;
    exact { x_1 : ℝ | x_1 = x - b - δ ∨ x_1 = x - b };
    · -- If the functions are not equal, then either the first function is 1 and the second is 0, or vice versa.
      intro x_1 hx_1
      simp [Set.mem_setOf_eq] at hx_1;
      grind;
    · rw [ show { x_1 : ℝ | x_1 = x - b - δ ∨ x_1 = x - b } = { x - b - δ, x - b } by rfl, Set.insert_eq, MeasureTheory.measure_union ] <;> norm_num;
      linarith;
  -- By simplifying the integral, we can see that it matches the definition of the triangle function.
  funext x
  simp [h_conv_def];
  unfold triangle;
  cases max_cases a ( x - b - δ ) <;> cases min_cases ( a + δ ) ( x - b ) <;> cases abs_cases ( x - ( a + b + δ ) ) <;> cases max_cases ( Min.min ( a + δ ) ( x - b ) - Max.max a ( x - b - δ ) ) 0 <;> cases max_cases 0 ( δ - |x - ( a + b + δ )| ) <;> linarith

noncomputable def step_convolution_sum (n m : ℕ) (c : Fin (2 * n) → ℕ) (x : ℝ) : ℝ :=
  let δ := 1 / (4 * n : ℝ)
  ∑ k : Fin (4 * n - 1),
    let val := ∑ i : Fin (2 * n), ∑ j : Fin (2 * n),
      if i.1 + j.1 = k then (c i : ℝ) * (c j : ℝ) else 0
    (val / m ^ 2) * triangle ((k + 1) * δ - 1 / 2) δ x

lemma step_function_convolution_eq_sum (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) :
    MeasureTheory.convolution (step_function n m c) (step_function n m c) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume =
    step_convolution_sum n m c := by
  have h_conv_triangle : ∀ i j : Fin (2 * n), MeasureTheory.convolution (Set.indicator (Set.Ico (-1/4 + (i.val : ℝ) / (4 * n)) (-1/4 + (i.val + 1) / (4 * n))) (fun _ => (c i : ℝ) / m)) (Set.indicator (Set.Ico (-1/4 + (j.val : ℝ) / (4 * n)) (-1/4 + (j.val + 1) / (4 * n))) (fun _ => (c j : ℝ) / m)) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume = fun x => (c i * c j : ℝ) / m^2 * triangle (-1/2 + (i.val + j.val + 1) / (4 * n)) (1 / (4 * n)) x := by
    intro i j
    have h_conv_triangle : MeasureTheory.convolution (Set.indicator (Set.Ico (-1/4 + (i.val : ℝ) / (4 * n)) (-1/4 + (i.val + 1) / (4 * n))) (1 : ℝ → ℝ)) (Set.indicator (Set.Ico (-1/4 + (j.val : ℝ) / (4 * n)) (-1/4 + (j.val + 1) / (4 * n))) (1 : ℝ → ℝ)) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume = fun x => triangle (-1/2 + (i.val + j.val + 1) / (4 * n)) (1 / (4 * n)) x := by
      convert convolution_indicator_indicator ( -1 / 4 + ( i : ℝ ) / ( 4 * n ) ) ( -1 / 4 + ( j : ℝ ) / ( 4 * n ) ) ( 1 / ( 4 * n ) ) ( by positivity ) using 1 ; ring;
      exact funext fun x => by ring;
    convert congr_arg ( fun f => fun x => ( c i * c j : ℝ ) / m ^ 2 * f x ) h_conv_triangle using 1;
    ext x; simp +decide [ MeasureTheory.convolution, MeasureTheory.integral_const_mul, MeasureTheory.integral_mul_const ] ; ring;
    rw [ ← MeasureTheory.integral_const_mul ] ; congr ; ext ; norm_num [ Set.indicator ] ; ring;
  convert Finset.sum_congr rfl fun i hi => Finset.sum_congr rfl fun j hj => h_conv_triangle i j using 1;
  any_goals exact Finset.univ;
  any_goals exact fun i => Finset.univ;
  · have h_conv_triangle : step_function n m c = ∑ i : Fin (2 * n), Set.indicator (Set.Ico (-1/4 + (i.val : ℝ) / (4 * n)) (-1/4 + (i.val + 1) / (4 * n))) (fun _ => (c i : ℝ) / m) := by
      ext x; simp [step_function];
      split_ifs <;> simp_all +decide [ Set.indicator ];
      · -- Since $x$ is either less than $-1/4$ or greater than or equal to $1/4$, none of the intervals $[-1/4 + i/(4n), -1/4 + (i+1)/(4n))$ contain $x$.
        have h_no_interval : ∀ i : Fin (2 * n), ¬(-1 / 4 + (i.val : ℝ) / (4 * n) ≤ x ∧ x < -1 / 4 + ((i.val + 1) : ℝ) / (4 * n)) := by
          intro i hi; cases ‹x < -1 / 4 ∨ 4⁻¹ ≤ x› <;> nlinarith [ show ( i : ℝ ) + 1 ≤ 2 * n by norm_cast; linarith [ Fin.is_lt i ], div_mul_cancel₀ ( ( i : ℝ ) : ℝ ) ( by positivity : ( 4 * n : ℝ ) ≠ 0 ), div_mul_cancel₀ ( ( i + 1 : ℝ ) : ℝ ) ( by positivity : ( 4 * n : ℝ ) ≠ 0 ) ] ;
        exact Eq.symm ( Finset.sum_eq_zero fun i hi => if_neg ( h_no_interval i ) );
      · -- Since $x$ is in the interval $[-1/4, 1/4)$, there exists a unique $i$ such that $-1/4 + i/(4n) \leq x < -1/4 + (i+1)/(4n)$.
        obtain ⟨i, hi⟩ : ∃ i : Fin (2 * n), -1 / 4 + (i.val : ℝ) / (4 * n) ≤ x ∧ x < -1 / 4 + ((i.val + 1) : ℝ) / (4 * n) := by
          refine' ⟨ ⟨ ⌊ ( x + 1 / 4 ) * ( 4 * n ) ⌋₊, _ ⟩, _, _ ⟩ <;> norm_num at *;
          · rw [ Nat.floor_lt ] <;> norm_num <;> nlinarith [ ( by norm_cast : ( 1 : ℝ ) ≤ n ) ];
          · rw [ div_le_iff₀ ] <;> nlinarith [ Nat.floor_le ( show 0 ≤ ( x + 1 / 4 ) * ( 4 * n ) by nlinarith [ show ( n : ℝ ) ≥ 1 by norm_cast ] ), show ( n : ℝ ) ≥ 1 by norm_cast ];
          · rw [ lt_div_iff₀ ] <;> norm_num <;> linarith [ Nat.lt_floor_add_one ( ( x + 1 / 4 ) * ( 4 * n ) ) ];
        rw [ Finset.sum_eq_single i ] <;> simp_all +decide [ Fin.val_inj ];
        · -- Since $i$ is in the interval $[-1/4 + i/(4n), -1/4 + (i+1)/(4n))$, we have $i \leq (x + 1/4) / (1/(4n)) < i+1$.
          have h_floor : (i.val : ℝ) ≤ (x + 1 / 4) / (1 / (4 * n)) ∧ (x + 1 / 4) / (1 / (4 * n)) < (i.val + 1 : ℝ) := by
            field_simp at *; constructor <;> linarith;
          norm_num [ show ⌊ ( x + 1 / 4 ) / ( ( n : ℝ ) ⁻¹ * ( 1 / 4 ) ) ⌋ = i from Int.floor_eq_iff.mpr ⟨ by norm_num at *; linarith, by norm_num at *; linarith ⟩ ];
        · intro j hj₁ hj₂ hj₃; contrapose! hj₁; simp_all +decide [ Fin.ext_iff ] ;
          exact Nat.le_antisymm ( Nat.le_of_lt_succ <| by rw [ ← @Nat.cast_lt ℝ ] ; push_cast; ring_nf at *; nlinarith [ inv_mul_cancel₀ ( by positivity : ( n : ℝ ) ≠ 0 ) ] ) ( Nat.le_of_lt_succ <| by rw [ ← @Nat.cast_lt ℝ ] ; push_cast; ring_nf at *; nlinarith [ inv_mul_cancel₀ ( by positivity : ( n : ℝ ) ≠ 0 ) ] );
      · rename_i h₁ h₂;
        exact absurd h₂ ( not_le_of_gt <| Int.floor_lt.mpr <| by rw [ div_lt_iff₀ ] <;> norm_num <;> nlinarith [ show ( n : ℝ ) ≥ 1 by norm_cast, mul_inv_cancel₀ ( by positivity : ( n : ℝ ) ≠ 0 ) ] );
    rw [ h_conv_triangle ];
    ext x;
    simp +decide [ MeasureTheory.convolution, Finset.sum_apply ];
    rw [ MeasureTheory.integral_finset_sum ];
    · rw [ Finset.sum_comm ];
      refine' Finset.sum_congr rfl fun i hi => _;
      rw [ MeasureTheory.integral_finset_sum ];
      intro j hj;
      refine' MeasureTheory.Integrable.mono' _ _ _;
      use fun a => ( c j : ℝ ) / m * ( c i : ℝ ) / m * ( Set.indicator ( Set.Ico ( -1 / 4 + ( j.val : ℝ ) / ( 4 * n ) ) ( -1 / 4 + ( j.val + 1 ) / ( 4 * n ) ) ) ( fun _ => 1 ) a ) * ( Set.indicator ( Set.Ico ( -1 / 4 + ( i.val : ℝ ) / ( 4 * n ) ) ( -1 / 4 + ( i.val + 1 ) / ( 4 * n ) ) ) ( fun _ => 1 ) ( x - a ) );
      · refine' MeasureTheory.Integrable.mono' _ _ _;
        use fun a => ( c j : ℝ ) / m * ( c i : ℝ ) / m * ( Set.indicator ( Set.Ico ( -1 / 4 + ( j.val : ℝ ) / ( 4 * n ) ) ( -1 / 4 + ( j.val + 1 ) / ( 4 * n ) ) ) ( fun _ => 1 ) a );
        · refine' MeasureTheory.Integrable.const_mul _ _;
          rw [ MeasureTheory.integrable_indicator_iff ] <;> norm_num;
        · exact Measurable.aestronglyMeasurable ( by exact Measurable.mul ( Measurable.mul ( measurable_const ) ( measurable_const.indicator ( measurableSet_Ico ) ) ) ( measurable_const.indicator ( measurableSet_Ico ) |> Measurable.comp <| measurable_const.sub measurable_id' ) );
        · filter_upwards [ ] with a ; by_cases ha : -1 / 4 + ( j : ℝ ) / ( 4 * n ) ≤ a ∧ a < -1 / 4 + ( j + 1 : ℝ ) / ( 4 * n ) <;> by_cases hb : -1 / 4 + ( i : ℝ ) / ( 4 * n ) ≤ x - a ∧ x - a < -1 / 4 + ( i + 1 : ℝ ) / ( 4 * n ) <;> simp +decide [ ha, hb ];
          positivity;
      · exact Measurable.aestronglyMeasurable ( by exact Measurable.mul ( Measurable.indicator ( measurable_const ) ( measurableSet_Ico ) ) ( Measurable.indicator ( measurable_const ) ( measurableSet_Ico ) |> Measurable.comp <| measurable_const.sub measurable_id' ) );
      · filter_upwards [ ] with a ; by_cases ha : -1 / 4 + ( j : ℝ ) / ( 4 * n ) ≤ a ∧ a < -1 / 4 + ( j + 1 : ℝ ) / ( 4 * n ) <;> by_cases hb : -1 / 4 + ( i : ℝ ) / ( 4 * n ) ≤ x - a ∧ x - a < -1 / 4 + ( i + 1 : ℝ ) / ( 4 * n ) <;> simp +decide [ ha, hb ] ; ring_nf ; norm_num;
    · intro i hi;
      refine' MeasureTheory.integrable_finset_sum _ _;
      intro j hj;
      refine' MeasureTheory.Integrable.mono' _ _ _;
      use fun t => ( c j : ℝ ) / m * ( c i : ℝ ) / m * ( Set.indicator ( Set.Ico ( -1 / 4 + ( j.val : ℝ ) / ( 4 * n ) ) ( -1 / 4 + ( j.val + 1 ) / ( 4 * n ) ) ) ( fun _ => 1 ) t ) * ( Set.indicator ( Set.Ico ( -1 / 4 + ( i.val : ℝ ) / ( 4 * n ) ) ( -1 / 4 + ( i.val + 1 ) / ( 4 * n ) ) ) ( fun _ => 1 ) ( x - t ) );
      · refine' MeasureTheory.Integrable.mono' _ _ _;
        use fun t => ( c j : ℝ ) / m * ( c i : ℝ ) / m * ( Set.indicator ( Set.Ico ( -1 / 4 + ( j.val : ℝ ) / ( 4 * n ) ) ( -1 / 4 + ( j.val + 1 ) / ( 4 * n ) ) ) ( fun _ => 1 ) t );
        · refine' MeasureTheory.Integrable.const_mul _ _;
          rw [ MeasureTheory.integrable_indicator_iff ] <;> norm_num;
        · exact Measurable.aestronglyMeasurable ( by exact Measurable.mul ( Measurable.mul ( measurable_const ) ( measurable_const.indicator ( measurableSet_Ico ) ) ) ( measurable_const.indicator ( measurableSet_Ico ) |> Measurable.comp <| measurable_const.sub measurable_id' ) );
        · filter_upwards [ ] with a ; by_cases ha : -1 / 4 + ( j : ℝ ) / ( 4 * n ) ≤ a ∧ a < -1 / 4 + ( j + 1 : ℝ ) / ( 4 * n ) <;> by_cases hb : -1 / 4 + ( i : ℝ ) / ( 4 * n ) ≤ x - a ∧ x - a < -1 / 4 + ( i + 1 : ℝ ) / ( 4 * n ) <;> simp +decide [ ha, hb ];
          positivity;
      · exact Measurable.aestronglyMeasurable ( by exact Measurable.mul ( Measurable.indicator ( measurable_const ) ( measurableSet_Ico ) ) ( Measurable.indicator ( measurable_const ) ( measurableSet_Ico ) |> Measurable.comp <| measurable_const.sub measurable_id' ) );
      · filter_upwards [ ] with a ; by_cases ha : -1 / 4 + ( j : ℝ ) / ( 4 * n ) ≤ a ∧ a < -1 / 4 + ( j + 1 : ℝ ) / ( 4 * n ) <;> by_cases hb : -1 / 4 + ( i : ℝ ) / ( 4 * n ) ≤ x - a ∧ x - a < -1 / 4 + ( i + 1 : ℝ ) / ( 4 * n ) <;> simp +decide [ ha, hb ] ; ring_nf ; norm_num;
  · unfold step_convolution_sum; ext; simp +decide [ Finset.sum_mul _ _ _ ] ;
    simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ];
    rw [ Finset.sum_comm ];
    refine' Finset.sum_congr rfl fun i hi => _;
    rw [ Finset.sum_comm ];
    refine' Finset.sum_congr rfl fun j hj => _;
    rw [ Finset.sum_eq_single ⟨ i + j, by linarith [ Fin.is_lt i, Fin.is_lt j, Nat.sub_add_cancel ( by linarith : 1 ≤ 4 * n ) ] ⟩ ] <;> norm_num ; ring;
    · norm_num;
    · exact fun k hk₁ hk₂ => False.elim <| hk₁ <| Fin.ext hk₂.symm

lemma autoconvolution_ratio_eq (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m) :
    autoconvolution_ratio (step_function n m c) =
    (4 * n : ℝ) ^ 2 * (MeasureTheory.eLpNorm (MeasureTheory.convolution (step_function n m c) (step_function n m c) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal := by
  -- By definition of $f$, we know that its integral is $1/(4n)$.
  have h_integral : ∫ x, step_function n m c x = 1 / (4 * n : ℝ) := by
    -- Apply the lemma that states the integral of the step function is 1/(4n).
    apply step_function_integral n m hn hm c hc;
  -- Substitute the integral of the step function into the autoconvolution ratio formula.
  have h_ratio : autoconvolution_ratio (step_function n m c) = (MeasureTheory.eLpNorm (MeasureTheory.convolution (step_function n m c) (step_function n m c) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal / (1 / (4 * n : ℝ)) ^ 2 := by
    exact h_integral ▸ rfl;
  -- Simplify the expression for the autoconvolution ratio.
  rw [h_ratio]
  field_simp

lemma integral_triangle (c h : ℝ) (hh : 0 < h) :
    MeasureTheory.integral MeasureTheory.volume (triangle c h) = h ^ 2 := by
  -- The integral of the triangle function can be computed by splitting it into two parts: the area of the triangle from $c$ to $c + h$ and the area of the triangle from $c - h$ to $c$.
  have h_integral_split : ∫ x in Set.Icc (c - h) (c + h), max 0 (h - |x - c|) = ∫ x in Set.Icc (c - h) (c + h), (h - |x - c|) := by
    exact MeasureTheory.setIntegral_congr_fun measurableSet_Icc fun x hx => max_eq_right ( by cases abs_cases ( x - c ) <;> linarith [ hx.1, hx.2 ] );
  convert h_integral_split using 1;
  · rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero ] ; aesop;
    exact fun x hx => max_eq_left <| by contrapose! hx; constructor <;> cases abs_cases ( x - c ) <;> linarith;
  · rw [ MeasureTheory.integral_Icc_eq_integral_Ioc, ← intervalIntegral.integral_of_le ( by linarith ), intervalIntegral.integral_sub ] <;> norm_num;
    · -- Evaluate the integral of $|x|$ over $[-h, h]$.
      have h_abs : ∫ x in (-h)..h, abs x = (∫ x in (-h)..0, abs x) + (∫ x in (0)..h, abs x) := by
        rw [ intervalIntegral.integral_add_adjacent_intervals ] <;> exact Continuous.intervalIntegrable ( by continuity ) _ _;
      rw [ h_abs, intervalIntegral.integral_congr fun x hx => abs_of_nonpos ( by linarith [ Set.mem_Icc.mp ( by simpa [ hh.le ] using hx ) ] ), intervalIntegral.integral_congr fun x hx => abs_of_nonneg ( by linarith [ Set.mem_Icc.mp ( by simpa [ hh.le ] using hx ) ] ) ] ; norm_num ; ring;
      rw [ intervalIntegral.integral_neg ] ; norm_num ; ring;
    · exact Continuous.intervalIntegrable ( by continuity ) _ _

lemma triangle_support_subset (n : ℕ) (hn : n > 0) (k s_lo ℓ : ℕ) (hℓ : 2 ≤ ℓ) (hk1 : s_lo ≤ k) (hk2 : k ≤ s_lo + ℓ - 2) :
    let δ := 1 / (4 * n : ℝ)
    let center := ((k + 1) * δ - 1 / 2)
    Set.Icc (center - δ) (center + δ) ⊆ Set.Icc (s_lo * δ - 1 / 2) ((s_lo + ℓ) * δ - 1 / 2) := by
  refine' Set.Icc_subset_Icc _ _ <;> norm_num;
  · nlinarith [ show ( s_lo : ℝ ) ≤ k by norm_cast, inv_pos.2 ( by positivity : 0 < ( n : ℝ ) ) ];
  · nlinarith [ show ( k : ℝ ) + 2 ≤ s_lo + ℓ by norm_cast; omega, inv_pos.2 ( by positivity : 0 < ( n : ℝ ) ) ]

lemma integral_convolution_subset (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (s_lo ℓ : ℕ) (hℓ : 2 ≤ ℓ)
    (hk_start : s_lo ≤ s_lo) (hk_end : s_lo + ℓ - 2 ≤ s_lo + ℓ - 2) :
    let δ := 1 / (4 * n : ℝ)
    let interval := Set.Icc (s_lo * δ - 1 / 2) ((s_lo + ℓ) * δ - 1 / 2)
    ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2),
      MeasureTheory.integral MeasureTheory.volume
        (fun x =>
          let val := ∑ i : Fin (2 * n), ∑ j : Fin (2 * n),
            if i.1 + j.1 = k then (c i : ℝ) * (c j : ℝ) else 0
          (val / m ^ 2) * triangle ((k + 1) * δ - 1 / 2) δ x)
    ≤ MeasureTheory.integral MeasureTheory.volume
        (Set.indicator interval (step_convolution_sum n m c)) := by
  -- By linearity of the integral, we can pull the summation inside.
  suffices h_sum : ∑ x_1 ∈ Finset.Icc s_lo (s_lo + ℓ - 2), (∫ x, (let val := ∑ i : Fin (2 * n), ∑ j : Fin (2 * n), if i.1 + j.1 = x_1 then (c i : ℝ) * (c j : ℝ) else 0;
    val / m ^ 2 * triangle ((x_1 + 1) * (1 / (4 * n : ℝ)) - 1 / 2) (1 / (4 * n : ℝ)) x)) ≤ ∫ x in (Set.Icc ((s_lo : ℝ) * (1 / (4 * n : ℝ)) - 1 / 2) ((s_lo + ℓ) * (1 / (4 * n : ℝ)) - 1 / 2)), ∑ k : Fin (4 * n - 1), (let val := ∑ i : Fin (2 * n), ∑ j : Fin (2 * n), if i.1 + j.1 = k then (c i : ℝ) * (c j : ℝ) else 0;
    val / m ^ 2 * triangle ((k + 1) * (1 / (4 * n : ℝ)) - 1 / 2) (1 / (4 * n : ℝ)) x) by
      convert h_sum using 1;
      rw [ MeasureTheory.integral_indicator ];
      · bound;
      · norm_num;
  rw [ MeasureTheory.integral_finset_sum ];
  · rw [ ← Finset.sum_subset ];
    any_goals exact Finset.filter ( fun x => x < 4 * n - 1 ) ( Finset.Icc s_lo ( s_lo + ℓ - 2 ) );
    · refine' le_trans _ ( Finset.sum_le_sum fun i hi => _ );
      rotate_left;
      use fun i => ∫ x, (let val := ∑ i_1 : Fin (2 * n), ∑ j : Fin (2 * n), if (↑i_1 : ℕ) + (↑j : ℕ) = (↑i : ℕ) then (↑(c i_1) : ℝ) * (↑(c j) : ℝ) else 0;
        val / (↑m : ℝ) ^ 2 * triangle (((↑(↑i : ℕ) : ℝ) + 1) * (1 / (4 * (↑n : ℝ))) - 1 / 2) (1 / (4 * (↑n : ℝ))) x) * (if (↑i : ℕ) ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then 1 else 0);
      · by_cases hi' : ( i : ℕ ) ∈ Finset.Icc s_lo ( s_lo + ℓ - 2 ) <;> simp +decide [ hi' ];
        · rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero ];
          intro x hx; contrapose! hx; simp_all +decide [ triangle ] ;
          constructor <;> norm_num at * <;> nlinarith [ abs_lt.mp hx.2, show ( i : ℝ ) ≥ s_lo by exact_mod_cast hi'.1, show ( i : ℝ ) ≤ s_lo + ℓ - 2 by exact le_tsub_of_add_le_right <| by norm_cast; omega, inv_mul_cancel₀ ( by positivity : ( n : ℝ ) ≠ 0 ) ];
        · refine' MeasureTheory.setIntegral_nonneg measurableSet_Icc fun x hx => mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => Finset.sum_nonneg fun _ _ => by positivity ) ( sq_nonneg _ ) ) ( le_max_left _ _ );
      · rw [ ← Finset.sum_subset ( Finset.subset_univ _ ) ];
        any_goals exact Finset.univ.filter fun x => x.val ∈ Finset.Icc s_lo ( s_lo + ℓ - 2 ) ∧ x.val < 4 * n - 1;
        · refine' le_of_eq _;
          refine' Finset.sum_bij ( fun x hx => ⟨ x, by linarith [ Finset.mem_Icc.mp ( Finset.mem_filter.mp hx |>.1 ), Finset.mem_filter.mp hx |>.2 ] ⟩ ) _ _ _ _ <;> simp +decide;
          · tauto;
          · exact fun b hb₁ hb₂ => ⟨ b, ⟨ ⟨ hb₁, hb₂ ⟩, b.2 ⟩, rfl ⟩;
          · aesop;
        · intro x hx hx'; rw [ MeasureTheory.integral_eq_zero_of_ae ] ; filter_upwards [ ] with y ; aesop;
    · exact Finset.filter_subset _ _;
    · simp +zetaDelta at *;
      intro x hx₁ hx₂ hx₃; rw [ MeasureTheory.integral_const_mul ] ; rw [ integral_triangle ] ; norm_num;
      · exact Or.inl <| Or.inl <| Finset.sum_eq_zero fun i hi => Finset.sum_eq_zero fun j hj => if_neg <| by linarith [ Fin.is_lt i, Fin.is_lt j, hx₃ hx₁ hx₂ ] ;
      · positivity;
  · intro i hi; apply_rules [ Continuous.integrableOn_Icc ] ; unfold triangle; apply_rules [ Continuous.max, Continuous.sub, Continuous.max, Continuous.mul, continuous_const, continuous_id' ] ; norm_num;
    continuity

noncomputable def sum_val (n : ℕ) (c : Fin (2 * n) → ℕ) (s_lo ℓ : ℕ) : ℝ :=
  ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2),
    ∑ i : Fin (2 * n), ∑ j : Fin (2 * n),
      if i.1 + j.1 = k then (c i : ℝ) * (c j : ℝ) else 0

lemma test_value_eq_sum_val (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (s_lo ℓ : ℕ) :
    test_value n m c ℓ s_lo = (4 * n / (ℓ * m ^ 2)) * sum_val n c s_lo ℓ := by
  -- By definition of test_value, we can rewrite the left-hand side as (1 / (4 * n * ℓ)) * sum_val n c s_lo ℓ.
  simp [test_value, sum_val];
  -- By definition of discrete autoconvolution, we can rewrite the left-hand side as the sum of the products of the coefficients.
  have h_discrete_conv : ∀ k : ℕ, discrete_autoconvolution (fun i : Fin (2 * n) => (4 * n / m : ℝ) * (c i : ℝ)) k = (4 * n / m : ℝ) ^ 2 * ∑ i : Fin (2 * n), ∑ j : Fin (2 * n), if i.1 + j.1 = k then (c i : ℝ) * (c j : ℝ) else 0 := by
    unfold discrete_autoconvolution; norm_num [ Finset.mul_sum _ _ _, mul_assoc, mul_comm, mul_left_comm, sq ] ;
  -- Apply the hypothesis `h_discrete_conv` to each term in the sum.
  simp [h_discrete_conv];
  norm_num [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ] ; ring;
  simp +decide [ sq, mul_assoc, mul_comm, mul_left_comm, hn.ne' ]

lemma sum_integral_eq_sum_val_mul_sq_delta (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (s_lo ℓ : ℕ) :
    let δ := 1 / (4 * n : ℝ)
    ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2),
      MeasureTheory.integral MeasureTheory.volume
        (fun x =>
          let val := ∑ i : Fin (2 * n), ∑ j : Fin (2 * n),
            if i.1 + j.1 = k then (c i : ℝ) * (c j : ℝ) else 0
          (val / m ^ 2) * triangle ((k + 1) * δ - 1 / 2) δ x)
    = (sum_val n c s_lo ℓ / m ^ 2) * δ ^ 2 := by
  simp +zetaDelta at *;
  unfold sum_val;
  rw [ Finset.sum_div, Finset.sum_mul ];
  refine' Finset.sum_congr rfl fun x hx => _ ; erw [ MeasureTheory.integral_const_mul ] ; erw [ integral_triangle ] ; ring ; norm_num [ hn.ne', hm.ne' ] ; ring;
  positivity

lemma volume_test_interval (n s_lo ℓ : ℕ) (hn : n > 0) :
    let δ := 1 / (4 * n : ℝ)
    let interval := Set.Icc (s_lo * δ - 1 / 2) ((s_lo + ℓ) * δ - 1 / 2)
    MeasureTheory.volume interval = ENNReal.ofReal (ℓ * δ) := by
  -- The length of the interval is $(s_lo + ℓ) * δ - 1/2 - (s_lo * δ - 1/2) = ℓ * δ$.
  simp [ENNReal.ofReal];
  -- The length of the interval is $(s_lo + ℓ) * δ - 1/2 - (s_lo * δ - 1/2) = ℓ * δ$ by simplifying the expression.
  ring_nf at *

lemma integral_le_volume_mul_Linfty (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (s_lo ℓ : ℕ) :
    let δ := 1 / (4 * n : ℝ)
    let interval := Set.Icc (s_lo * δ - 1 / 2) ((s_lo + ℓ) * δ - 1 / 2)
    MeasureTheory.integral MeasureTheory.volume
        (Set.indicator interval (step_convolution_sum n m c))
    ≤ (MeasureTheory.volume interval).toReal * (MeasureTheory.eLpNorm (MeasureTheory.convolution (step_function n m c) (step_function n m c) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal := by
  -- Let $f$ be the convolution.
  set f := MeasureTheory.convolution (step_function n m c) (step_function n m c) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.MeasureSpace.volume;
  -- Since `step_convolution_sum` is equal to the convolution (proved in `step_function_convolution_eq_sum`), we have `f = step_convolution_sum`.
  have hf : f = step_convolution_sum n m c := by
    exact?;
  -- By definition of $f$, we know that $|f(x)| \leq \ess sup |f|$ almost everywhere.
  have h_abs : ∀ᵐ x ∂MeasureTheory.volume, |f x| ≤ (MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume).toReal := by
    have h_abs : ∀ᵐ x ∂MeasureTheory.volume, ‖f x‖ₑ ≤ essSup (fun x => ‖f x‖ₑ) MeasureTheory.volume := by
      exact?;
    filter_upwards [ h_abs ] with x hx;
    convert ENNReal.toReal_mono _ hx using 1;
    -- Since `step_convolution_sum` is a finite sum of bounded functions, it is bounded.
    have h_bounded : ∃ C, ∀ x, |step_convolution_sum n m c x| ≤ C := by
      use ∑ k : Fin (4 * n - 1), ( ∑ i : Fin (2 * n), ∑ j : Fin (2 * n), if i.1 + j.1 = k then (c i : ℝ) * (c j : ℝ) else 0 ) / m ^ 2 * (1 / (4 * n : ℝ));
      intro x
      simp [step_convolution_sum];
      refine' le_trans ( Finset.abs_sum_le_sum_abs _ _ ) ( Finset.sum_le_sum fun i _ => _ );
      rw [ abs_of_nonneg ( mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => Finset.sum_nonneg fun _ _ => by positivity ) ( sq_nonneg _ ) ) ( by unfold triangle; positivity ) ) ];
      exact mul_le_mul_of_nonneg_left ( by unfold triangle; exact max_le_iff.mpr ⟨ by norm_num, by cases abs_cases ( x - ( ( i + 1 ) * ( ( n : ℝ ) ⁻¹ * 4⁻¹ ) - 2⁻¹ ) ) <;> linarith ⟩ ) ( div_nonneg ( Finset.sum_nonneg fun _ _ => Finset.sum_nonneg fun _ _ => by positivity ) ( sq_nonneg _ ) );
    obtain ⟨ C, hC ⟩ := h_bounded; refine' ne_of_lt ( lt_of_le_of_lt ( csInf_le _ _ ) _ ) <;> norm_num [ hf ];
    exact ENNReal.ofReal C
    all_goals generalize_proofs at *;
    · filter_upwards [ ] with x using by simpa only [ Real.enorm_eq_ofReal_abs ] using ENNReal.ofReal_le_ofReal ( hC x ) ;
    · exact ENNReal.ofReal_lt_top;
  -- Applying the inequality $|f(x)| \leq \ess sup |f|$ almost everywhere to the integral, we get:
  have h_integral : ∫ x in Set.Icc (s_lo * (1 / (4 * n : ℝ)) - 1 / 2) ((s_lo + ℓ) * (1 / (4 * n : ℝ)) - 1 / 2), |f x| ≤ (MeasureTheory.volume (Set.Icc (s_lo * (1 / (4 * n : ℝ)) - 1 / 2) ((s_lo + ℓ) * (1 / (4 * n : ℝ)) - 1 / 2))).toReal * (MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume).toReal := by
    refine' le_trans ( MeasureTheory.integral_mono_of_nonneg _ _ _ ) _;
    refine' fun x => ( MeasureTheory.eLpNorm f ⊤ MeasureTheory.MeasureSpace.volume ).toReal;
    · exact Filter.Eventually.of_forall fun x => abs_nonneg _;
    · norm_num;
    · exact MeasureTheory.ae_restrict_of_ae h_abs;
    · norm_num [ mul_comm ];
      rw [ max_eq_left ( by nlinarith [ show ( 0 : ℝ ) ≤ ( n : ℝ ) ⁻¹ * ( 1 / 4 ) by positivity ] ), ENNReal.toReal_ofReal ( by nlinarith [ show ( 0 : ℝ ) ≤ ( n : ℝ ) ⁻¹ * ( 1 / 4 ) by positivity ] ) ];
  refine' le_trans _ ( h_integral.trans _ );
  · rw [ MeasureTheory.integral_indicator ] <;> norm_num [ hf ];
    exact le_of_abs_le ( MeasureTheory.norm_integral_le_integral_norm ( _ : ℝ → ℝ ) ) |> le_trans <| by norm_num;
  · grind

lemma test_value_le_autoconvolution_ratio_aux (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m) (s_lo ℓ : ℕ) (hℓ : 2 ≤ ℓ) :
    test_value n m c ℓ s_lo ≤ autoconvolution_ratio (step_function n m c) := by
  rw [ autoconvolution_ratio_eq n m hn hm c hc ];
  -- By combining the inequalities from the previous steps, we can conclude the proof.
  have h_combined : (4 * n / (ℓ * m ^ 2)) * sum_val n c s_lo ℓ ≤ (4 * n / (ℓ * m ^ 2)) * (ℓ * m ^ 2 / (1 / (4 * n))) * (MeasureTheory.eLpNorm (MeasureTheory.convolution (step_function n m c) (step_function n m c) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal := by
    have h_combined : (sum_val n c s_lo ℓ / m ^ 2) * (1 / (4 * n : ℝ)) ^ 2 ≤ (ℓ * (1 / (4 * n : ℝ))) * (MeasureTheory.eLpNorm (MeasureTheory.convolution (step_function n m c) (step_function n m c) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal := by
      have h_combined : (∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), MeasureTheory.integral MeasureTheory.volume (fun x => (let val := ∑ i : Fin (2 * n), ∑ j : Fin (2 * n), if i.1 + j.1 = k then (c i : ℝ) * (c j : ℝ) else 0; (val / m ^ 2) * triangle ((k + 1) * (1 / (4 * n : ℝ)) - 1 / 2) (1 / (4 * n : ℝ)) x))) ≤ (MeasureTheory.volume (Set.Icc (s_lo * (1 / (4 * n : ℝ)) - 1 / 2) ((s_lo + ℓ) * (1 / (4 * n : ℝ)) - 1 / 2))).toReal * (MeasureTheory.eLpNorm (MeasureTheory.convolution (step_function n m c) (step_function n m c) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal := by
        convert integral_convolution_subset n m hn hm c s_lo ℓ hℓ ( by linarith ) ( by omega ) |> le_trans <| integral_le_volume_mul_Linfty n m hn hm c s_lo ℓ using 1;
      convert h_combined using 1;
      · convert sum_integral_eq_sum_val_mul_sq_delta n m hn hm c s_lo ℓ |> Eq.symm using 1;
      · norm_num [ add_mul ];
    field_simp at *;
    convert h_combined using 1;
  convert h_combined using 1 <;> norm_num [ test_value_eq_sum_val ] ; ring;
  · convert test_value_eq_sum_val n m hn hm c s_lo ℓ using 1 ; ring;
  · field_simp;
    norm_num

theorem test_value_le_Linfty (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m) :
    (max_test_value n m c : ℝ) ≤ autoconvolution_ratio (step_function n m c) := by
  unfold max_test_value;
  field_simp;
  split_ifs <;> simp_all +decide [ Finset.max' ];
  · rintro b x hx₁ hx₂ y hy₁ rfl; exact test_value_le_autoconvolution_ratio_aux n m hn hm c hc y x hx₁;
  · linarith [ ‹∀ x : ℕ, 2 ≤ x → x ≤ 2 * ( 2 * n ) → n = 0› 2 ( by norm_num ) ( by linarith ) ]