/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 124a8efc-d6be-462e-ac99-eca09c3b8d0d

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise

noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

theorem exists_invariant_under_permutation {α : Type*} [DecidableEq α]
    (S : Finset α) (P : α → Prop) [DecidablePred P] :
    (∃ x ∈ S, P x) ↔ (∃ x ∈ S, P x) :=
  Iff.rfl

#check essSup

theorem conv_total {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) :
    ∑ k ∈ Finset.range (2*d-1),
      (∑ i : Fin d, ∑ j : Fin d, if i.1+j.1=k then c i * c j else 0) = m ^ 2 := by
  -- By Fubini's theorem, we can interchange the order of summation.
  have h_fubini : ∑ k ∈ Finset.range (2 * d - 1), ∑ i : Fin d, ∑ j : Fin d, (if i + j = k then c i * c j else 0) = ∑ i : Fin d, ∑ j : Fin d, ∑ k ∈ Finset.range (2 * d - 1), (if i + j = k then c i * c j else 0) := by
    exact Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_comm );
  simp_all +decide [ Finset.sum_ite, sq ];
  -- Since $i$ and $j$ are in $\text{Fin } d$, their values are between $0$ and $d-1$. Therefore, $i + j$ is always less than $2d-1$.
  have h_filter : ∀ i j : Fin d, i.val + j.val < 2 * d - 1 := by
    exact fun i j => lt_tsub_iff_left.mpr ( by linarith [ Fin.is_lt i, Fin.is_lt j ] );
  simp +decide [ ← hc, h_filter, Finset.sum_mul _ _ _ ];
  simp +decide only [Finset.mul_sum _ _ _]

theorem conv_entry_le_total {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) (k : ℕ) :
    (∑ i : Fin d, ∑ j : Fin d, if i.1+j.1=k then c i * c j else 0) ≤ m ^ 2 := by
  -- Since the sum of the products is less than or equal to the sum of m * m over all i and j, and the sum of m * m over all i and j is m^2, we can conclude that the sum of the products is less than or equal to m^2.
  have h_sum_bound : ∑ i : Fin d, ∑ j : Fin d, (if i.val + j.val = k then c i * c j else 0) ≤ ∑ i : Fin d, ∑ j : Fin d, c i * c j := by
    exact Finset.sum_le_sum fun i hi => Finset.sum_le_sum fun j hj => by split_ifs <;> nlinarith;
  simp_all +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul, sq ]

theorem int32_safe (m : ℕ) (hm : m ≤ 200) : m ^ 2 ≤ 2 ^ 31 - 1 := by
  native_decide +revert

theorem lintegral_le_essSup_mul_measure_ennreal {α : Type*} [MeasureTheory.MeasureSpace α]
    (f : α → ENNReal) (S : Set α) (h_supp : Function.support f ⊆ S) :
    ∫⁻ x, f x ∂MeasureTheory.volume ≤
    (essSup f MeasureTheory.volume) * (MeasureTheory.volume S) := by
  -- Apply the lemma that states the integral of a function is less than or equal to the essential supremum times the measure of the set where the function is non-zero.
  have h_integral_le_essSup_mul_measure : ∫⁻ x, f x ∂MeasureTheory.MeasureSpace.volume ≤ essSup f MeasureTheory.MeasureSpace.volume * MeasureTheory.MeasureSpace.volume (Function.support f) := by
    have h_integral_le_essSup_mul_measure : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, f x ≤ essSup f MeasureTheory.MeasureSpace.volume := by
      exact?
    generalize_proofs at *; (
    -- Since $f$ is non-zero only on the support, we can restrict the integral to the support.
    have h_integral_restrict : ∫⁻ x, f x ∂MeasureTheory.MeasureSpace.volume = ∫⁻ x in Function.support f, f x ∂MeasureTheory.MeasureSpace.volume := by
      exact?
    generalize_proofs at *; (
    -- Since $f$ is non-negative and bounded above by its essential supremum almost everywhere, we can apply the inequality for integrals.
    have h_integral_le_essSup_mul_measure : ∫⁻ x in Function.support f, f x ∂MeasureTheory.MeasureSpace.volume ≤ ∫⁻ x in Function.support f, essSup f MeasureTheory.MeasureSpace.volume ∂MeasureTheory.MeasureSpace.volume := by
      apply_rules [ MeasureTheory.lintegral_mono_ae ];
      exact MeasureTheory.ae_restrict_of_ae h_integral_le_essSup_mul_measure
    generalize_proofs at *; (
    simpa [ mul_comm ] using h_integral_restrict.le.trans h_integral_le_essSup_mul_measure)));
  exact h_integral_le_essSup_mul_measure.trans ( mul_le_mul_left' ( MeasureTheory.measure_mono h_supp ) _ )

theorem essSup_ge_lintegral_div_measure_ennreal {α : Type*} [MeasureTheory.MeasureSpace α]
    (f : α → ENNReal) (S : Set α) (h_supp : Function.support f ⊆ S)
    (hS_fin : MeasureTheory.volume S ≠ ⊤) (hS_pos : MeasureTheory.volume S ≠ 0) :
    essSup f MeasureTheory.volume ≥
    (∫⁻ x, f x ∂MeasureTheory.volume) / (MeasureTheory.volume S) := by
  -- Apply the theorem that states the integral of a function is less than or equal to the essential supremum times the measure of the set.
  have h_integral_le_essSup_mul_measure : ∫⁻ x, f x ∂MeasureTheory.volume ≤ essSup f MeasureTheory.volume * MeasureTheory.volume S := by
    -- Apply the theorem that states the integral of f is less than or equal to the essential supremum times the measure of S, given that the support of f is contained in S.
    apply lintegral_le_essSup_mul_measure_ennreal f S h_supp
  generalize_proofs at *; (
  exact?)

#check MeasureTheory.eLpNormEssSup

#check MeasureTheory.eLpNorm_exponent_top

theorem eLpNorm_eq_essSup_ofReal {α : Type*} [MeasureTheory.MeasureSpace α]
    (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) :
    MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume =
    essSup (fun x => ENNReal.ofReal (f x)) MeasureTheory.volume := by
  simp +decide [ MeasureTheory.eLpNormEssSup ];
  simp +decide only [Real.enorm_eq_ofReal (hf _)]

theorem eLpNorm_ge_integral_div_measure_real {α : Type*} [MeasureTheory.MeasureSpace α]
    (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) (S : Set α) (h_supp : Function.support f ⊆ S)
    (hS_fin : MeasureTheory.volume S ≠ ⊤) (hS_pos : MeasureTheory.volume S ≠ 0)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (h_fin : MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume ≠ ⊤) :
    (MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume).toReal ≥
    (MeasureTheory.integral MeasureTheory.volume f) / (MeasureTheory.volume S).toReal := by
      refine' div_le_iff₀ ( ENNReal.toReal_pos _ _ ) |>.2 _;
      · exact hS_pos;
      · exact hS_fin;
      · have h_integral_le : ∫⁻ x, ENNReal.ofReal (f x) ∂MeasureTheory.volume ≤ (essSup (fun x => ENNReal.ofReal (f x)) MeasureTheory.volume) * (MeasureTheory.volume S) := by
          convert lintegral_le_essSup_mul_measure_ennreal _ _ _ using 1 ; aesop ( simp_config := { singlePass := true } ) ;
        convert ENNReal.toReal_mono _ h_integral_le using 1 <;> norm_num [ MeasureTheory.eLpNormEssSup ];
        · rw [ MeasureTheory.integral_eq_lintegral_of_nonneg_ae ];
          · exact Filter.Eventually.of_forall hf;
          · exact hf_int.1;
        · simp +decide [ Real.enorm_eq_ofReal ( hf _ ) ];
        · refine' ENNReal.mul_ne_top _ _ <;> simp_all +decide [ MeasureTheory.eLpNormEssSup ];
          simp_all +decide [ ENNReal.ofReal, Real.enorm_eq_ofReal ( hf _ ) ]

theorem eLpNorm_ge_integral_div_measure_real_of_finite {α : Type*} [MeasureTheory.MeasureSpace α]
    (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) (S : Set α) (h_supp : Function.support f ⊆ S)
    (hS_fin : MeasureTheory.volume S ≠ ⊤) (hS_pos : MeasureTheory.volume S ≠ 0)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (h_fin : MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume ≠ ⊤) :
    (MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume).toReal ≥
    (MeasureTheory.integral MeasureTheory.volume f) / (MeasureTheory.volume S).toReal := by
      -- Apply the hypothesis `h_essSup_ge_integral_div_measure` with the given hypotheses.
      apply eLpNorm_ge_integral_div_measure_real f hf S h_supp hS_fin hS_pos hf_int h_fin