/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d2245f8f-c42a-486a-867f-d3ba8626c7c3

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have proved Claim 2.3 (Single-Bin Energy Cap) and Claim 2.2 (Asymmetry No-Margin).

For Claim 2.3, we proved `single_bin_energy_cap`, showing that for any bin $i$, $\|f*f\|_\infty \geq 2n \cdot M_i^2$. This relied on:
1. `f_restricted`: restricting $f$ to the bin $i$.
2. `convolution_mono`: showing $\|f*f\|_\infty \geq \|f_i*f_i\|_\infty$ using pointwise monotonicity of convolution for non-negative functions.
3. `convolution_support_Ico`: showing the support of $f_i*f_i$ is small (length $1/(2n)$).
4. `averaging_principle`: showing $\|g\|_\infty \geq (\int g) / \text{vol}(\text{supp } g)$.

For Claim 2.2, we proved:
1. `bin_boundary_at_zero`: The boundary between the left and right halves of the grid falls exactly at $x=0$.
2. `refinement_preserves_left_sum`: Refinement of the grid preserves the mass in the left half.
3. `asymmetry_threshold_exact`: The condition $L \geq \sqrt{c_\text{target}/2}$ implies $2L^2 \geq c_\text{target}$ directly, confirming no margin is needed.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  let norm_inf := (MeasureTheory.eLpNorm conv ⊤ MeasureTheory.volume).toReal
  let integral := MeasureTheory.integral MeasureTheory.volume f
  norm_inf / (integral ^ 2)

noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

noncomputable def canonical_discretization (f : ℝ → ℝ) (n m : ℕ) : Fin (2 * n) → ℕ :=
  fun i =>
    let masses := bin_masses f n
    let total_mass := ∑ j, masses j
    let cum_mass (k : ℕ) := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
    let target_cum (k : ℕ) := (cum_mass k) / total_mass * m
    let discrete_cum (k : ℕ) := ⌊target_cum k⌋.natAbs
    if i.1 + 1 < 2 * n then discrete_cum (i.1 + 1) - discrete_cum i.1
    else m - discrete_cum i.1

noncomputable def f_restricted (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) : ℝ → ℝ :=
  let δ := 1 / (4 * n : ℝ)
  let a := -(1/4 : ℝ) + i * δ
  let b := -(1/4 : ℝ) + (i + 1) * δ
  Set.indicator (Set.Ico a b) f

theorem bin_masses_nonneg (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n : ℕ) (i : Fin (2 * n)) :
    0 ≤ bin_masses f n i := by
      apply_rules [ MeasureTheory.integral_nonneg, Set.indicator_nonneg ] ; aesop

theorem f_restricted_integral (n : ℕ) (f : ℝ → ℝ) (i : Fin (2 * n)) :
    MeasureTheory.integral MeasureTheory.volume (f_restricted f n i) = bin_masses f n i := by
  unfold f_restricted bin_masses
  rfl

theorem f_ge_f_restricted (n : ℕ) (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x) (i : Fin (2 * n)) :
    ∀ x, f x ≥ f_restricted f n i x ∧ f_restricted f n i x ≥ 0 := by
      intros x
      simp [f_restricted];
      simp [Set.indicator] at *; aesop;

theorem convolution_comm_real (f g : ℝ → ℝ) :
    MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume =
    MeasureTheory.convolution g f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume := by
      ext x;
      have h_subst : ∀ {f g : ℝ → ℝ}, (∫ t, f t * g (x - t)) = (∫ t, g t * f (x - t)) := by
        intro f g; rw [ ← MeasureTheory.integral_sub_left_eq_self ] ; congr; ext; ring;
      exact h_subst

theorem f_has_compact_support (f : ℝ → ℝ) (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4)) :
    HasCompactSupport f := by
      have h_closure : closure (Function.support f) ⊆ Set.Icc (-1 / 4 : ℝ) (1 / 4) := by
        have h_closure_subset : closure (Function.support f) ⊆ closure (Set.Ioo (-1 / 4 : ℝ) (1 / 4)) := by
          apply closure_mono hf_supp;
        exact h_closure_subset.trans ( by rw [ closure_Ioo ( by norm_num ) ] );
      exact CompactIccSpace.isCompact_Icc.of_isClosed_subset ( isClosed_closure ) h_closure

theorem f_restricted_integrable (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n))
    (h_int : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.Integrable (f_restricted f n i) MeasureTheory.volume := by
  unfold f_restricted
  apply MeasureTheory.Integrable.indicator h_int measurableSet_Ico

theorem convolution_integral_eq (f g : ℝ → ℝ)
    (hf_nonneg : ∀ x, 0 ≤ f x) (hg_nonneg : ∀ x, 0 ≤ g x)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    MeasureTheory.integral MeasureTheory.volume
      (MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) =
    MeasureTheory.integral MeasureTheory.volume f *
    MeasureTheory.integral MeasureTheory.volume g := by
  -- Apply the convolution theorem, which states that the integral of the convolution of two functions is equal to the product of their integrals. This theorem is available in Lean as `MeasureTheory.integral_convolution`.
  apply MeasureTheory.integral_convolution;
  · -- The hypothesis `hf_int` directly states that `f` is integrable.
    exact hf_int;
  · -- Since $g$ is integrable by hypothesis, we can conclude the proof.
    exact hg_int

theorem convolution_support_Ico (a b : ℝ) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ico a b) :
    Function.support (MeasureTheory.convolution f f
      (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆
    Set.Ico (2 * a) (2 * b) := by
  intro x hx; simp_all +decide [ MeasureTheory.convolution ] ;
  -- Since the integral is non-zero, there must exist some $t$ such that $f(t) \neq 0$ and $f(x - t) \neq 0$.
  obtain ⟨t, ht⟩ : ∃ t, f t ≠ 0 ∧ f (x - t) ≠ 0 := by
    -- Since the integral is non-zero, there must exist some $t$ such that $f(t) * f(x - t) \neq 0$.
    obtain ⟨t, ht⟩ : ∃ t, f t * f (x - t) ≠ 0 := by
      exact not_forall.mp fun h => hx <| MeasureTheory.integral_eq_zero_of_ae <| Filter.Eventually.of_forall h;
    exact ⟨ t, by aesop_cat, by aesop_cat ⟩;
  constructor <;> linarith [ hf_supp t ht.1, hf_supp ( x - t ) ht.2 ]

theorem averaging_principle (g : ℝ → ℝ) (hg_nonneg : ∀ x, 0 ≤ g x)
    (S : Set ℝ) (hS : Function.support g ⊆ S)
    (vol : ℝ)
    (hS_meas : MeasureTheory.volume S = ENNReal.ofReal vol)
    (hvol : 0 < vol)
    (hg_bdd : MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume ≠ ⊤) :
    (MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume).toReal ≥
      MeasureTheory.integral MeasureTheory.volume g / vol := by
  rw [ ge_iff_le, div_le_iff₀ hvol ];
  -- Since $g$ is bounded above by its essential supremum almost everywhere, we have:
  have h_le_ess_sup : ∀ᵐ x ∂MeasureTheory.volume, g x ≤ (MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume).toReal := by
    have h_le_inf : ∀ᵐ x ∂MeasureTheory.volume, ‖g x‖ₑ ≤ essSup (fun x => ‖g x‖ₑ) MeasureTheory.volume := by
      exact?;
    filter_upwards [ h_le_inf ] with x hx using by simpa [ abs_of_nonneg ( hg_nonneg x ) ] using ENNReal.toReal_mono ( by aesop ) hx;
  have h_le_ess_sup_integral : ∫ x in S, g x ∂MeasureTheory.MeasureSpace.volume ≤ ∫ x in S, (MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume).toReal ∂MeasureTheory.MeasureSpace.volume := by
    refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
    · exact Filter.Eventually.of_forall hg_nonneg;
    · apply_rules [ MeasureTheory.integrable_const ];
      constructor ; aesop;
    · exact MeasureTheory.ae_restrict_of_ae h_le_ess_sup;
  simp_all +decide [ mul_comm, ENNReal.toReal_ofReal hvol.le ];
  convert h_le_ess_sup_integral using 1;
  · rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero fun x hx => by contrapose! hx; aesop ];
  · rw [ mul_comm, MeasureTheory.measureReal_def, hS_meas, ENNReal.toReal_ofReal hvol.le ]

theorem bin_boundary_at_zero (n : ℕ) (hn : n > 0) :
    (-1/4 : ℝ) + (n : ℝ) * (1 / (4 * (n : ℝ))) = 0 := by
  field_simp; ring

theorem refinement_preserves_left_sum (n : ℕ) (hn : n > 0)
    (parent : Fin (2 * n) → ℕ) (a : Fin (2 * n) → ℕ)
    (ha : ∀ i, a i ≤ parent i)
    (child : Fin (4 * n) → ℕ)
    (hc_even : ∀ i : Fin (2 * n), child ⟨2 * i.1, by omega⟩ = a i)
    (hc_odd : ∀ i : Fin (2 * n), child ⟨2 * i.1 + 1, by omega⟩ = parent i - a i) :
    ∑ j : Fin (2 * n), (child ⟨j.1, by omega⟩ : ℕ) =
    ∑ i : Fin n, (parent ⟨i.1, by omega⟩ : ℕ) := by
  have h_split_sum : ∑ j : Fin (2 * n), child ⟨j.val, by
    linarith [ Fin.is_lt j ]⟩ = ∑ i : Fin n, (child ⟨2 * i.val, by
    linarith [ Fin.is_lt i ]⟩ + child ⟨2 * i.val + 1, by
    grind⟩) := by
    have h_split : Finset.range (2 * n) = Finset.image (fun i => 2 * i) (Finset.range n) ∪ Finset.image (fun i => 2 * i + 1) (Finset.range n) := by
      ext i
      simp [Finset.mem_range, Finset.mem_image];
      exact ⟨ fun hi => by rcases Nat.even_or_odd' i with ⟨ k, rfl | rfl ⟩ <;> [ left; right ] <;> exact ⟨ k, by linarith, rfl ⟩, fun hi => by rcases hi with ( ⟨ k, hk, rfl ⟩ | ⟨ k, hk, rfl ⟩ ) <;> linarith ⟩
    generalize_proofs at *;
    rw [ Finset.sum_fin_eq_sum_range ];
    rw [ h_split, Finset.sum_union ] <;> norm_num [ Finset.sum_add_distrib ];
    · norm_num [ Finset.sum_range, Nat.lt_succ_iff ];
      exact Finset.sum_congr rfl fun i hi => by split_ifs <;> linarith [ Fin.is_lt i ] ;
    · norm_num [ Finset.disjoint_right ];
      intros; omega;
  generalize_proofs at *;
  grind

theorem asymmetry_threshold_exact (c_target : ℝ) (hct : 0 < c_target)
    (L : ℝ) (hL : L ≥ Real.sqrt (c_target / 2)) :
    2 * L ^ 2 ≥ c_target := by
  nlinarith [ Real.sqrt_nonneg ( c_target / 2 ), Real.mul_self_sqrt ( show 0 ≤ c_target / 2 by positivity ) ]

theorem convolution_integrand_mono (f1 f2 g1 g2 : ℝ → ℝ) (x : ℝ)
    (h_nonneg : ∀ t, 0 ≤ f1 t ∧ 0 ≤ f2 t ∧ 0 ≤ g1 t ∧ 0 ≤ g2 t)
    (h_le1 : ∀ t, f1 t ≤ g1 t)
    (h_le2 : ∀ t, f2 t ≤ g2 t) :
    ∀ t, f1 t * f2 (x - t) ≤ g1 t * g2 (x - t) := by
  intro t
  apply mul_le_mul
  · exact h_le1 t
  · exact h_le2 (x - t)
  · exact (h_nonneg (x - t)).2.1
  · exact (h_nonneg t).2.2.1

theorem convolution_mono_ae (f1 f2 g1 g2 : ℝ → ℝ)
    (h_nonneg : ∀ᵐ x ∂MeasureTheory.volume, 0 ≤ f1 x ∧ 0 ≤ f2 x ∧ 0 ≤ g1 x ∧ 0 ≤ g2 x)
    (h_le1 : ∀ᵐ x ∂MeasureTheory.volume, f1 x ≤ g1 x)
    (h_le2 : ∀ᵐ x ∂MeasureTheory.volume, f2 x ≤ g2 x)
    (h_int_g1 : MeasureTheory.Integrable g1 MeasureTheory.volume)
    (h_int_g2 : MeasureTheory.Integrable g2 MeasureTheory.volume) :
    ∀ᵐ x ∂MeasureTheory.volume,
      MeasureTheory.convolution f1 f2 (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤
      MeasureTheory.convolution g1 g2 (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  -- For almost every x, the function t ↦ g1(t)g2(x-t) is integrable.
  have h_integrable : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.Integrable (fun t => g1 t * g2 (x - t)) MeasureTheory.volume := by
    have h_integrable : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, MeasureTheory.Integrable (fun t => g1 t * g2 (x - t)) MeasureTheory.volume := by
      have h_conv_integrable : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => g1 p.1 * g2 p.2) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
        exact h_int_g1.prod_mul h_int_g2
      have h_conv_integrable : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => g1 p.1 * g2 (p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
        have h_measure_preserving : MeasureTheory.MeasurePreserving (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
          exact?
        have h_conv_integrable : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => g1 p.1 * g2 p.2) (MeasureTheory.Measure.map (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume)) := by
          rw [ h_measure_preserving.map_eq ] ; exact h_conv_integrable;
        convert h_conv_integrable.comp_measurable ( measurable_fst.prodMk ( measurable_snd.sub measurable_fst ) ) using 1;
      rw [ MeasureTheory.integrable_prod_iff' ] at h_conv_integrable ; aesop;
      exact h_conv_integrable.1;
    exact h_integrable;
  -- For such x, and for almost every t, we have 0 ≤ f1(t)f2(x-t) ≤ g1(t)g2(x-t).
  have h_le : ∀ᵐ x ∂MeasureTheory.volume, ∀ᵐ t ∂MeasureTheory.volume, 0 ≤ f1 t * f2 (x - t) ∧ f1 t * f2 (x - t) ≤ g1 t * g2 (x - t) := by
    have h_le : ∀ᵐ x ∂MeasureTheory.volume, ∀ᵐ t ∂MeasureTheory.volume, 0 ≤ f1 t ∧ 0 ≤ f2 (x - t) ∧ f1 t ≤ g1 t ∧ f2 (x - t) ≤ g2 (x - t) := by
      filter_upwards [ h_integrable ] with x hx;
      have h_le : ∀ᵐ t ∂MeasureTheory.volume, 0 ≤ f1 t ∧ 0 ≤ f2 (x - t) ∧ f1 t ≤ g1 t ∧ f2 (x - t) ≤ g2 (x - t) := by
        have h_le1 : ∀ᵐ t ∂MeasureTheory.volume, f1 t ≤ g1 t := h_le1
        have h_le2 : ∀ᵐ t ∂MeasureTheory.volume, f2 (x - t) ≤ g2 (x - t) := by
          rw [ MeasureTheory.ae_iff ] at *;
          convert h_le2 using 1;
          rw [ show { a : ℝ | ¬f2 ( x - a ) ≤ g2 ( x - a ) } = ( fun a => x - a ) ⁻¹' { a : ℝ | ¬f2 a ≤ g2 a } by ext; simp +decide ];
          -- The volume of a set is invariant under translation.
          have h_volume_invariant : ∀ (S : Set ℝ), MeasureTheory.volume (Set.preimage (fun a => x - a) S) = MeasureTheory.volume S := by
            intro S; exact (by
            rw [ show ( fun a => x - a ) ⁻¹' S = ( fun a => -a ) ⁻¹' ( S.preimage fun a => x + a ) by ext; simp +decide [ sub_eq_add_neg ] ];
            simp +zetaDelta at *);
          exact h_volume_invariant _
        have h_nonneg1 : ∀ᵐ t ∂MeasureTheory.volume, 0 ≤ f1 t := by
          filter_upwards [ h_nonneg ] with t ht using ht.1
        have h_nonneg2 : ∀ᵐ t ∂MeasureTheory.volume, 0 ≤ f2 (x - t) := by
          have h_nonneg2 : ∀ᵐ t ∂MeasureTheory.volume, 0 ≤ f2 t := by
            filter_upwards [ h_nonneg ] with t ht using ht.2.1;
          rw [ MeasureTheory.ae_iff ] at *;
          rw [ show { a : ℝ | ¬0 ≤ f2 ( x - a ) } = ( fun t => x - t ) ⁻¹' { a : ℝ | ¬0 ≤ f2 a } by ext; simp +decide ];
          rw [ show ( fun t => x - t ) ⁻¹' { a : ℝ | ¬0 ≤ f2 a } = ( fun t => -t ) ⁻¹' ( { a : ℝ | ¬0 ≤ f2 a } - { x } ) by ext; simp +decide [ sub_eq_add_neg, add_comm, add_left_comm, add_assoc ] ];
          convert h_nonneg2 using 1;
          simp +zetaDelta at *;
          erw [ Set.image_add_right ] ; norm_num;
          rw [ show { a : ℝ | f2 ( a + x ) < 0 } = ( fun a => a + x ) ⁻¹' { a : ℝ | f2 a < 0 } by rfl, MeasureTheory.measure_preimage_add_right ]
        filter_upwards [ h_nonneg1, h_nonneg2, h_le1, h_le2 ] with t ht1 ht2 ht3 ht4 using ⟨ ht1, ht2, ht3, ht4 ⟩;
      exact h_le;
    filter_upwards [ h_le ] with x hx using by filter_upwards [ hx ] with t ht using ⟨ mul_nonneg ht.1 ht.2.1, mul_le_mul ht.2.2.1 ht.2.2.2 ( by linarith ) ( by linarith ) ⟩ ;
  filter_upwards [ h_integrable, h_le ] with x hx hx';
  refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
  · filter_upwards [ hx' ] with t ht using ht.1;
  · exact hx;
  · filter_upwards [ hx' ] with t ht using ht.2

theorem convolution_mono (f1 f2 g1 g2 : ℝ → ℝ)
    (h_nonneg : ∀ x, 0 ≤ f1 x ∧ 0 ≤ f2 x ∧ 0 ≤ g1 x ∧ 0 ≤ g2 x)
    (h_le1 : ∀ x, f1 x ≤ g1 x)
    (h_le2 : ∀ x, f2 x ≤ g2 x)
    (h_int_f1 : MeasureTheory.Integrable f1 MeasureTheory.volume)
    (h_int_f2 : MeasureTheory.Integrable f2 MeasureTheory.volume)
    (h_int_g1 : MeasureTheory.Integrable g1 MeasureTheory.volume)
    (h_int_g2 : MeasureTheory.Integrable g2 MeasureTheory.volume) :
    ∀ᵐ x ∂MeasureTheory.volume,
      MeasureTheory.convolution f1 f2 (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤
      MeasureTheory.convolution g1 g2 (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  -- The convolution is defined as an integral. We compare the integrals.
  -- The integrand for (f1 * f2)(x) is t ↦ f1(t) * f2(x - t).
  -- The integrand for (g1 * g2)(x) is t ↦ g1(t) * g2(x - t).
  -- We know f1(t) ≤ g1(t) and f2(x - t) ≤ g2(x - t) and all are non-negative.
  -- Thus f1(t) * f2(x - t) ≤ g1(t) * g2(x - t).
  -- If the larger integrand is integrable, then the integral is monotonic.
  -- The convolution of integrable functions is integrable, so for a.e. x, the integrand is integrable.
  have h_integrable_g : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.Integrable (fun t => g1 t * g2 (x - t)) MeasureTheory.volume := by
    -- This follows from the fact that g1 * g2 is defined a.e.
    -- We can use MeasureTheory.Integrable.convolution_integrand or similar if available,
    -- or derive it from the integrability of the convolution.
    have h_fubini : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.Integrable (fun t => g1 t * g2 (x - t)) MeasureTheory.volume := by
      have h_convolution : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => g1 p.1 * g2 p.2) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
        exact h_int_g1.prod_mul h_int_g2
      have h_convolution : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => g1 p.1 * g2 (p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
        have h_convolution : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => g1 p.1 * g2 p.2) (MeasureTheory.Measure.map (fun p => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume)) := by
          have h_convolution : MeasureTheory.MeasurePreserving (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
            exact?;
          rw [ h_convolution.map_eq ] ; assumption;
        convert h_convolution.comp_measurable ( measurable_fst.prodMk ( measurable_snd.sub measurable_fst ) ) using 1;
      rw [ MeasureTheory.integrable_prod_iff' ] at h_convolution ; aesop;
      exact h_convolution.1;
    exact h_fubini
  filter_upwards [h_integrable_g] with x h_int_gx
  simp [MeasureTheory.convolution]
  apply MeasureTheory.integral_mono_of_nonneg
  · -- Non-negativity of f1 * f2
    filter_upwards with t
    exact mul_nonneg (h_nonneg t).1 (h_nonneg (x - t)).2.1
  · -- Integrability of g1 * g2 integrand
    exact h_int_gx
  · -- Pointwise inequality
    filter_upwards with t
    apply mul_le_mul (h_le1 t) (h_le2 (x - t)) (h_nonneg (x - t)).2.1 (h_nonneg t).2.2.1

theorem single_bin_energy_cap (n : ℕ) (hn : n > 0)
    (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (h_conv_bdd : MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≠ ⊤)
    (i : Fin (2 * n)) :
    let M_i := bin_masses f n i
    autoconvolution_ratio f ≥ (2 * n : ℝ) * M_i ^ 2 := by
  -- By the properties of the convolution and the L^∞ norm, we have that the convolution of f_restricted f n i with itself has an L^∞ norm at least 2n * (bin_masses f n i)^2.
  have h_conv_norm : (MeasureTheory.eLpNorm (MeasureTheory.convolution (f_restricted f n i) (f_restricted f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥ 2 * n * (bin_masses f n i)^2 := by
    have h_conv_norm : (MeasureTheory.eLpNorm (MeasureTheory.convolution (f_restricted f n i) (f_restricted f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥ (MeasureTheory.integral MeasureTheory.volume (f_restricted f n i)) ^ 2 / (1 / (2 * n)) := by
      have h_conv_norm : (MeasureTheory.eLpNorm (MeasureTheory.convolution (f_restricted f n i) (f_restricted f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥ (MeasureTheory.integral MeasureTheory.volume (MeasureTheory.convolution (f_restricted f n i) (f_restricted f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume)) / (1 / (2 * n)) := by
        apply_rules [ averaging_principle ];
        any_goals exact Set.Ico ( 2 * ( - ( 1 / 4 ) + i * ( 1 / ( 4 * n ) ) ) ) ( 2 * ( - ( 1 / 4 ) + ( i + 1 ) * ( 1 / ( 4 * n ) ) ) );
        · intro x
          simp [MeasureTheory.convolution];
          exact MeasureTheory.integral_nonneg fun t => mul_nonneg ( by unfold f_restricted; exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _ ) ( by unfold f_restricted; exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _ );
        · apply convolution_support_Ico;
          intro x hx; unfold f_restricted at hx; aesop;
        · norm_num [ mul_add, mul_div ] ; ring;
        · positivity;
        · have h_conv_bdd : MeasureTheory.eLpNorm (MeasureTheory.convolution (f_restricted f n i) (f_restricted f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≤ MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume := by
            have h_conv_mono : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.convolution (f_restricted f n i) (f_restricted f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤ MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
              have h_nonneg : ∀ᵐ x ∂MeasureTheory.volume, 0 ≤ f_restricted f n i x ∧ 0 ≤ f_restricted f n i x ∧ 0 ≤ f x ∧ 0 ≤ f x := by
                filter_upwards [ ] with x using ⟨ by exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _, by exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _, hf_nonneg _, hf_nonneg _ ⟩ ;
              apply convolution_mono_ae; assumption; exact (by
              filter_upwards [ ] with x using f_ge_f_restricted n f hf_nonneg i x |>.1 |> le_trans <| by norm_num;); exact (by
              filter_upwards [ ] with x using f_ge_f_restricted n f hf_nonneg i x |>.1 |> le_trans <| by norm_num;); (
              exact MeasureTheory.integrable_of_integral_eq_one hf_int); (
              exact MeasureTheory.integrable_of_integral_eq_one hf_int);
            exact (by
            apply_rules [ MeasureTheory.eLpNorm_mono_ae ];
            filter_upwards [ h_conv_mono ] with x hx;
            rw [ Real.norm_of_nonneg, Real.norm_of_nonneg ];
            · exact hx;
            · exact MeasureTheory.integral_nonneg fun y => mul_nonneg ( hf_nonneg _ ) ( hf_nonneg _ );
            · exact MeasureTheory.integral_nonneg fun y => mul_nonneg ( show 0 ≤ f_restricted f n i y from by rw [ f_restricted ] ; exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _ ) ( show 0 ≤ f_restricted f n i ( x - y ) from by rw [ f_restricted ] ; exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _ )); -- Just need to complete the proof by showing the desired inequality for the L-infinity norm.;
          exact ne_of_lt ( lt_of_le_of_lt h_conv_bdd ( lt_top_iff_ne_top.mpr ‹_› ) );
      convert h_conv_norm using 2 ; rw [ convolution_integral_eq ] ; ring;
      · exact fun x => by unfold f_restricted; exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
      · exact fun x => f_ge_f_restricted n f hf_nonneg i x |>.2;
      · refine' MeasureTheory.Integrable.indicator _ _;
        · exact MeasureTheory.integrable_of_integral_eq_one hf_int;
        · exact measurableSet_Ico;
      · apply_rules [ MeasureTheory.Integrable.indicator, hf_int ];
        · exact MeasureTheory.integrable_of_integral_eq_one hf_int;
        · exact measurableSet_Ico;
    convert h_conv_norm using 1 ; ring! ; norm_num [ f_restricted_integral ] ; ring!;
  -- By the properties of the convolution and the L^∞ norm, we have that the convolution of f with itself has an L^∞ norm at least as large as the convolution of f_restricted f n i with itself.
  have h_conv_ge : (MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥ (MeasureTheory.eLpNorm (MeasureTheory.convolution (f_restricted f n i) (f_restricted f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal := by
    have h_conv_mono : ∀ᵐ x ∂MeasureTheory.volume, (MeasureTheory.convolution (f_restricted f n i) (f_restricted f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) x ≤ (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) x := by
      apply convolution_mono_ae;
      · simp [f_restricted, hf_nonneg];
        exact Filter.Eventually.of_forall fun x => by rw [ Set.indicator_apply ] ; aesop;
      · exact Filter.Eventually.of_forall fun x => f_ge_f_restricted n f hf_nonneg i x |>.1;
      · exact Filter.Eventually.of_forall fun x => f_ge_f_restricted n f hf_nonneg i x |>.1;
      · exact MeasureTheory.integrable_of_integral_eq_one hf_int;
      · exact MeasureTheory.integrable_of_integral_eq_one hf_int;
    refine' ENNReal.toReal_mono _ _;
    · assumption;
    · apply_rules [ MeasureTheory.eLpNorm_mono_ae ];
      filter_upwards [ h_conv_mono ] with x hx using by rw [ Real.norm_of_nonneg ( by
        refine' MeasureTheory.integral_nonneg fun y => mul_nonneg _ _;
        · exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
        · exact Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _ ), Real.norm_of_nonneg ( by
        exact MeasureTheory.integral_nonneg fun y => mul_nonneg ( hf_nonneg _ ) ( hf_nonneg _ ) ) ] ; exact hx;
  refine le_trans h_conv_norm <| h_conv_ge.trans ?_ ; unfold autoconvolution_ratio ; aesop;