/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 09b5fd79-43df-4525-9d9c-48a95bacdc12

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  let norm_inf := (MeasureTheory.eLpNorm conv ⊤ MeasureTheory.volume).toReal
  let integral := MeasureTheory.integral MeasureTheory.volume f
  norm_inf / (integral ^ 2)

noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

noncomputable def canonical_discretization (f : ℝ → ℝ) (n m : ℕ) : Fin (2 * n) → ℕ :=
  fun i =>
    let masses := bin_masses f n
    let total_mass := ∑ j, masses j
    let cum_mass (k : ℕ) := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
    let target_cum (k : ℕ) := (cum_mass k) / total_mass * m
    let discrete_cum (k : ℕ) := ⌊target_cum k⌋.natAbs
    if i.1 + 1 < 2 * n then discrete_cum (i.1 + 1) - discrete_cum i.1
    else m - discrete_cum i.1

def discrete_autoconvolution {d : ℕ} (a : Fin d → ℝ) (k : ℕ) : ℝ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then a i * a j else 0

noncomputable def test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let a : Fin d → ℝ := fun i => (4 * n : ℝ) / m * (c i : ℝ)
  let conv := discrete_autoconvolution a
  let sum_conv := ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), conv k
  (1 / (4 * n * ℓ : ℝ)) * sum_conv

noncomputable def max_test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) : ℝ :=
  let d := 2 * n
  let range_ell := Finset.Icc 2 (2 * d)
  let range_s_lo := Finset.range (2 * d)
  let values := range_ell.biUnion (fun ℓ => range_s_lo.image (fun s_lo => test_value n m c ℓ s_lo))
  if h : values.Nonempty then values.max' h else 0

/-
The sum of the bin masses equals 1.
-/
lemma sum_bin_masses_eq_one (n : ℕ) (hn : n > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1) :
    ∑ i : Fin (2 * n), bin_masses f n i = 1 := by
  convert hf_int using 1;
  -- By definition of $bin\_masses$, we can rewrite the sum as an integral over $[-1/4, 1/4)$.
  have h_sum_eq_integral : ∑ i : Fin (2 * n), MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico (-(1 / 4 : ℝ) + i.val * (1 / (4 * n : ℝ))) (-(1 / 4 : ℝ) + (i.val + 1) * (1 / (4 * n : ℝ)))) f) = ∫ x in Set.Ico (-(1 / 4 : ℝ)) (-(1 / 4 : ℝ) + 2 * n * (1 / (4 * n : ℝ))), f x := by
    have h_sum_eq_integral : ∑ i : Fin (2 * n), ∫ x in Set.Ico (-(1 / 4 : ℝ) + i.val * (1 / (4 * n : ℝ))) (-(1 / 4 : ℝ) + (i.val + 1) * (1 / (4 * n : ℝ))), f x = ∫ x in Set.Ico (-(1 / 4 : ℝ)) (-(1 / 4 : ℝ) + 2 * n * (1 / (4 * n : ℝ))), f x := by
      have h_sum_eq_integral : ∀ m : ℕ, ∑ i ∈ Finset.range m, ∫ x in Set.Ico (-(1 / 4 : ℝ) + i * (1 / (4 * n : ℝ))) (-(1 / 4 : ℝ) + (i + 1) * (1 / (4 * n : ℝ))), f x = ∫ x in Set.Ico (-(1 / 4 : ℝ)) (-(1 / 4 : ℝ) + m * (1 / (4 * n : ℝ))), f x := by
        intro m
        induction' m with m ih;
        · norm_num;
        · rw [ Finset.sum_range_succ, ih, Nat.cast_succ, add_mul, one_mul, ← MeasureTheory.setIntegral_union ] <;> norm_num;
          · rw [ Set.Ico_union_Ico_eq_Ico ] <;> ring <;> norm_num [ hn ];
          · exact MeasureTheory.Integrable.integrableOn ( MeasureTheory.integrable_of_integral_eq_one hf_int );
          · exact MeasureTheory.Integrable.integrableOn ( MeasureTheory.integrable_of_integral_eq_one hf_int );
      simpa [ Finset.sum_range ] using h_sum_eq_integral ( 2 * n );
    convert h_sum_eq_integral using 2;
    rw [ MeasureTheory.integral_indicator ( measurableSet_Ico ) ];
  convert h_sum_eq_integral using 1;
  rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero ] ; ring_nf ; norm_num [ hn.ne' ];
  exact fun x hx => Classical.not_not.1 fun hx' => by have := hf_supp hx'; exact this.2.not_le <| hx <| by linarith [ this.1 ] ;

/-
The discretization error for each bin is at most $1/m$.
-/
lemma discretization_error_bound (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1) :
    ∀ i : Fin (2 * n), |(canonical_discretization f n m i : ℝ) / m - bin_masses f n i| ≤ 1 / m := by
  intro i;
  -- By definition of $D_k$ and $M_k$, we have $|D_k - M_k| \leq 1$.
  have h_diff : ∀ k : ℕ, k ≤ 2 * n → |(⌊(∑ j ∈ Finset.univ.filter (fun j => j.val < k), (bin_masses f n j)) / (∑ j ∈ Finset.univ, (bin_masses f n j)) * m⌋ : ℝ) - (∑ j ∈ Finset.univ.filter (fun j => j.val < k), (bin_masses f n j)) / (∑ j ∈ Finset.univ, (bin_masses f n j)) * m| ≤ 1 := by
    exact fun k hk => abs_sub_le_iff.mpr ⟨ by linarith [ Int.floor_le ( ( ( ∑ j ∈ Finset.univ.filter fun j : Fin ( 2 * n ) => ( j : ℕ ) < k, bin_masses f n j ) / ∑ j : Fin ( 2 * n ), bin_masses f n j ) * m ) ], by linarith [ Int.lt_floor_add_one ( ( ( ∑ j ∈ Finset.univ.filter fun j : Fin ( 2 * n ) => ( j : ℕ ) < k, bin_masses f n j ) / ∑ j : Fin ( 2 * n ), bin_masses f n j ) * m ) ] ⟩;
  -- By definition of $c_i$, we have $c_i = D_{i+1} - D_i$.
  have h_ci : (canonical_discretization f n m i : ℝ) = (⌊(∑ j ∈ Finset.univ.filter (fun j => j.val < i.val + 1), (bin_masses f n j)) / (∑ j ∈ Finset.univ, (bin_masses f n j)) * m⌋ : ℝ) - (⌊(∑ j ∈ Finset.univ.filter (fun j => j.val < i.val), (bin_masses f n j)) / (∑ j ∈ Finset.univ, (bin_masses f n j)) * m⌋ : ℝ) := by
    unfold canonical_discretization; norm_num [ Finset.sum_ite ] ;
    split_ifs <;> simp_all +decide [ Finset.sum_ite, Nat.lt_succ_iff ];
    · rw [ Nat.cast_sub ] <;> norm_num [ abs_of_nonneg, Int.floor_nonneg ];
      · rw [ abs_of_nonneg, abs_of_nonneg ] <;> norm_cast;
        · refine' Int.floor_nonneg.mpr _;
          refine' mul_nonneg ( div_nonneg _ _ ) ( Nat.cast_nonneg _ );
          · refine' Finset.sum_nonneg fun _ _ => _;
            exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun x hx => hf_nonneg x ) _;
          · refine' Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun x => _;
            rw [ Set.indicator_apply ] ; aesop;
        · exact Int.floor_nonneg.mpr ( mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => by
            exact MeasureTheory.integral_nonneg fun x => by unfold Set.indicator; aesop; ) ( Finset.sum_nonneg fun _ _ => by
            exact MeasureTheory.integral_nonneg fun x => by unfold Set.indicator; aesop; ) ) ( Nat.cast_nonneg _ ) );
      · rw [ show ( Finset.filter ( fun x : Fin ( 2 * n ) => x ≤ i ) Finset.univ : Finset ( Fin ( 2 * n ) ) ) = Finset.filter ( fun x : Fin ( 2 * n ) => x < i ) Finset.univ ∪ { i } from ?_, Finset.sum_union ] <;> norm_num [ Finset.sum_singleton, Finset.sum_union, Finset.sum_filter, Finset.sum_range, Finset.sum_range_succ, Nat.lt_succ_iff ];
        · rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg, Int.natAbs_of_nonneg ] <;> norm_num [ Finset.sum_ite ];
          · gcongr;
            · refine' Finset.sum_nonneg fun _ _ => _;
              exact MeasureTheory.integral_nonneg fun x => by unfold Set.indicator; aesop;
            · refine' le_add_of_nonneg_right _;
              exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun x hx => hf_nonneg x ) _;
          · refine' Int.floor_nonneg.mpr _;
            refine' mul_nonneg ( div_nonneg _ _ ) ( Nat.cast_nonneg _ );
            · refine' add_nonneg ( Finset.sum_nonneg fun _ _ => _ ) _;
              · exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun _ _ => hf_nonneg x ) _;
              · exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun x hx => hf_nonneg x ) _;
            · refine' Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun x => _;
              rw [ Set.indicator_apply ] ; aesop;
          · refine' Int.floor_nonneg.mpr _;
            refine' mul_nonneg ( div_nonneg _ _ ) ( Nat.cast_nonneg _ );
            · refine' Finset.sum_nonneg fun _ _ => _;
              exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun x hx => hf_nonneg x ) _;
            · refine' Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun x => _;
              rw [ Set.indicator_apply ] ; aesop;
        · grind +ring;
    · rw [ Nat.cast_sub ];
      · rw [ show ( ∑ x : Fin ( 2 * n ) with x ≤ i, bin_masses f n x ) = ∑ x : Fin ( 2 * n ), bin_masses f n x from ?_ ];
        · rw [ show ( ∑ x : Fin ( 2 * n ), bin_masses f n x ) = 1 from ?_ ] ; norm_num [ hm.ne' ];
          · refine' Int.floor_nonneg.mpr _;
            refine' mul_nonneg ( Finset.sum_nonneg fun _ _ => _ ) ( Nat.cast_nonneg _ );
            exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun _ _ => hf_nonneg x ) _;
          · convert sum_bin_masses_eq_one n hn f _ _ using 1 <;> aesop;
        · refine' Finset.sum_subset _ _ <;> simp +decide [ Finset.subset_iff ];
          exact fun x hx => False.elim <| hx.not_le <| Nat.le_of_lt_succ <| by linarith [ Fin.is_lt i, Fin.is_lt x ] ;
      · rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ];
        · refine' Int.le_of_lt_add_one ( Int.floor_lt.mpr _ );
          refine' lt_of_le_of_lt ( mul_le_mul_of_nonneg_right ( div_le_one_of_le₀ _ _ ) ( Nat.cast_nonneg _ ) ) _ <;> norm_num;
          · exact Finset.sum_le_sum_of_subset_of_nonneg ( Finset.filter_subset _ _ ) fun _ _ _ => by
              exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun _ _ => hf_nonneg x ) _;
          · refine' Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun x => _;
            rw [ Set.indicator_apply ] ; aesop;
        · refine' Int.floor_nonneg.mpr _;
          refine' mul_nonneg ( div_nonneg _ _ ) ( Nat.cast_nonneg _ );
          · refine' Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun x => _;
            rw [ Set.indicator_apply ] ; aesop;
          · refine' Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun x => _;
            rw [ Set.indicator_apply ] ; aesop;
  -- By definition of $bin_masses$, we have $\sum_{j=0}^{2n-1} bin_masses f n j = 1$.
  have h_sum_bin_masses : ∑ j ∈ Finset.univ, (bin_masses f n j) = 1 := by
    convert sum_bin_masses_eq_one n hn f hf_supp hf_int using 1;
  simp_all +decide [ abs_le, div_le_iff₀, le_div_iff₀ ];
  have := h_diff ( i + 1 ) ( by linarith [ Fin.is_lt i ] ) ; ( have := h_diff i ( by linarith [ Fin.is_lt i ] ) ; simp_all +decide [ Finset.sum_filter, Finset.sum_range, Nat.lt_succ_iff ] ; );
  rw [ show ( ∑ a : Fin ( 2 * n ), if a ≤ i then bin_masses f n a else 0 ) = ( ∑ a : Fin ( 2 * n ), if a < i then bin_masses f n a else 0 ) + bin_masses f n i from ?_ ] at *;
  · field_simp;
    constructor <;> linarith [ Int.floor_le ( ( ( ∑ a : Fin ( 2 * n ), if a < i then bin_masses f n a else 0 ) + bin_masses f n i ) * m ), Int.lt_floor_add_one ( ( ( ∑ a : Fin ( 2 * n ), if a < i then bin_masses f n a else 0 ) + bin_masses f n i ) * m ), Int.floor_le ( ( ∑ a : Fin ( 2 * n ), if a < i then bin_masses f n a else 0 ) * m ), Int.lt_floor_add_one ( ( ∑ a : Fin ( 2 * n ), if a < i then bin_masses f n a else 0 ) * m ) ];
  · rw [ Finset.sum_eq_sum_diff_singleton_add ( Finset.mem_univ i ) ];
    rw [ Finset.sum_congr rfl fun x hx => if_congr ( by exact ⟨ fun h => lt_of_le_of_ne h ( by aesop ), fun h => le_of_lt h ⟩ ) rfl rfl ] ; simp +decide [ Finset.sum_ite, Finset.filter_lt_eq_Ioi ];
    rw [ Finset.sdiff_singleton_eq_erase, Finset.filter_erase ] ; aesop;
  · rw [ Finset.sum_eq_sum_diff_singleton_add ( Finset.mem_univ i ) ];
    rw [ Finset.sum_congr rfl fun x hx => if_congr ( by exact ⟨ fun hx' => lt_of_le_of_ne hx' ( by aesop ), fun hx' => le_of_lt hx' ⟩ ) rfl rfl ] ; simp +decide [ Finset.sum_ite, Finset.filter_lt_eq_Ioi ];
    rw [ Finset.sdiff_singleton_eq_erase, Finset.filter_erase ] ; aesop;
  · rw [ Finset.sum_eq_sum_diff_singleton_add ( Finset.mem_univ i ) ];
    rw [ Finset.sum_congr rfl fun x hx => if_congr ( by exact ⟨ fun hx' => lt_of_le_of_ne hx' ( by aesop ), fun hx' => le_of_lt hx' ⟩ ) rfl rfl ] ; simp +decide [ Finset.sum_ite, Finset.filter_lt_eq_Ioi ];
    rw [ Finset.sdiff_singleton_eq_erase, Finset.filter_erase ] ; aesop

noncomputable def target_cum_mass (f : ℝ → ℝ) (n m : ℕ) (k : ℕ) : ℝ :=
  let masses := bin_masses f n
  let total_mass := ∑ j, masses j
  let cum_mass := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
  (cum_mass) / total_mass * m

noncomputable def discrete_cum_mass (f : ℝ → ℝ) (n m : ℕ) (k : ℕ) : ℕ :=
  ⌊target_cum_mass f n m k⌋.natAbs

noncomputable def delta (f : ℝ → ℝ) (n m : ℕ) (i : Fin (2 * n)) : ℝ :=
  (canonical_discretization f n m i : ℝ) / m - bin_masses f n i

noncomputable def test_value_continuous (n : ℕ) (f : ℝ → ℝ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let a : Fin d → ℝ := fun i => (4 * n : ℝ) * bin_masses f n i
  let conv := discrete_autoconvolution a
  let sum_conv := ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), conv k
  (1 / (4 * n * ℓ : ℝ)) * sum_conv

/-
The partial sum of the discretization error is bounded by $1/m$.
-/
lemma partial_sum_delta_bound (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (k : ℕ) (hk : k ≤ 2 * n) :
    |∑ i : Fin k, delta f n m (Fin.castLE hk i)| ≤ 1 / m := by
  -- By definition of $D_k$, we have $D_k = \lfloor M_k \cdot m \rfloor$ where $M_k = \sum_{i=0}^{k-1} \text{bin\_masses}(f, n)_i$.
  set M_k := ∑ i : Fin k, bin_masses f n (Fin.castLE hk i)
  set D_k := ⌊M_k * m⌋.natAbs
  have h_Dk : ∑ i : Fin k, (canonical_discretization f n m (Fin.castLE hk i) : ℝ) = D_k := by
    -- By definition of $D_k$, we have $D_k = \sum_{i=0}^{k-1} (canonical\_discretization f n m (Fin.castLE hk i))$.
    have h_Dk_def : ∑ i : Fin k, (canonical_discretization f n m (Fin.castLE hk i) : ℝ) = ∑ i ∈ Finset.range k, (discrete_cum_mass f n m (i + 1) - discrete_cum_mass f n m i) := by
      simp +decide [ Finset.sum_range, Finset.sum_range_succ, canonical_discretization ];
      refine' Finset.sum_congr rfl fun i hi => _;
      split_ifs <;> norm_cast;
      rw [ show ( i : ℕ ) + 1 = 2 * n by linarith [ Fin.is_lt i ] ] ; norm_num [ discrete_cum_mass ] ; ring;
      unfold target_cum_mass; norm_num [ mul_comm n, Finset.sum_ite ] ; ring;
      rw [ show ( ∑ x : Fin ( 2 * n ), bin_masses f n x ) = 1 by exact sum_bin_masses_eq_one n hn f hf_supp hf_int ] ; norm_num [ hm.ne' ];
    rw [ h_Dk_def, Nat.cast_sum ];
    rw [ Finset.sum_congr rfl fun i hi => Nat.cast_sub <| show discrete_cum_mass f n m ( i + 1 ) ≥ discrete_cum_mass f n m i from ?_ ];
    · convert Finset.sum_range_sub ( fun i => ( discrete_cum_mass f n m i : ℝ ) ) k using 1 ; norm_num [ D_k ];
      unfold discrete_cum_mass; norm_num;
      unfold target_cum_mass; norm_num [ M_k ] ; ring;
      rw [ show ( ∑ j : Fin ( 2 * n ), bin_masses f n j ) = 1 from ?_ ] ; norm_num [ mul_comm ];
      · rw [ ← Finset.sum_subset ( Finset.subset_univ ( Finset.image ( fun i : Fin k => Fin.castLE hk i ) Finset.univ ) ) ] <;> norm_num [ Finset.sum_image, Fin.val_injective.eq_iff ];
        exact fun x hx₁ hx₂ => False.elim <| hx₁ ⟨ x, hx₂ ⟩ rfl;
      · convert sum_bin_masses_eq_one n hn f hf_supp hf_int using 1;
    · unfold discrete_cum_mass;
      unfold target_cum_mass;
      field_simp;
      rw [ show ( ∑ j : Fin ( 2 * n ), if ( j : ℕ ) < i + 1 then bin_masses f n j else 0 ) = ( ∑ j : Fin ( 2 * n ), if ( j : ℕ ) < i then bin_masses f n j else 0 ) + ( ∑ j : Fin ( 2 * n ), if ( j : ℕ ) = i then bin_masses f n j else 0 ) from ?_ ];
      · rw [ show ( ∑ j : Fin ( 2 * n ), if ( j : ℕ ) = i then bin_masses f n j else 0 ) = bin_masses f n ⟨ i, by linarith [ Finset.mem_range.mp hi ] ⟩ from ?_ ];
        · rw [ show ( ∑ j : Fin ( 2 * n ), bin_masses f n j ) = 1 from ?_ ];
          · norm_num [ mul_comm ];
            rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg <| Int.floor_nonneg.mpr <| mul_nonneg ( Nat.cast_nonneg _ ) <| Finset.sum_nonneg fun _ _ => ?_, Int.natAbs_of_nonneg <| Int.floor_nonneg.mpr <| mul_nonneg ( Nat.cast_nonneg _ ) <| add_nonneg ( Finset.sum_nonneg fun _ _ => ?_ ) <| ?_ ];
            · gcongr;
              refine' le_add_of_nonneg_right _;
              exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun _ _ => hf_nonneg x ) _;
            · exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun _ _ => hf_nonneg x ) _;
            · split_ifs <;> norm_num [ bin_masses ];
              exact MeasureTheory.integral_nonneg fun x => by rw [ Set.indicator_apply ] ; aesop;
            · split_ifs <;> norm_num [ bin_masses ];
              exact MeasureTheory.integral_nonneg fun x => by rw [ Set.indicator_apply ] ; aesop;
          · convert sum_bin_masses_eq_one n hn f hf_supp hf_int using 1;
        · rw [ Finset.sum_eq_single ⟨ i, by linarith [ Finset.mem_range.mp hi ] ⟩ ] <;> aesop;
      · rw [ ← Finset.sum_add_distrib ] ; congr ; ext j ; split_ifs <;> first | linarith | omega;
  -- Therefore, $\sum_{i=0}^{k-1} \delta_i = D_k / m - M_k$.
  have h_sum_delta : ∑ i : Fin k, delta f n m (Fin.castLE hk i) = (D_k : ℝ) / m - M_k := by
    convert congr_arg ( fun x : ℝ => x / m - ∑ i : Fin k, bin_masses f n ( Fin.castLE hk i ) ) h_Dk using 1 ; norm_num [ Finset.sum_div _ _ _ ] ; ring!;
    exact?;
  -- Since $D_k = \lfloor M_k \cdot m \rfloor$, we have $D_k \leq M_k \cdot m < D_k + 1$.
  have h_floor : (D_k : ℝ) ≤ M_k * m ∧ M_k * m < (D_k : ℝ) + 1 := by
    simp +zetaDelta at *;
    rw [ abs_of_nonneg ( Int.cast_nonneg.mpr ( Int.floor_nonneg.mpr ( mul_nonneg ( Finset.sum_nonneg fun _ _ => ?_ ) ( Nat.cast_nonneg _ ) ) ) ) ] ; exact ⟨ Int.floor_le _, Int.lt_floor_add_one _ ⟩ ;
    exact MeasureTheory.integral_nonneg fun x => by rw [ Set.indicator_apply ] ; aesop;
  exact abs_le.mpr ⟨ by nlinarith [ show ( m : ℝ ) > 0 by positivity, div_mul_cancel₀ ( D_k : ℝ ) ( by positivity : ( m : ℝ ) ≠ 0 ), div_mul_cancel₀ ( 1 : ℝ ) ( by positivity : ( m : ℝ ) ≠ 0 ) ], by nlinarith [ show ( m : ℝ ) > 0 by positivity, div_mul_cancel₀ ( D_k : ℝ ) ( by positivity : ( m : ℝ ) ≠ 0 ), div_mul_cancel₀ ( 1 : ℝ ) ( by positivity : ( m : ℝ ) ≠ 0 ) ] ⟩

/-
The partial sum of the canonical discretization equals the discrete cumulative mass.
-/
lemma sum_canonical_discretization_eq (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (k : ℕ) (hk : k ≤ 2 * n) :
    ∑ i : Fin k, canonical_discretization f n m (Fin.castLE hk i) = discrete_cum_mass f n m k := by
  unfold canonical_discretization discrete_cum_mass;
  unfold target_cum_mass; induction' k with k ih <;> norm_num [ Fin.sum_univ_castSucc ] at *;
  split_ifs;
  · rw [ ih ( by linarith ), add_tsub_cancel_of_le ];
    rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr ?_ ), Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr ?_ ) ] <;> norm_num [ Finset.sum_ite ];
    · gcongr;
      · exact Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun _ => Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
      · exact fun _ _ _ => MeasureTheory.integral_nonneg fun _ => Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
      · exact fun x hx => Nat.lt_succ_of_lt hx;
    · refine' mul_nonneg ( div_nonneg _ _ ) ( Nat.cast_nonneg _ );
      · refine' Finset.sum_nonneg fun _ _ => _;
        exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun _ _ => hf_nonneg x ) _;
      · exact Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun _ => Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
    · refine' mul_nonneg ( div_nonneg _ _ ) ( Nat.cast_nonneg _ );
      · refine' Finset.sum_nonneg fun _ _ => _;
        exact MeasureTheory.integral_nonneg fun _ => Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
      · exact Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun _ => Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
  · rw [ ih ( by linarith ) ];
    rw [ add_tsub_cancel_of_le ];
    · rw [ show ( ∑ j : Fin ( 2 * n ), if ( j : ℕ ) < k + 1 then bin_masses f n j else 0 ) = ∑ j : Fin ( 2 * n ), bin_masses f n j from ?_ ];
      · rw [ sum_bin_masses_eq_one ] <;> norm_num [ hn, hm ];
        · exact hf_supp;
        · exact hf_int;
      · exact Finset.sum_congr rfl fun x hx => if_pos <| by linarith [ Fin.is_lt x ] ;
    · rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr _ ) ];
      · refine' Int.le_of_lt_add_one ( Int.floor_lt.mpr _ );
        rw [ div_mul_eq_mul_div, div_lt_iff₀ ] <;> norm_cast;
        · norm_num [ Finset.sum_ite ];
          rw [ add_mul, one_mul, mul_comm ];
          refine' lt_add_of_le_of_pos ( mul_le_mul_of_nonneg_left ( Finset.sum_le_sum_of_subset_of_nonneg ( Finset.filter_subset _ _ ) fun _ _ _ => _ ) ( Nat.cast_nonneg _ ) ) ( _ );
          · exact MeasureTheory.integral_nonneg fun x => Set.indicator_nonneg ( fun _ _ => hf_nonneg x ) _;
          · rw [ sum_bin_masses_eq_one ] <;> norm_num [ hn, hm ];
            · exact hf_supp;
            · exact hf_int;
        · rw [ sum_bin_masses_eq_one ] <;> norm_num [ hn, hm ];
          · exact hf_supp;
          · exact hf_int;
      · refine' mul_nonneg ( div_nonneg _ _ ) ( Nat.cast_nonneg _ );
        · refine' Finset.sum_nonneg fun _ _ => _;
          split_ifs <;> norm_num [ bin_masses ];
          exact MeasureTheory.integral_nonneg fun x => by rw [ Set.indicator_apply ] ; split_ifs <;> norm_num ; exact hf_nonneg x;
        · exact Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun _ => Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _

/-
Summation by parts bound (Abel's inequality variant).
-/
lemma sum_mul_bound_succ {n : ℕ} (a b : Fin (n + 1) → ℝ) (A V : ℝ)
    (ha : ∀ k : Fin (n + 1), |∑ i : Fin (n + 1), if i ≤ k then a i else 0| ≤ A)
    (hb : ∑ i : Fin n, |b (Fin.castSucc i) - b (Fin.succ i)| ≤ V)
    (hb_last : |b (Fin.last n)| ≤ V) :
    |∑ i : Fin (n + 1), a i * b i| ≤ A * (V + V) := by
  -- Applying the summation by parts formula, we have
  have h_sum_parts : ∑ i, (a i * b i) = ∑ i : Fin n, (∑ j ∈ Finset.univ.filter (fun j => j ≤ Fin.castSucc i), a j) * (b (Fin.castSucc i) - b (Fin.succ i)) + (∑ j ∈ Finset.univ.filter (fun j => j ≤ Fin.last n), a j) * b (Fin.last n) := by
    clear ha hb hb_last;
    induction' n with n ih;
    · simp +decide [ Fin.eq_zero ];
    · specialize ih ( fun i => a i.castSucc ) ( fun i => b i.castSucc ) ; simp_all +decide [ Fin.sum_univ_castSucc, Finset.sum_filter ] ; ring;
      simp +decide [ Fin.le_last, Finset.sum_ite ] ; ring!;
  -- Applying the triangle inequality to the sum, we get
  have h_triangle : |∑ i : Fin n, (∑ j ∈ Finset.univ.filter (fun j => j ≤ Fin.castSucc i), a j) * (b (Fin.castSucc i) - b (Fin.succ i))| ≤ A * (∑ i : Fin n, |b (Fin.castSucc i) - b (Fin.succ i)|) := by
    rw [ Finset.mul_sum _ _ _ ];
    refine' le_trans ( Finset.abs_sum_le_sum_abs _ _ ) ( Finset.sum_le_sum fun i _ => _ );
    simpa only [ abs_mul, Finset.sum_filter ] using mul_le_mul_of_nonneg_right ( ha _ ) ( abs_nonneg _ );
  rw [ h_sum_parts, abs_le ] at *;
  have := ha ( Fin.last n );
  norm_num [ Fin.le_last ] at * ; constructor <;> nlinarith [ abs_le.mp this ]

/-
The sum of the discretization error over any range is bounded by $1/m$.
-/
lemma sum_delta_bound_range (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (a b : ℕ) (h_le : a ≤ b) (hb : b ≤ 2 * n) :
    |∑ i ∈ (Finset.Ico a b).attach, delta f n m ⟨i.1, lt_of_lt_of_le (Finset.mem_Ico.mp i.2).2 hb⟩| ≤ 1 / m := by
  -- The sum over `Ico a b` is the difference of partial sums: $S_b - S_a$ by definition of `delta`.
  have h_diff_partial_sums : ∑ i ∈ Finset.attach (Finset.Ico a b), delta f n m ⟨i.val, by linarith [Finset.mem_Ico.mp i.2]⟩ = ∑ i : Fin b, delta f n m ⟨i, by linarith [Fin.is_lt i]⟩ - ∑ i : Fin a, delta f n m ⟨i, by linarith [Fin.is_lt i]⟩ := by
    rw [ eq_sub_iff_add_eq', ← Finset.sum_sdiff ( Finset.subset_univ ( Finset.image ( fun i : Fin a => ⟨ i, by linarith [ Fin.is_lt i ] ⟩ : Fin a → Fin b ) Finset.univ ) ) ];
    rw [ add_comm, Finset.sum_image ];
    · refine' congrArg₂ ( · + · ) _ _;
      · refine' Finset.sum_bij ( fun x hx => ⟨ x, by linarith [ Finset.mem_Ico.mp x.2 ] ⟩ ) _ _ _ _ <;> simp +decide;
        · exact fun x hx₁ hx₂ y hy => by linarith [ Fin.is_lt y ] ;
        · exact fun x hx => ⟨ x, ⟨ not_lt.mp fun contra => hx ⟨ x, contra ⟩ rfl, x.2 ⟩, rfl ⟩;
      · rfl;
    · exact fun i _ j _ hij => Fin.ext <| by simpa using congr_arg Fin.val hij;
  -- By the properties of the partial sums and the bound on the discretization error, we can conclude that the absolute value of the difference is bounded by $1/m$.
  have h_abs_diff_partial_sums : |∑ i : Fin b, delta f n m ⟨i, by linarith [Fin.is_lt i]⟩| ≤ 1 / m ∧ |∑ i : Fin a, delta f n m ⟨i, by linarith [Fin.is_lt i]⟩| ≤ 1 / m := by
    exact ⟨ by simpa using partial_sum_delta_bound n m hn hm f hf_nonneg hf_supp hf_int b hb, by simpa using partial_sum_delta_bound n m hn hm f hf_nonneg hf_supp hf_int a ( by linarith ) ⟩;
  rw [ h_diff_partial_sums, abs_le ] at *;
  -- By combining the inequalities from h_abs_diff_partial_sums, we can conclude the proof.
  apply And.intro;
  · have h_partial_sum_nonpos : ∑ i : Fin a, delta f n m ⟨i, by linarith [Fin.is_lt i]⟩ ≤ 0 := by
      have h_partial_sum_nonpos : ∑ i : Fin a, delta f n m ⟨i, by linarith [Fin.is_lt i]⟩ = (discrete_cum_mass f n m a : ℝ) / m - ∑ i : Fin a, bin_masses f n ⟨i, by linarith [Fin.is_lt i]⟩ := by
        have h_partial_sum_nonpos : ∑ i : Fin a, delta f n m ⟨i, by linarith [Fin.is_lt i]⟩ = (∑ i : Fin a, canonical_discretization f n m ⟨i, by linarith [Fin.is_lt i]⟩ : ℝ) / m - ∑ i : Fin a, bin_masses f n ⟨i, by linarith [Fin.is_lt i]⟩ := by
          unfold delta; simp +decide [ Finset.sum_div _ _ _ ] ;
        rw [ h_partial_sum_nonpos, ← sum_canonical_discretization_eq ];
        all_goals norm_cast;
        · exact hf_supp.trans ( by norm_num [ Rat.divInt_eq_div ] );
        · linarith;
      rw [ h_partial_sum_nonpos, div_sub', div_le_iff₀ ] <;> norm_cast;
      · norm_num [ discrete_cum_mass ];
        rw [ abs_of_nonneg ( Int.cast_nonneg.mpr ( Int.floor_nonneg.mpr _ ) ) ];
        · refine' le_trans ( Int.floor_le _ ) _;
          unfold target_cum_mass;
          rw [ mul_comm ];
          rw [ show ( ∑ j : Fin ( 2 * n ), if ( j : ℕ ) < a then bin_masses f n j else 0 ) = ∑ j : Fin a, bin_masses f n ⟨ j, by linarith [ Fin.is_lt j ] ⟩ from ?_ ];
          · rw [ sum_bin_masses_eq_one n hn f hf_supp hf_int ] ; norm_num;
          · rw [ ← Finset.sum_filter ];
            refine' Finset.sum_bij ( fun x hx => ⟨ x, by linarith [ Finset.mem_filter.mp hx, Fin.is_lt x ] ⟩ ) _ _ _ _ <;> simp +decide;
            · exact fun i hi j hj hij => Fin.ext hij;
            · exact fun i => ⟨ ⟨ i, by linarith [ Fin.is_lt i ] ⟩, by simp, rfl ⟩;
        · refine' mul_nonneg ( div_nonneg _ _ ) _ <;> norm_num;
          · refine' Finset.sum_nonneg fun i _ => _;
            split_ifs <;> norm_num [ bin_masses ];
            exact MeasureTheory.integral_nonneg fun x => by rw [ Set.indicator_apply ] ; aesop;
          · exact Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun _ => Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
      · linarith;
    linarith [ abs_le.mp h_abs_diff_partial_sums.2 ];
  · have h_sum_delta_nonpos : ∀ k : Fin (2 * n + 1), ∑ i : Fin k, delta f n m (Fin.castLE (by linarith [Fin.is_lt k]) i) ≤ 0 := by
      intro k
      have h_sum_delta_nonpos : ∑ i : Fin k, delta f n m (Fin.castLE (by linarith [Fin.is_lt k]) i) = (discrete_cum_mass f n m k : ℝ) / m - ∑ i : Fin k, bin_masses f n (Fin.castLE (by linarith [Fin.is_lt k]) i) := by
        have h_sum_delta_nonpos : ∑ i : Fin k, delta f n m (Fin.castLE (by linarith [Fin.is_lt k]) i) = (∑ i : Fin k, (canonical_discretization f n m (Fin.castLE (by linarith [Fin.is_lt k]) i) : ℝ)) / m - ∑ i : Fin k, bin_masses f n (Fin.castLE (by linarith [Fin.is_lt k]) i) := by
          simp +decide [ delta, Finset.sum_div _ _ _ ];
        convert h_sum_delta_nonpos using 2;
        rw_mod_cast [ sum_canonical_discretization_eq ];
        · linarith;
        · linarith;
        · assumption;
        · convert hf_supp using 1 ; norm_num [ Rat.divInt_eq_div ];
        · exact hf_int;
      have h_sum_bin_masses : ∑ i : Fin k, bin_masses f n (Fin.castLE (by linarith [Fin.is_lt k]) i) = (target_cum_mass f n m k : ℝ) / m := by
        unfold target_cum_mass;
        field_simp;
        rw [ show ( ∑ j : Fin ( 2 * n ), if ( j : ℕ ) < k then bin_masses f n j else 0 ) = ∑ i : Fin k, bin_masses f n ( Fin.castLE ( by linarith [ Fin.is_lt k ] ) i ) from ?_, show ( ∑ j : Fin ( 2 * n ), bin_masses f n j ) = 1 from ?_ ];
        · ring;
        · exact?;
        · rw [ ← Finset.sum_filter ];
          refine' Finset.sum_bij ( fun i hi => ⟨ i, by linarith [ Fin.is_lt i, Fin.is_lt k, Finset.mem_filter.mp hi ] ⟩ ) _ _ _ _ <;> simp +decide [ Fin.ext_iff ];
          exact fun i => ⟨ ⟨ i, by linarith [ Fin.is_lt i, Fin.is_lt k ] ⟩, by simp, rfl ⟩;
      rw [ h_sum_delta_nonpos, h_sum_bin_masses ];
      rw [ sub_nonpos, div_le_div_iff_of_pos_right ] <;> norm_cast;
      unfold discrete_cum_mass; norm_num;
      rw [ abs_of_nonneg ( Int.cast_nonneg.mpr ( Int.floor_nonneg.mpr ( show 0 ≤ target_cum_mass f n m k from _ ) ) ) ] ; exact Int.floor_le _;
      refine' mul_nonneg ( div_nonneg _ _ ) _ <;> norm_num;
      · refine' Finset.sum_nonneg fun i _ => _ ; split_ifs <;> norm_num [ bin_masses ];
        exact MeasureTheory.integral_nonneg fun x => by rw [ Set.indicator_apply ] ; aesop;
      · exact Finset.sum_nonneg fun _ _ => MeasureTheory.integral_nonneg fun _ => Set.indicator_nonneg ( fun _ _ => hf_nonneg _ ) _;
    linarith! [ abs_le.mp h_abs_diff_partial_sums.2, h_sum_delta_nonpos ⟨ b, by linarith ⟩, h_sum_delta_nonpos ⟨ a, by linarith ⟩ ]

/-
The sum of absolute discretization errors is bounded by $2n/m$.
-/
lemma sum_abs_delta_le (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1) :
    ∑ i : Fin (2 * n), |delta f n m i| ≤ (2 * n : ℝ) / m := by
  -- Apply the bound on the absolute value of the discretization error to each term in the sum.
  have h_sum_bound : ∑ i : Fin (2 * n), |delta f n m i| ≤ ∑ i : Fin (2 * n), (1 / m : ℝ) := by
    exact Finset.sum_le_sum fun i _ => by simpa using discretization_error_bound n m hn hm f hf_nonneg hf_supp hf_int i;
  simpa [ div_eq_mul_inv ] using h_sum_bound

/-
The maximum test value is attained at some parameters.
-/
lemma max_test_value_le_max (n m : ℕ) (hn : n > 0) (c : Fin (2 * n) → ℕ) :
    ∃ ℓ s_lo, ℓ ∈ Finset.Icc 2 (2 * (2 * n)) ∧ s_lo ∈ Finset.range (2 * (2 * n)) ∧
    max_test_value n m c = test_value n m c ℓ s_lo := by
  unfold max_test_value;
  simp +zetaDelta at *;
  split_ifs with h;
  · have := Finset.max'_mem ( Finset.biUnion ( Finset.Icc 2 ( 2 * ( 2 * n ) ) ) fun ℓ => Finset.image ( fun s_lo => test_value n m c ℓ s_lo ) ( Finset.range ( 2 * ( 2 * n ) ) ) ) ; aesop;
  · exact False.elim <| h ⟨ ⟨ 2, by norm_num, by linarith ⟩, hn.ne' ⟩

/-
The first error term in the decomposition of the test value difference.
-/
noncomputable def error_term_1 (n m : ℕ) (f : ℝ → ℝ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let w := fun i => (canonical_discretization f n m i : ℝ) / m
  let mu := bin_masses f n
  let delta := fun i => w i - mu i
  (4 * n / ℓ) * ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2),
    ∑ i : Fin d,
      if h : i.1 ≤ k ∧ k - i.1 < d then
        delta i * mu ⟨k - i.1, h.2⟩
      else 0

/-
The second error term in the decomposition of the test value difference.
-/
noncomputable def error_term_2 (n m : ℕ) (f : ℝ → ℝ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let w := fun i => (canonical_discretization f n m i : ℝ) / m
  let mu := bin_masses f n
  let delta := fun i => w i - mu i
  (4 * n / ℓ) * ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2),
    ∑ i : Fin d,
      if h : i.1 ≤ k ∧ k - i.1 < d then
        mu i * delta ⟨k - i.1, h.2⟩
      else 0

/-
The third error term in the decomposition of the test value difference.
-/
noncomputable def error_term_3 (n m : ℕ) (f : ℝ → ℝ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let w := fun i => (canonical_discretization f n m i : ℝ) / m
  let mu := bin_masses f n
  let delta := fun i => w i - mu i
  (4 * n / ℓ) * ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2),
    ∑ i : Fin d,
      if h : i.1 ≤ k ∧ k - i.1 < d then
        delta i * delta ⟨k - i.1, h.2⟩
      else 0

/-
The mass of the function f in a window of length ℓ shifted by i.
-/
noncomputable def window_mass (n : ℕ) (f : ℝ → ℝ) (ℓ s_lo : ℕ) (i : Fin (2 * n)) : ℝ :=
  ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2),
    if h : i.1 ≤ k ∧ k - i.1 < 2 * n then
      bin_masses f n ⟨k - i.1, h.2⟩
    else 0

/-
Extended bin masses function that returns 0 for out-of-bounds indices.
-/
noncomputable def extended_bin_masses (n : ℕ) (f : ℝ → ℝ) (k : ℤ) : ℝ :=
  if h : 0 ≤ k ∧ k < 2 * n then bin_masses f n ⟨k.natAbs, by
    linarith [ abs_of_nonneg h.1 ]⟩ else 0