/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f55017a5-3a9a-47fb-9e62-4b6a01773a74

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  let norm_inf := (MeasureTheory.eLpNorm conv ⊤ MeasureTheory.volume).toReal
  let integral := MeasureTheory.integral MeasureTheory.volume f
  norm_inf / (integral ^ 2)

noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

noncomputable def f_restricted (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) : ℝ → ℝ :=
  let δ := 1 / (4 * n : ℝ)
  let a := -(1/4 : ℝ) + i * δ
  let b := -(1/4 : ℝ) + (i + 1) * δ
  Set.indicator (Set.Ico a b) f

theorem bin_masses_nonneg (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n : ℕ) (i : Fin (2 * n)) :
    0 ≤ bin_masses f n i := by
      apply_rules [ MeasureTheory.integral_nonneg, Set.indicator_nonneg ] ; aesop

theorem f_restricted_integral (n : ℕ) (f : ℝ → ℝ) (i : Fin (2 * n)) :
    MeasureTheory.integral MeasureTheory.volume (f_restricted f n i) = bin_masses f n i := by
  unfold f_restricted bin_masses
  rfl

theorem f_ge_f_restricted (n : ℕ) (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x) (i : Fin (2 * n)) :
    ∀ x, f x ≥ f_restricted f n i x ∧ f_restricted f n i x ≥ 0 := by
      intros x
      simp [f_restricted];
      simp [Set.indicator] at *; aesop;

theorem convolution_comm_real (f g : ℝ → ℝ) :
    MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume =
    MeasureTheory.convolution g f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume := by
      ext x;
      have h_subst : ∀ {f g : ℝ → ℝ}, (∫ t, f t * g (x - t)) = (∫ t, g t * f (x - t)) := by
        intro f g; rw [ ← MeasureTheory.integral_sub_left_eq_self ] ; congr; ext; ring;
      exact h_subst

theorem f_has_compact_support (f : ℝ → ℝ) (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4)) :
    HasCompactSupport f := by
      have h_closure : closure (Function.support f) ⊆ Set.Icc (-1 / 4 : ℝ) (1 / 4) := by
        have h_closure_subset : closure (Function.support f) ⊆ closure (Set.Ioo (-1 / 4 : ℝ) (1 / 4)) := by
          apply closure_mono hf_supp;
        exact h_closure_subset.trans ( by rw [ closure_Ioo ( by norm_num ) ] );
      exact CompactIccSpace.isCompact_Icc.of_isClosed_subset ( isClosed_closure ) h_closure

theorem f_restricted_integrable (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n))
    (h_int : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.Integrable (f_restricted f n i) MeasureTheory.volume := by
  unfold f_restricted
  apply MeasureTheory.Integrable.indicator h_int measurableSet_Ico

/-
For nonneg integrable f, g with compact support: ∫(f∗g) = (∫f)·(∫g)
-/
theorem convolution_integral_eq (f g : ℝ → ℝ)
    (hf_nonneg : ∀ x, 0 ≤ f x) (hg_nonneg : ∀ x, 0 ≤ g x)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    MeasureTheory.integral MeasureTheory.volume
      (MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) =
    MeasureTheory.integral MeasureTheory.volume f *
    MeasureTheory.integral MeasureTheory.volume g := by
  -- Apply the convolution theorem, which states that the integral of the convolution of two functions is the product of their integrals.
  have h_convolution_theorem : ∀ {f g : ℝ → ℝ}, MeasureTheory.Integrable f MeasureTheory.volume → MeasureTheory.Integrable g MeasureTheory.volume → MeasureTheory.integral MeasureTheory.volume (MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) = (MeasureTheory.integral MeasureTheory.volume f) * (MeasureTheory.integral MeasureTheory.volume g) := by
    intro f g hf hg; exact (by
    rw [ MeasureTheory.integral_convolution ] ; aesop;
    · exact hf;
    · exact hg);
  exact h_convolution_theorem hf_int hg_int

/-
Convolution of nonneg functions is nonneg.
-/
theorem convolution_nonneg (f g : ℝ → ℝ)
    (hf : ∀ x, 0 ≤ f x) (hg : ∀ x, 0 ≤ g x) :
    ∀ x, 0 ≤ MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  intro x
  unfold MeasureTheory.convolution
  simp [hf, hg];
  exact MeasureTheory.integral_nonneg fun t => mul_nonneg ( hf t ) ( hg ( x - t ) )

/-
If supp(f) ⊆ (-1/4, 0), then supp(f∗f) ⊆ (-1/2, 0).
-/
theorem convolution_support_subset (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) 0) :
    Function.support (MeasureTheory.convolution f f
      (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆
    Set.Ioo (-1/2 : ℝ) 0 := by
  intro x hx; have := hf_supp; simp_all +decide [ MeasureTheory.convolution ] ; (
  -- Since $\int t, f t * f (x - t) \neq 0$, there exists some $t$ such that $f t * f (x - t) \neq 0$.
  obtain ⟨t, ht⟩ : ∃ t, f t * f (x - t) ≠ 0 := by
    exact not_forall.mp fun h => hx <| MeasureTheory.integral_eq_zero_of_ae <| Filter.Eventually.of_forall h;
  constructor <;> nlinarith [ this t ( by aesop ), this ( x - t ) ( by aesop ) ] ;)

/-
Averaging principle: ‖g‖∞ ≥ (∫g) / measure(support).
-/
theorem averaging_principle (g : ℝ → ℝ) (m : ℝ) (hg_nonneg : ∀ x, 0 ≤ g x)
    (S : Set ℝ) (hS : Function.support g ⊆ S)
    (hS_meas : MeasureTheory.volume S = ENNReal.ofReal m)
    (hm : 0 < m)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume)
    (hg_bdd : MeasureTheory.MemLp g ⊤ MeasureTheory.volume) :
    (MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume).toReal ≥
      MeasureTheory.integral MeasureTheory.volume g / m := by
  -- Since $g$ is nonnegative and integrable, the integral of $g$ over its support is less than or equal to the essential supremum of $g$ times the measure of the support.
  have h_integral_le_sup : (∫ x in {x | g x ≠ 0}, g x) ≤ (MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume).toReal * (MeasureTheory.MeasureSpace.volume {x | g x ≠ 0}).toReal := by
    have h_integral_le_ess_sup : ∀ᵐ x ∂MeasureTheory.Measure.restrict MeasureTheory.volume {x | g x ≠ 0}, g x ≤ (MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume).toReal := by
      have h_int_le_sup : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, g x ≤ (MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume).toReal := by
        have := hg_bdd.2;
        have h_le_essSup : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, ‖g x‖ₑ ≤ essSup (fun x => ‖g x‖ₑ) (MeasureTheory.MeasureSpace.volume) := by
          exact?;
        filter_upwards [ h_le_essSup ] with x hx;
        convert ENNReal.toReal_mono _ hx using 1 <;> norm_num [ hg_nonneg ];
        · rw [ abs_of_nonneg ( hg_nonneg x ) ];
        · exact?;
      exact MeasureTheory.ae_restrict_of_ae h_int_le_sup;
    convert MeasureTheory.integral_mono_ae _ _ h_integral_le_ess_sup using 1 <;> norm_num [ mul_comm ];
    · exact Or.inl rfl;
    · exact hg_int.integrableOn;
    · have h_measure_finite : MeasureTheory.MeasureSpace.volume {x | g x ≠ 0} < ⊤ := by
        exact lt_of_le_of_lt ( MeasureTheory.measure_mono hS ) ( hS_meas.symm ▸ ENNReal.ofReal_lt_top )
      generalize_proofs at *; (
      apply_rules [ MeasureTheory.integrable_const ];
      constructor ; aesop);
  rw [ ge_iff_le, div_le_iff₀ hm ];
  convert h_integral_le_sup.trans _ using 1;
  · rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero ] ; aesop;
  · gcongr;
    exact ENNReal.toReal_le_of_le_ofReal hm.le ( by exact le_trans ( MeasureTheory.measure_mono hS ) hS_meas.le )

/-
Pointwise inequality for convolution integrand.
-/
theorem convolution_pointwise_le (f g : ℝ → ℝ) (x : ℝ)
    (hf : ∀ x, 0 ≤ f x) (hg : ∀ x, 0 ≤ g x) (hfg : ∀ x, f x ≤ g x) :
    ∀ t, f t * f (x - t) ≤ g t * g (x - t) := by
  exact fun t => mul_le_mul ( hfg t ) ( hfg ( x - t ) ) ( hf _ ) ( hg _ )

/-
Convolution monotonicity almost everywhere for nonneg integrable functions.
-/
theorem convolution_mono_ae (f g : ℝ → ℝ)
    (hf : ∀ x, 0 ≤ f x) (hg : ∀ x, 0 ≤ g x) (hfg : ∀ x, f x ≤ g x)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤
         MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  have h_conv_integrable : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, MeasureTheory.Integrable (fun t => g t * g (x - t)) MeasureTheory.MeasureSpace.volume := by
    have := hg_int
    have h_conv_integrable : MeasureTheory.Integrable (fun (x : ℝ × ℝ) => g x.1 * g x.2) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
      exact this.prod_mul this;
    have h_conv_integrable : MeasureTheory.Integrable (fun (x : ℝ × ℝ) => g x.1 * g (x.2 - x.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
      have h_measure_preserving : MeasureTheory.MeasurePreserving (fun (x : ℝ × ℝ) => (x.1, x.2 - x.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
        exact?
      have h_conv_integrable : MeasureTheory.Integrable (fun (x : ℝ × ℝ) => g x.1 * g x.2) (MeasureTheory.Measure.map (fun (x : ℝ × ℝ) => (x.1, x.2 - x.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume)) := by
        rw [ h_measure_preserving.map_eq ] ; exact h_conv_integrable;
      convert h_conv_integrable.comp_measurable ( measurable_fst.prodMk ( measurable_snd.sub measurable_fst ) ) using 1;
    rw [ MeasureTheory.integrable_prod_iff' ] at h_conv_integrable ; aesop;
    exact h_conv_integrable.1;
  filter_upwards [ h_conv_integrable ] with x hx;
  refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
  · exact Filter.Eventually.of_forall fun t => mul_nonneg ( hf t ) ( hf ( x - t ) );
  · exact hx;
  · filter_upwards [ ] with t using mul_le_mul ( hfg t ) ( hfg ( x - t ) ) ( hf _ ) ( hg _ )

/-
Averaging principle in ENNReal.
-/
theorem averaging_principle_ennreal (g : ℝ → ℝ) (m : ℝ) (hg_nonneg : ∀ x, 0 ≤ g x)
    (S : Set ℝ) (hS : Function.support g ⊆ S)
    (hS_meas : MeasureTheory.volume S = ENNReal.ofReal m)
    (hm : 0 < m)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume ≥
    ENNReal.ofReal (MeasureTheory.integral MeasureTheory.volume g / m) := by
  by_cases h : MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume = ⊤;
  · aesop;
  · convert averaging_principle g m hg_nonneg S hS hS_meas hm hg_int _;
    · rw [ ge_iff_le, ge_iff_le, ENNReal.ofReal_le_iff_le_toReal ] ; aesop;
    · constructor;
      · exact hg_int.1;
      · exact lt_top_iff_ne_top.mpr h

/-
Monotonicity of convolution essential sup norm (ENNReal). Corrected direction.
-/
theorem convolution_norm_mono_ennreal (f g : ℝ → ℝ)
    (hf : ∀ x, 0 ≤ f x) (hg : ∀ x, 0 ≤ g x) (hfg : ∀ x, f x ≤ g x)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≤
    MeasureTheory.eLpNorm (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume := by
  -- By convolution_mono_ae, we have (f*f)(x) ≤ (g*g)(x) almost everywhere.
  have h_conv_mono : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤ MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
    exact?;
  apply_rules [ essSup_mono_ae ];
  filter_upwards [ h_conv_mono ] with x hx using by rw [ Real.enorm_eq_ofReal ( convolution_nonneg f f hf hf x ), Real.enorm_eq_ofReal ( convolution_nonneg g g hg hg x ) ] ; exact ENNReal.ofReal_le_ofReal hx;

/-
Bound for convolution of function supported on left half.
-/
theorem convolution_bound_of_support_subset (g : ℝ → ℝ)
    (hg_nonneg : ∀ x, 0 ≤ g x)
    (hg_supp : Function.support g ⊆ Set.Ioo (-1/4 : ℝ) 0)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    MeasureTheory.eLpNorm (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≥
    ENNReal.ofReal (2 * (MeasureTheory.integral MeasureTheory.volume g) ^ 2) := by
  convert averaging_principle_ennreal ( MeasureTheory.convolution g g ( ContinuousLinearMap.mul ℝ ℝ ) MeasureTheory.MeasureSpace.volume ) ( 1 / 2 ) _ _ _ using 1 <;> norm_num;
  any_goals exact Set.Ioo ( -1 / 2 ) 0;
  · rw [ convolution_integral_eq ] <;> norm_num;
    · by_cases h : MeasureTheory.Integrable ( MeasureTheory.convolution g g ( ContinuousLinearMap.mul ℝ ℝ ) MeasureTheory.MeasureSpace.volume ) MeasureTheory.MeasureSpace.volume <;> simp_all +decide [ sq, mul_assoc ];
      · rw [ ← mul_assoc, ENNReal.ofReal_mul ( mul_nonneg ( MeasureTheory.integral_nonneg hg_nonneg ) ( MeasureTheory.integral_nonneg hg_nonneg ) ) ] ; ring_nf ; norm_num;
      · contrapose! h;
        exact?;
    · assumption;
    · assumption;
    · exact hg_int;
    · exact hg_int;
  · exact?;
  · intro x hx; have := convolution_support_subset g hg_supp; aesop;

/-
Asymmetry bound (ENNReal).
-/
theorem asymmetry_bound_ennreal (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Icc (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1) :
    let L := MeasureTheory.integral MeasureTheory.volume
               (Set.indicator (Set.Ioo (-1/4 : ℝ) 0) f)
    MeasureTheory.eLpNorm
      (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume)
      ⊤ MeasureTheory.volume ≥ ENNReal.ofReal (2 * L ^ 2) := by
  let f_L := Set.indicator (Set.Ioo (-1/4 : ℝ) 0) f
  have hf_integrable : MeasureTheory.Integrable f MeasureTheory.volume := MeasureTheory.integrable_of_integral_eq_one hf_int
  have hf_L_nonneg : ∀ x, 0 ≤ f_L x := fun x => Set.indicator_nonneg (fun _ _ => hf_nonneg _) _
  have hf_L_le_f : ∀ x, f_L x ≤ f x := fun x => Set.indicator_le_self' (fun _ _ => hf_nonneg _) _
  have hf_L_supp : Function.support f_L ⊆ Set.Ioo (-1/4 : ℝ) 0 := Set.support_indicator_subset
  have hf_L_integrable : MeasureTheory.Integrable f_L MeasureTheory.volume := hf_integrable.indicator measurableSet_Ioo

  have h_mono := convolution_norm_mono_ennreal f_L f hf_L_nonneg hf_nonneg hf_L_le_f hf_L_integrable hf_integrable
  have h_bound := convolution_bound_of_support_subset f_L hf_L_nonneg hf_L_supp hf_L_integrable
  exact le_trans h_bound h_mono