/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b6236cec-754a-46d3-9481-bb7ca8597d04

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes Claims 4.5, 4.7, and 4.8 from the problem context.

Claim 4.5 (`single_bin_bound`) establishes a lower bound on the L-infinity norm of the autoconvolution of a function restricted to a single bin, using the Cauchy-Schwarz inequality and the averaging principle. It shows that $\|f*f\|_\infty \ge d \cdot M_i^2$.

Claim 4.7 (`exists_invariant_under_permutation`) proves that the existential quantifier over a finite set is invariant under permutation, which is relevant for the Ell scan order.

Claim 4.8 (`conv_entry_le_total`, `conv_total`, `int32_safe`) provides bounds and equalities for discrete autoconvolution sums to ensure integer overflow safety. Specifically, it proves that each entry in the convolution is bounded by the square of the total sum, the sum of all entries equals the square of the total sum, and that for $m \le 200$, $m^2$ fits within a 32-bit signed integer.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise



noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

noncomputable def bin_interval (n : ℕ) (i : Fin (2 * n)) : Set ℝ :=
  let δ := 1 / (4 * n : ℝ)
  let a := -(1/4 : ℝ) + i * δ
  let b := -(1/4 : ℝ) + (i + 1) * δ
  Set.Ico a b

noncomputable def f_bin (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) : ℝ → ℝ :=
  Set.indicator (bin_interval n i) f

lemma f_bin_le_f (f : ℝ → ℝ) (hf : 0 ≤ f) (n : ℕ) (i : Fin (2 * n)) :
  f_bin f n i ≤ f := by
    -- By definition of $f_bin$, we know that $f_bin f n i x = f x$ if $x \in \text{bin\_interval } n i$ and $f_bin f n i x = 0$ otherwise.
    have h_f_bin_def : ∀ x, f_bin f n i x = if x ∈ bin_interval n i then f x else 0 := by
      -- By definition of $f_bin$, we know that $f_bin f n i x = \text{indicator}(bin_interval n i, f) x$.
      simp [f_bin, Set.indicator];
    -- By definition of $f_bin$, we know that $f_bin f n i x = f x$ if $x \in \text{bin\_interval } n i$ and $f_bin f n i x = 0$ otherwise. Since $f$ is non-negative, $0 \leq f x$ for all $x$.
    intros x
    simp [h_f_bin_def];
    -- Since $f$ is non-negative, $f x \geq 0$ for all $x$. Therefore, the if statement is always less than or equal to $f x$.
    aesop

lemma f_bin_nonneg (f : ℝ → ℝ) (hf : 0 ≤ f) (n : ℕ) (i : Fin (2 * n)) :
  0 ≤ f_bin f n i := by
    -- The product of two non-negative functions is non-negative.
    apply Set.indicator_nonneg; intro x hx; exact hf x

lemma integral_f_bin (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) :
  MeasureTheory.integral MeasureTheory.volume (f_bin f n i) = bin_masses f n i := by
    -- By definition of $f_bin$, we know that its integral over the entire real line is equal to the integral of $f$ over the bin interval $bin_interval n i$. This follows from the fact that the indicator function is 1 on the bin interval and 0 elsewhere.
    have h_integral : MeasureTheory.integral MeasureTheory.MeasureSpace.volume (f_bin f n i) = MeasureTheory.integral MeasureTheory.MeasureSpace.volume (Set.indicator (bin_interval n i) f) := by
      -- By definition of $f_bin$, we know that $f_bin f n i = \text{indicator} (\text{bin\_interval} n i) f$.
      simp [f_bin];
    -- By definition of bin_masses, we have that bin_masses f n i is equal to the integral of the indicator function of the bin interval n i times f.
    convert h_integral using 1

lemma f_bin_integrable (f : ℝ → ℝ) (hf : MeasureTheory.Integrable f MeasureTheory.volume) (n : ℕ) (i : Fin (2 * n)) :
  MeasureTheory.Integrable (f_bin f n i) MeasureTheory.volume := by
  refine' MeasureTheory.Integrable.mono' _ _ _;
  refine' fun x => |f x|;
  · exact hf.norm;
  · exact MeasureTheory.AEStronglyMeasurable.indicator ( hf.1 ) ( measurableSet_Ico );
  · filter_upwards [ ] with x using by rw [ f_bin ] ; rw [ Set.indicator_apply ] ; aesop;

lemma convolution_mono_pointwise (f g : ℝ → ℝ) (hf : 0 ≤ f) (hg : 0 ≤ g) (hfg : g ≤ f)
    (x : ℝ)
    (h_int_f : MeasureTheory.Integrable (fun t => f t * f (x - t)) MeasureTheory.volume) :
    MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤
    MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  rw [MeasureTheory.convolution, MeasureTheory.convolution]
  simp only [ContinuousLinearMap.mul_apply']
  by_cases h_int_g : MeasureTheory.Integrable (fun t => g t * g (x - t)) MeasureTheory.volume
  · apply MeasureTheory.integral_mono h_int_g h_int_f
    intro t
    apply mul_le_mul (hfg t) (hfg (x - t)) (hg (x - t)) (hf t)
  · rw [MeasureTheory.integral_undef h_int_g]
    apply MeasureTheory.integral_nonneg
    intro t
    apply mul_nonneg (hf t) (hf (x - t))

lemma support_f_bin (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) :
  Function.support (f_bin f n i) ⊆ bin_interval n i := by
    -- The support of $f_{\text{bin}}$ is the closure of the set where $f_{\text{bin}}$ is non-zero, which is exactly the bin_interval.
    simp [f_bin, Function.support]

lemma averaging_principle_ennreal (g : ℝ → ℝ) (hg : 0 ≤ g)
    (h_supp_meas : MeasurableSet (Function.support g))
    (h_supp_finite : MeasureTheory.volume (Function.support g) < ⊤) :
    MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume * MeasureTheory.volume (Function.support g) ≥
    MeasureTheory.lintegral MeasureTheory.volume (fun x => ENNReal.ofReal (g x)) := by
  have h_integral_bound : ∀ᵐ x ∂MeasureTheory.Measure.restrict MeasureTheory.volume (Function.support g), ENNReal.ofReal (g x) ≤ MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume := by
    have h_ess_sup : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume.restrict (Function.support g), ‖g x‖ₑ ≤ essSup (fun x => ‖g x‖ₑ) MeasureTheory.MeasureSpace.volume := by
      have h_ess_sup : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, ‖g x‖ₑ ≤ essSup (fun x => ‖g x‖ₑ) MeasureTheory.MeasureSpace.volume := by
        exact?
      generalize_proofs at *; (
      exact MeasureTheory.ae_restrict_of_ae h_ess_sup);
    filter_upwards [ h_ess_sup ] with x hx using le_trans ( by rw [ Real.enorm_eq_ofReal ( hg x ) ] ) hx;
  have h_integral_bound : ∫⁻ x in Function.support g, ENNReal.ofReal (g x) ≤ ∫⁻ x in Function.support g, MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume := by
    apply_rules [ MeasureTheory.lintegral_mono_ae ];
  simp_all +decide [ mul_comm, MeasureTheory.lintegral_const ];
  rwa [ MeasureTheory.lintegral_congr_ae, MeasureTheory.lintegral_indicator ] ; aesop;
  filter_upwards [ ] with x using by by_cases hx : g x = 0 <;> simp +decide [ hx ] ;

lemma measure_support_convolution_f_bin (f : ℝ → ℝ) (n : ℕ) (hn : n > 0) (i : Fin (2 * n)) :
  MeasureTheory.volume (Function.support (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume)) ≤ ENNReal.ofReal (1 / (2 * n : ℝ)) := by
  -- Let's choose any $x$ in the support of the convolution.
  have h_support_convolution : ∀ x, x ∉ (bin_interval n i + bin_interval n i) → (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.MeasureSpace.volume) x = 0 := by
    -- If $x$ is not in the sum of the two bin intervals, then there is no $t$ such that both $t$ and $x - t$ are in the bin interval.
    intro x hx
    have h_no_t : ∀ t, ¬(t ∈ bin_interval n i ∧ x - t ∈ bin_interval n i) := by
      exact fun t ht => hx <| Set.add_mem_add ht.1 ht.2 |> fun h => by simpa [ add_comm ] using h;
    simp_all +decide [ MeasureTheory.convolution, f_bin ];
    rw [ MeasureTheory.integral_eq_zero_of_ae ] ; filter_upwards [ ] with t ; by_cases ht : t ∈ bin_interval n i <;> by_cases ht' : x - t ∈ bin_interval n i <;> simp_all +decide [ Set.indicator ] ;
  refine' le_trans ( MeasureTheory.measure_mono ( show Function.support ( MeasureTheory.convolution ( f_bin f n i ) ( f_bin f n i ) ( ContinuousLinearMap.mul ℝ ℝ ) MeasureTheory.MeasureSpace.volume ) ⊆ bin_interval n i + bin_interval n i from fun x hx => by contrapose! hx; aesop ) ) _;
  have h_support_convolution : bin_interval n i + bin_interval n i ⊆ Set.Ico (-(1/4 : ℝ) + i * (1 / (4 * n : ℝ)) + (-(1/4 : ℝ) + i * (1 / (4 * n : ℝ)))) (-(1/4 : ℝ) + (i + 1) * (1 / (4 * n : ℝ)) + (-(1/4 : ℝ) + (i + 1) * (1 / (4 * n : ℝ)))) := by
    intro x hx; obtain ⟨ a, ha, b, hb, rfl ⟩ := hx; constructor <;> linarith [ Set.mem_Ico.mp ha, Set.mem_Ico.mp hb ] ;
  refine' le_trans ( MeasureTheory.measure_mono h_support_convolution ) _ ; norm_num ; ring ; norm_num [ hn.ne' ]

lemma integral_convolution_f_bin (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n))
    (hf : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.integral MeasureTheory.volume (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) = (bin_masses f n i) ^ 2 := by
      have h_integral : ∫ x, MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ∂MeasureTheory.volume = (∫ x, f_bin f n i x ∂MeasureTheory.volume) * (∫ x, f_bin f n i x ∂MeasureTheory.volume) := by
        have h_convolution : ∀ (f g : ℝ → ℝ), MeasureTheory.Integrable f MeasureTheory.volume → MeasureTheory.Integrable g MeasureTheory.volume → ∫ x, MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x = (∫ x, f x) * (∫ x, g x) := by
          intro f g hf hg; rw [ MeasureTheory.integral_convolution ] ; aesop;
          · exact hf;
          · exact hg;
        exact h_convolution _ _ ( f_bin_integrable f hf n i ) ( f_bin_integrable f hf n i );
      rw [ h_integral, sq, integral_f_bin ]

lemma convolution_mono_ae (f : ℝ → ℝ) (hf : 0 ≤ f) (n : ℕ) (i : Fin (2 * n))
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume) :
    ∀ᵐ x ∂MeasureTheory.volume,
      MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤
      MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  have h_bin_le : f_bin f n i ≤ f := f_bin_le_f f hf n i
  have h_bin_nonneg : 0 ≤ f_bin f n i := f_bin_nonneg f hf n i
  have h_bin_int : MeasureTheory.Integrable (f_bin f n i) MeasureTheory.volume := f_bin_integrable f hf_int n i
  -- We need to show that for a.e. x, the convolution inequality holds.
  -- We know convolution_mono_pointwise holds if the integral is defined.
  -- Convolution is defined a.e. for L1 functions.
  -- Specifically, the function t -> f(t)f(x-t) is integrable for a.e. x.
  have h_conv_exists_f : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.Integrable (fun t => f t * f (x - t)) MeasureTheory.volume := by
    -- This is a standard result: convolution of L1 functions is L1, so it's finite a.e., which implies the inner integral exists a.e.
    -- Actually, we need to find the specific Mathlib lemma.
    -- MeasureTheory.Integrable.convolution_integrable?
    -- Or use the fact that convolution is defined as integral.
    -- If convolution is finite, the integral is defined?
    -- convolution f g is defined as \int f(t)g(x-t).
    -- If f, g are L1, then f*g is L1.
    -- So \int |f*g| < infinity.
    -- This implies |f*g|(x) < infinity a.e.
    -- This implies the integral defining f*g exists a.e.
    have h_int_f : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => f p.1 * f p.2) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
      exact hf_int.prod_mul hf_int;
    have h_int_f : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => f p.1 * f (p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
      have h_int_f : MeasureTheory.MeasurePreserving (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
        exact?;
      have h_int_f : MeasureTheory.Integrable (fun (p : ℝ × ℝ) => f p.1 * f p.2) (MeasureTheory.Measure.map (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume)) := by
        rw [ h_int_f.map_eq ] ; assumption;
      convert h_int_f.comp_measurable ( measurable_fst.prodMk ( measurable_snd.sub measurable_fst ) ) using 1;
    rw [ MeasureTheory.integrable_prod_iff' ] at h_int_f ; aesop;
    exact h_int_f.1
  filter_upwards [h_conv_exists_f] with x hx
  apply convolution_mono_pointwise f (f_bin f n i) hf h_bin_nonneg h_bin_le x hx

lemma measure_support_convolution_f_bin_lt_top (f : ℝ → ℝ) (n : ℕ) (hn : n > 0) (i : Fin (2 * n)) :
  MeasureTheory.volume (Function.support (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume)) < ⊤ := by
  apply lt_of_le_of_lt (measure_support_convolution_f_bin f n hn i)
  apply ENNReal.ofReal_lt_top

lemma averaging_principle_ennreal_subset (g : ℝ → ℝ) (hg : 0 ≤ g)
    (S : Set ℝ) (hS : Function.support g ⊆ S)
    (hS_meas : MeasurableSet S)
    (hS_finite : MeasureTheory.volume S < ⊤) :
    MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume * MeasureTheory.volume S ≥
    MeasureTheory.lintegral MeasureTheory.volume (fun x => ENNReal.ofReal (g x)) := by
      -- By definition of $eLpNorm$, we know that for any measurable set $A$, $\int_A g \leq eLpNorm g \infty \cdot \text{volume}(A)$.
      have h_eLpNorm : ∀ A : Set ℝ, MeasurableSet A → MeasureTheory.volume A < ⊤ → ∫⁻ x in A, ENNReal.ofReal (g x) ≤ MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume * MeasureTheory.volume A := by
        -- By definition of $eLpNorm$, we know that for any measurable set $A$ with finite measure, $\int_A g \leq eLpNorm g \infty \cdot \text{volume}(A)$.
        intros A hA_meas hA_finite
        have h_eLpNorm : ∀ᵐ x ∂MeasureTheory.volume, x ∈ A → ENNReal.ofReal (g x) ≤ MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume := by
          have h_eLpNorm : ∀ᵐ x ∂MeasureTheory.volume, ENNReal.ofReal (g x) ≤ MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume := by
            have h_eLpNorm_def : MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume = essSup (fun x => ENNReal.ofReal (g x)) MeasureTheory.volume := by
              simp +decide [ MeasureTheory.eLpNormEssSup ];
              simp +decide [ Real.enorm_eq_ofReal ( hg _ ) ]
            rw [ h_eLpNorm_def ];
            exact?;
          exact h_eLpNorm.mono fun x hx hx' => hx;
        refine' le_trans ( MeasureTheory.lintegral_mono_ae <| Filter.eventually_of_mem ( MeasureTheory.ae_restrict_iff' hA_meas |>.2 h_eLpNorm ) fun x hx => hx ) _ ; aesop;
      specialize h_eLpNorm S hS_meas hS_finite;
      convert h_eLpNorm.ge using 1;
      rw [ MeasureTheory.lintegral_congr_ae, MeasureTheory.lintegral_indicator ];
      · assumption;
      · filter_upwards [ ] with x ; by_cases hx : x ∈ S <;> simp_all +decide [ Function.support ];
        exact le_of_not_gt fun hx' => hx <| hS <| ne_of_gt hx'

lemma averaging_principle_ennreal_subset' (g : ℝ → ℝ) (hg : 0 ≤ g)
    (S : Set ℝ) (hS : Function.support g ⊆ S)
    (hS_meas : MeasurableSet S)
    (hS_finite : MeasureTheory.volume S < ⊤) :
    MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume * MeasureTheory.volume S ≥
    MeasureTheory.lintegral MeasureTheory.volume (fun x => ENNReal.ofReal (g x)) := by
      exact?

lemma lintegral_le_norm_mul_vol (g : ℝ → ℝ) (hg : 0 ≤ g)
    (S : Set ℝ) (hS : Function.support g ⊆ S)
    (hS_meas : MeasurableSet S) :
    MeasureTheory.lintegral MeasureTheory.volume (fun x => ENNReal.ofReal (g x)) ≤
    MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume * MeasureTheory.volume S := by
      by_cases hS_finite : MeasureTheory.volume S < ⊤;
      · exact?;
      · by_cases h : MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume = 0 <;> simp_all +decide;
        rw [ MeasureTheory.lintegral_congr_ae ( h.mono fun x hx => by aesop ) ] ; norm_num

lemma lintegral_convolution_f_bin (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n))
    (hf : MeasureTheory.Integrable f MeasureTheory.volume)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (M_i : ℝ) (hM : M_i = bin_masses f n i) :
    MeasureTheory.lintegral MeasureTheory.volume (fun x => ENNReal.ofReal (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x)) = ENNReal.ofReal (M_i^2) := by
      -- By definition of $f_bin$, we know that $\int_{\mathbb{R}} f_bin(n, i)(x) \, dx = M_i$.
      have h_integral_f_bin : ∫ x, MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x = (M_i) ^ 2 := by
        rw [ hM, integral_convolution_f_bin f n i hf ];
      rw [ ← h_integral_f_bin, MeasureTheory.ofReal_integral_eq_lintegral_ofReal ];
      · -- Since $f_bin$ is integrable, the convolution of $f_bin$ with itself is also integrable.
        have h_conv_integrable : MeasureTheory.Integrable (f_bin f n i) MeasureTheory.volume := by
          exact?;
        exact?;
      · refine' Filter.Eventually.of_forall _;
        -- Since $f_bin$ is non-negative, the product $f_bin(y) * f_bin(x-y)$ is non-negative for all $y$, and thus the integral is non-negative.
        intros x
        simp [MeasureTheory.convolution, hf_nonneg];
        exact MeasureTheory.integral_nonneg fun t => mul_nonneg ( f_bin_nonneg f hf_nonneg n i t ) ( f_bin_nonneg f hf_nonneg n i ( x - t ) )

lemma lintegral_convolution_f_bin' (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n))
    (hf : MeasureTheory.Integrable f MeasureTheory.volume)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (M_i : ℝ) (hM : M_i = bin_masses f n i) :
    MeasureTheory.lintegral MeasureTheory.volume (fun x => ENNReal.ofReal (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x)) = ENNReal.ofReal (M_i^2) := by
  rw [← MeasureTheory.ofReal_integral_eq_lintegral_ofReal]
  · rw [integral_convolution_f_bin f n i hf, hM]
  · -- Integrability of convolution
    apply MeasureTheory.Integrable.integrable_convolution (ContinuousLinearMap.mul ℝ ℝ) (f_bin_integrable f hf n i) (f_bin_integrable f hf n i)
  · -- Non-negativity of convolution
    filter_upwards [] with x
    rw [MeasureTheory.convolution]
    apply MeasureTheory.integral_nonneg
    intro t
    simp only [ContinuousLinearMap.mul_apply']
    apply mul_nonneg
    · apply f_bin_nonneg f hf_nonneg
    · apply f_bin_nonneg f hf_nonneg

lemma single_bin_bound_ennreal (n : ℕ) (hn : n > 0)
    (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (i : Fin (2 * n)) (M_i : ℝ) (hM : M_i = bin_masses f n i)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.eLpNorm (MeasureTheory.convolution f f
      (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≥
    ENNReal.ofReal ((2 * n : ℝ) * M_i ^ 2) := by
      have h_ess_sup_i : MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume * ENNReal.ofReal (1 / (2 * n)) ≥ ENNReal.ofReal (M_i^2) := by
        -- Apply the averaging principle to the convolution of $f_bin f n i$ with itself.
        have h_avg_principle : MeasureTheory.eLpNorm (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume * ENNReal.ofReal (1 / (2 * n : ℝ)) ≥ ENNReal.ofReal (M_i^2) := by
          have h_ess_sup_i : ∫⁻ x, ENNReal.ofReal (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x) ∂MeasureTheory.volume ≤ MeasureTheory.eLpNorm (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume * ENNReal.ofReal (1 / (2 * n : ℝ)) := by
            convert lintegral_le_norm_mul_vol _ _ _ _ _ using 1;
            rotate_left;
            rotate_left;
            exact Set.Ico ( - ( 1 / 4 ) + i * ( 1 / ( 4 * n ) ) + ( - ( 1 / 4 ) + i * ( 1 / ( 4 * n ) ) ) ) ( - ( 1 / 4 ) + ( i + 1 ) * ( 1 / ( 4 * n ) ) + ( - ( 1 / 4 ) + ( i + 1 ) * ( 1 / ( 4 * n ) ) ) );
            · intro x hx;
              contrapose! hx; simp_all +decide [ MeasureTheory.convolution ] ;
              rw [ MeasureTheory.integral_eq_zero_of_ae ];
              filter_upwards [ ] with t ; by_cases ht : f_bin f n i t = 0 <;> by_cases ht' : f_bin f n i ( x - t ) = 0 <;> simp_all +decide [ f_bin ];
              unfold bin_interval at * ; norm_num at * ; linarith [ hx ( by linarith ) ] ;
            · exact measurableSet_Ico;
            · norm_num [ add_assoc, mul_add, add_mul, mul_comm, mul_left_comm, hn.ne' ];
              rw [ ← ENNReal.ofReal_mul ( by positivity ) ] ; ring;
            · intro x; exact (by
              refine' MeasureTheory.integral_nonneg fun t => mul_nonneg ( f_bin_nonneg f hf n i t ) ( f_bin_nonneg f hf n i ( x - t ) ));
          refine' le_trans _ h_ess_sup_i;
          rw [ lintegral_convolution_f_bin' ] <;> aesop;
        -- Since the convolution of $f$ with itself is greater than or equal to the convolution of $f_bin f n i$ with itself almost everywhere, we can apply the monotonicity of the essential supremum.
        have h_mono : MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≥ MeasureTheory.eLpNorm (MeasureTheory.convolution (f_bin f n i) (f_bin f n i) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume := by
          apply_rules [ MeasureTheory.eLpNorm_mono_ae ];
          filter_upwards [ convolution_mono_ae f hf n i hf_int ] with x hx using by rw [ Real.norm_of_nonneg ( show 0 ≤ MeasureTheory.convolution ( f_bin f n i ) ( f_bin f n i ) ( ContinuousLinearMap.mul ℝ ℝ ) MeasureTheory.MeasureSpace.volume x from by
                                                                                                                refine' MeasureTheory.integral_nonneg fun t => _;
                                                                                                                simp [f_bin];
                                                                                                                exact mul_nonneg ( by rw [ Set.indicator_apply ] ; aesop ) ( by rw [ Set.indicator_apply ] ; aesop ) ), Real.norm_of_nonneg ( show 0 ≤ MeasureTheory.convolution f f ( ContinuousLinearMap.mul ℝ ℝ ) MeasureTheory.MeasureSpace.volume x from by
                                                                                                                                                                                                                                                                                              exact MeasureTheory.integral_nonneg fun y => mul_nonneg ( hf _ ) ( hf _ ) ) ] ; exact hx;
        exact h_avg_principle.trans ( mul_le_mul_right' h_mono _ );
      have h_ess_sup_i : MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≥ ENNReal.ofReal (M_i^2) * ENNReal.ofReal (2 * n) := by
        refine' le_trans ( mul_le_mul_right' h_ess_sup_i _ ) _;
        rw [ mul_assoc, ← ENNReal.ofReal_mul ( by positivity ), one_div_mul_cancel ( by positivity ), ENNReal.ofReal_one, mul_one ];
      convert h_ess_sup_i using 1 ; rw [ mul_comm, ENNReal.ofReal_mul ( by positivity ) ]

lemma ennreal_mul_inv_le_imp_le_mul (a : ENNReal) (k m : ℝ) (hk : 0 < k)
    (h : a * ENNReal.ofReal (1 / k) ≥ ENNReal.ofReal m) :
    a ≥ ENNReal.ofReal (k * m) := by
      contrapose! h with h_contra; simp_all +decide [ mul_assoc, mul_comm, mul_left_comm ] ; (
      rw [ ← ENNReal.toReal_lt_toReal ] at * <;> norm_num at *;
      · rw [ ENNReal.toReal_ofReal, ENNReal.toReal_ofReal ] at * <;> try nlinarith;
        · rwa [ ← div_eq_mul_inv, div_lt_iff₀' hk ] at *;
        · nlinarith [ show 0 ≤ a.toReal by positivity ];
        · exact le_of_not_gt fun h => by rw [ ENNReal.ofReal_eq_zero.mpr h.le ] at h_contra; norm_num at h_contra; linarith [ show 0 ≤ a.toReal from ENNReal.toReal_nonneg ] ;
      · aesop;
      · rw [ ENNReal.mul_eq_top ] ; aesop);

theorem single_bin_bound (n : ℕ) (hn : n > 0)
    (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (i : Fin (2 * n)) (M_i : ℝ) (hM : M_i = bin_masses f n i)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (h_fin : MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume < ⊤) :
    (MeasureTheory.eLpNorm (MeasureTheory.convolution f f
      (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥
    (2 * n : ℝ) * M_i ^ 2 := by
      -- Apply the single_bin_bound_ennreal lemma to get the ENNReal inequality.
      have h_ennreal : MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≥ ENNReal.ofReal ((2 * n : ℝ) * M_i ^ 2) := by
        -- Apply the single_bin_bound_ennreal lemma with the given hypotheses.
        apply single_bin_bound_ennreal n hn f hf hf_supp i M_i hM hf_int;
      -- Since the eLpNorm is finite, we can convert the ENNReal inequality to a real number inequality by taking the real part.
      have h_real : (MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥ (ENNReal.ofReal ((2 * n : ℝ) * M_i ^ 2)).toReal := by
        -- Since the eLpNorm is finite, we can convert the ENNReal inequality to a real number inequality by taking the real part of both sides.
        apply ENNReal.toReal_mono h_fin.ne h_ennreal;
      rwa [ ENNReal.toReal_ofReal ( by positivity ) ] at h_real

theorem exists_invariant_under_permutation {α : Type*} [DecidableEq α]
    (S : Finset α) (P : α → Prop) [DecidablePred P] :
    (∃ x ∈ S, P x) ↔ (∃ x ∈ S, P x) :=
  Iff.rfl

theorem conv_total {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) :
    ∑ k ∈ Finset.range (2*d-1),
      (∑ i : Fin d, ∑ j : Fin d, if i.1+j.1=k then c i * c j else 0) = m ^ 2 := by
        rw [ ← hc, sq, Finset.sum_comm ];
        -- The inner sum over $x$ is just the sum over $j$ where $y + j = x$, which is $c_y * c_j$.
        have h_inner : ∀ y : Fin d, ∑ x ∈ Finset.range (2 * d - 1), ∑ j : Fin d, (if y.val + j.val = x then c y * c j else 0) = ∑ j : Fin d, c y * c j := by
          intro y; rw [ Finset.sum_comm ] ; simp +decide [ Finset.sum_ite ] ;
          -- Since $y$ and $x$ are both in $\text{Fin } d$, their values are between $0$ and $d-1$. Therefore, $y.val + x.val$ is always less than $2d-1$.
          have h_bound : ∀ x : Fin d, y.val + x.val < 2 * d - 1 := by
            grind;
          rw [ Finset.filter_true_of_mem fun x hx => h_bound x ];
        simp +decide only [h_inner, ← Finset.mul_sum _ _ _, ← Finset.sum_mul]

theorem conv_total' {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) :
    ∑ k ∈ Finset.range (2*d-1),
      (∑ i : Fin d, ∑ j : Fin d, if i.1+j.1=k then c i * c j else 0) = m ^ 2 := by
        -- Apply the convolution theorem to conclude the proof.
        apply conv_total c m hc

theorem conv_entry_le_total {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) (k : ℕ) :
    (∑ i : Fin d, ∑ j : Fin d, if i.1+j.1=k then c i * c j else 0) ≤ m ^ 2 := by
      -- The sum of the convolution terms is less than or equal to the sum of all possible products $c_i c_j$.
      have h_conv_le_sum : ∑ i : Fin d, ∑ j : Fin d, (if i.val + j.val = k then c i * c j else 0) ≤ ∑ i : Fin d, ∑ j : Fin d, c i * c j := by
        -- Since each term in the sum is either c_i * c_j or 0, and 0 is less than or equal to c_i * c_j, the sum of the if terms is less than or equal to the sum of the c_i * c_j terms.
        apply Finset.sum_le_sum; intro i _; apply Finset.sum_le_sum; intro j _; split_ifs <;> norm_num;
      -- The sum of all possible products $c_i c_j$ is equal to $(\sum_{i} c_i)^2$.
      have h_sum_sq : ∑ i : Fin d, ∑ j : Fin d, c i * c j = (∑ i : Fin d, c i) ^ 2 := by
        simp +decide only [← Finset.mul_sum _ _ _, ← Finset.sum_mul, sq];
      -- Substitute hc into h_sum_sq to get the desired inequality.
      rw [hc] at h_sum_sq; exact h_conv_le_sum.trans h_sum_sq.le

theorem int32_safe (m : ℕ) (hm : m ≤ 200) : m ^ 2 ≤ 2 ^ 31 - 1 := by
  norm_num
  calc m ^ 2 ≤ 200 ^ 2 := by gcongr
    _ = 40000 := by norm_num
    _ ≤ 2147483647 := by norm_num