/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: fd0c8f2e-0018-4c2c-81a6-b86976a60fff

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  let norm_inf := (MeasureTheory.eLpNorm conv ⊤ MeasureTheory.volume).toReal
  let integral := MeasureTheory.integral MeasureTheory.volume f
  norm_inf / (integral ^ 2)

noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

noncomputable def canonical_discretization (f : ℝ → ℝ) (n m : ℕ) : Fin (2 * n) → ℕ :=
  fun i =>
    let masses := bin_masses f n
    let total_mass := ∑ j, masses j
    let cum_mass (k : ℕ) := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
    let target_cum (k : ℕ) := (cum_mass k) / total_mass * m
    let discrete_cum (k : ℕ) := ⌊target_cum k⌋.natAbs
    if i.1 + 1 < 2 * n then discrete_cum (i.1 + 1) - discrete_cum i.1
    else m - discrete_cum i.1

def discrete_autoconvolution {d : ℕ} (a : Fin d → ℝ) (k : ℕ) : ℝ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then a i * a j else 0

noncomputable def test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let a : Fin d → ℝ := fun i => (4 * n : ℝ) / m * (c i : ℝ)
  let conv := discrete_autoconvolution a
  let sum_conv := ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), conv k
  (1 / (4 * n * ℓ : ℝ)) * sum_conv

def contributing_bins (n : ℕ) (ℓ s_lo : ℕ) : Finset (Fin (2 * n)) :=
  let d := 2 * n
  Finset.filter (fun i => ∃ j : Fin d, s_lo ≤ i.1 + j.1 ∧ i.1 + j.1 ≤ s_lo + ℓ - 2) Finset.univ

theorem contributing_bins_iff (n : ℕ) (hn : n > 0) (ℓ s_lo : ℕ)
    (hℓ : 2 ≤ ℓ) (i : Fin (2 * n)) :
    i ∈ contributing_bins n ℓ s_lo ↔
      Nat.max 0 (s_lo - (2 * n - 1)) ≤ i.1 ∧ i.1 ≤ Nat.min (2 * n - 1) (s_lo + ℓ - 2) := by
  -- By definition of contributing_bins, we need to show that there exists a j such that s_lo ≤ i.1 + j.1 ≤ s_lo + ℓ - 2 if and only if max(0, s_lo - (2n-1)) ≤ i.1 ≤ min(2n-1, s_lo + ℓ - 2).
  simp [contributing_bins];
  constructor;
  · grind;
  · -- Let's choose $j$ to be the minimum of $(s_lo + ℓ - 2 - i.1)$ and $(2n - 1)$.
    intro h
    use ⟨min (s_lo + ℓ - 2 - i.1) (2 * n - 1), by
      exact lt_of_le_of_lt ( min_le_right _ _ ) ( Nat.sub_lt ( by positivity ) ( by positivity ) )⟩
    generalize_proofs at *;
    grind +ring

noncomputable def ideal_test_value (f : ℝ → ℝ) (n : ℕ) (ℓ s_lo : ℕ) : ℝ :=
  let masses := bin_masses f n
  let d := 2 * n
  let a : Fin d → ℝ := fun i => (4 * n : ℝ) * masses i
  let conv := discrete_autoconvolution a
  let sum_conv := ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), conv k
  (1 / (4 * n * ℓ : ℝ)) * sum_conv

lemma sum_bin_masses_eq_one (n : ℕ) (hn : n > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1) :
    ∑ i : Fin (2 * n), bin_masses f n i = 1 := by
  -- The integral of $f$ over each interval is defined as the integral of $f$ over that interval.
  have h_integral_sum : ∑ i : Fin (2 * n), ∫ x in Set.Ico (-1 / 4 + i.val / (4 * n : ℝ)) (-1 / 4 + (i.val + 1) / (4 * n : ℝ)), f x = ∫ x in Set.Ico (-1 / 4) (-1 / 4 + (2 * n : ℝ) / (4 * n : ℝ)), f x := by
    have h_integral_sum : ∑ i ∈ Finset.range (2 * n), ∫ x in Set.Ico (-1 / 4 + i / (4 * n : ℝ)) (-1 / 4 + (i + 1) / (4 * n : ℝ)), f x = ∫ x in Set.Ico (-1 / 4) (-1 / 4 + (2 * n : ℝ) / (4 * n : ℝ)), f x := by
      have h_integral_sum : ∀ m : ℕ, ∑ i ∈ Finset.range m, ∫ x in Set.Ico (-1 / 4 + i / (4 * n : ℝ)) (-1 / 4 + (i + 1) / (4 * n : ℝ)), f x = ∫ x in Set.Ico (-1 / 4) (-1 / 4 + m / (4 * n : ℝ)), f x := by
        intro m
        induction' m with m ih
        · simp
        ·
          rw [ Finset.sum_range_succ, ih, Nat.cast_succ, add_div, ← MeasureTheory.setIntegral_union ] <;> norm_num;
          · rw [ Set.Ico_union_Ico_eq_Ico ] <;> ring <;> norm_num [ hn ];
          · exact MeasureTheory.Integrable.integrableOn ( MeasureTheory.integrable_of_integral_eq_one hf_int );
          · exact MeasureTheory.Integrable.integrableOn ( MeasureTheory.integrable_of_integral_eq_one hf_int );
      exact_mod_cast h_integral_sum ( 2 * n );
    rw [ ← h_integral_sum, Finset.sum_range ];
  convert h_integral_sum using 1 ; ring_nf ; norm_num [ hn.ne' ];
  · unfold bin_masses; congr; ext; ring; norm_num [ hn.ne' ] ; ring;
    rw [ MeasureTheory.integral_indicator ( measurableSet_Ico ) ];
  · rw [ ← MeasureTheory.integral_Icc_eq_integral_Ico, MeasureTheory.integral_Icc_eq_integral_Ioc, ← intervalIntegral.integral_of_le ] <;> ring <;> norm_num [ hn.ne' ];
    rw [ intervalIntegral.integral_of_le ] <;> norm_num [ hf_int ];
    rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero ] <;> norm_num [ hf_int ];
    exact fun x hx => Classical.not_not.1 fun hx' => by have := hf_supp hx'; norm_num at * ; linarith [ hx ( by linarith ) ] ;

lemma floor_diff_bound (x y : ℝ) : |(⌊x⌋ : ℝ) - ⌊y⌋ - (x - y)| < 1 := by
  -- By the properties of the floor function, we know that $⌊x⌋ \leq x < ⌊x⌋ + 1$ and $⌊y⌋ \leq y < ⌊y⌋ + 1$.
  have h_floor : (⌊x⌋ : ℝ) ≤ x ∧ x < (⌊x⌋ : ℝ) + 1 ∧ (⌊y⌋ : ℝ) ≤ y ∧ y < (⌊y⌋ : ℝ) + 1 := by
    -- By definition of floor function, we know that ⌊x⌋ ≤ x < ⌊x⌋ + 1 and ⌊y⌋ ≤ y < ⌊y⌋ + 1.
    apply And.intro (Int.floor_le x) (And.intro (Int.lt_floor_add_one x) (And.intro (Int.floor_le y) (Int.lt_floor_add_one y)))
  generalize_proofs at *; (
  -- By combining the inequalities from the properties of the floor function, we can conclude that |(⌊x⌋ - ⌊y⌋) - (x - y)| < 1.
  apply abs_lt.mpr
  constructor
  linarith
  linarith)

noncomputable def cumulative_mass (f : ℝ → ℝ) (n : ℕ) (k : ℕ) : ℝ :=
  ∑ j : Fin (2 * n), if j.1 < k then bin_masses f n j else 0

noncomputable def discrete_cum_global (f : ℝ → ℝ) (n m : ℕ) (k : ℕ) : ℕ :=
  ⌊cumulative_mass f n k * m⌋.natAbs

lemma c_eq_diff_discrete_cum (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c) :
    (∀ i : Fin (2 * n), i.1 < 2 * n - 1 → c i = discrete_cum_global f n m (i.1 + 1) - discrete_cum_global f n m i.1) ∧
    (c ⟨2 * n - 1, Nat.sub_lt (Nat.mul_pos (by norm_num) hn) (by norm_num)⟩ = m - discrete_cum_global f n m (2 * n - 1)) := by
  unfold canonical_discretization at hc;
  refine' ⟨ fun i hi => _, _ ⟩;
  · rw [ ← hc ];
    simp +decide [ hi.trans_le ( Nat.sub_le _ _ ), sum_bin_masses_eq_one n hn f hf_supp hf_int ];
    rw [ if_pos ( by omega ) ];
    congr! 2;
  · convert congr_fun hc.symm ⟨ 2 * n - 1, Nat.sub_lt ( by positivity ) ( by positivity ) ⟩ using 1;
    simp +decide [ Nat.sub_add_cancel ( by linarith : 1 ≤ 2 * n ) ];
    rw [ sum_bin_masses_eq_one n hn f hf_supp hf_int ] ; norm_num [ discrete_cum_global ];
    rfl

lemma abs_sub_floor_lt_one (x : ℝ) : |x - ⌊x⌋| < 1 := by
  -- By definition of floor function, we know that $|x - \lfloor x \rfloor| < 1$ for any real number $x$.
  apply abs_lt.mpr
  constructor
  · linarith [Int.floor_le x]
  · linarith [Int.lt_floor_add_one x]

lemma cumulative_mass_recurrence (f : ℝ → ℝ) (n : ℕ) (k : ℕ) (hk : k < 2 * n) :
    cumulative_mass f n (k + 1) = cumulative_mass f n k + bin_masses f n ⟨k, hk⟩ := by
  -- By definition of cumulative_mass, we can split the sum into the sum up to k and the term for j.1 = k.
  have h_split : ∑ j : Fin (2 * n), (if j.1 < k + 1 then bin_masses f n j else 0) = ∑ j : Fin (2 * n), (if j.1 < k then bin_masses f n j else 0) + ∑ j : Fin (2 * n), (if j.1 = k then bin_masses f n j else 0) := by
    simpa only [ ← Finset.sum_add_distrib ] using Finset.sum_congr rfl fun x hx => by split_ifs <;> first | linarith | omega;
  convert h_split using 1;
  congr! 1;
  rw [ Finset.sum_eq_single ⟨ k, hk ⟩ ] <;> aesop

lemma bin_masses_nonneg (n : ℕ) (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (i : Fin (2 * n)) :
    0 ≤ bin_masses f n i := by
  -- Since the integral of a non-negative function over any interval is non-negative, we have:
  have h_bin_mass_nonneg : ∀ i : Fin (2 * n), 0 ≤ ∫ x in Set.Ico (-(1 / 4 : ℝ) + i.val * (1 / (4 * n : ℝ))) (-(1 / 4 : ℝ) + (i.val + 1) * (1 / (4 * n : ℝ))), f x := by
    -- Since $f$ is non-negative, the integral of $f$ over any interval is non-negative. This follows from the fact that the integral of a non-negative function is non-negative.
    intros i
    apply MeasureTheory.integral_nonneg
    intro x
    apply hf_nonneg;
  convert h_bin_mass_nonneg i using 1;
  -- By definition of bin_masses, we have:
  simp [bin_masses];
  -- The integral of the indicator function over the interval is equal to the integral of f over the interval because the indicator function is 1 on the interval and 0 elsewhere.
  simp [MeasureTheory.integral_indicator]

lemma cumulative_mass_nonneg (f : ℝ → ℝ) (n : ℕ) (k : ℕ) (hf_nonneg : ∀ x, 0 ≤ f x) :
    0 ≤ cumulative_mass f n k := by
  -- Since each bin mass is non-negative, their sum is also non-negative.
  have h_bin_mass_nonneg : ∀ i : Fin (2 * n), 0 ≤ bin_masses f n i := by
    -- Since $f$ is non-negative, the integral of $f$ over any interval is non-negative.
    intros i
    apply bin_masses_nonneg n f hf_nonneg i;
  -- Since each bin mass is non-negative, their sum is also non-negative. We can use the fact that the sum of non-negative terms is non-negative.
  apply Finset.sum_nonneg; intro i _; exact (by
  -- Since the bin mass is non-negative by h_bin_mass_nonneg, and the if statement either returns the bin mass or 0, both of which are non-negative, the entire expression is non-negative.
  split_ifs <;> [ exact h_bin_mass_nonneg i; exact le_rfl ])

lemma discrete_cum_error (f : ℝ → ℝ) (n m : ℕ) (k : ℕ) (hf_nonneg : ∀ x, 0 ≤ f x) :
    abs ((discrete_cum_global f n m k : ℝ) - cumulative_mass f n k * m) < 1 := by
  -- By definition of discrete_cum_global, we have discrete_cum_global f n m k = ⌊cumulative_mass f n k * m⌋.natAbs.
  have h_floor : discrete_cum_global f n m k = ⌊cumulative_mass f n k * m⌋ := by
    -- Since the cumulative mass is non-negative and m is positive, the product cumulative_mass f n k * m is also non-negative. Therefore, the floor of that product is non-negative, and taking the absolute value doesn't change it.
    have h_nonneg : 0 ≤ cumulative_mass f n k * m := by
      -- Since each bin mass is the integral of a non-negative function over an interval, each bin mass is non-negative. Therefore, the sum of non-negative numbers is also non-negative.
      have h_bin_mass_nonneg : ∀ i : Fin (2 * n), 0 ≤ bin_masses f n i := by
        exact?;
      exact mul_nonneg ( Finset.sum_nonneg fun _ _ => by aesop ) ( Nat.cast_nonneg _ );
    -- Since the floor of a non-negative number is non-negative, the absolute value of the floor is just the floor itself.
    have h_floor_nonneg : 0 ≤ ⌊cumulative_mass f n k * m⌋ := by
      exact Int.floor_nonneg.mpr h_nonneg;
    exact Int.natAbs_of_nonneg h_floor_nonneg ▸ rfl;
  rw [ abs_lt ] ; constructor <;> push_cast [ ← @Int.cast_inj ℝ ] at * <;> linarith [ Int.floor_le ( cumulative_mass f n k * m ), Int.lt_floor_add_one ( cumulative_mass f n k * m ) ] ;

lemma bin_mass_error (n m : ℕ) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (i : Fin (2 * n)) :
    abs ((c i : ℝ) / m - bin_masses f n i) < 1 / m := by
  -- Case 1: $i < 2n-1$.
  by_cases h_case : i.1 < 2 * n - 1;
  · -- Applying the lemma for the discrete cumulative mass error.
    obtain ⟨h_cum_diff, h_last⟩ := c_eq_diff_discrete_cum n m (by
    exact Nat.pos_of_ne_zero ( by aesop_cat )) hm f hf_supp hf_int c hc
    generalize_proofs at *;
    rw [ h_cum_diff i h_case, Nat.cast_sub ];
    · rw [ div_sub', abs_div ] <;> norm_num [ hm.ne' ];
      rw [ inv_eq_one_div, div_lt_div_iff_of_pos_right ] <;> norm_cast;
      convert floor_diff_bound ( cumulative_mass f n ( i + 1 ) * m ) ( cumulative_mass f n i * m ) using 1 ; norm_num [ cumulative_mass_recurrence f n i ( by linarith [ Fin.is_lt i ] ) ] ; ring;
      unfold discrete_cum_global; ring;
      rw [ show ( 1 + ( i : ℕ ) ) = ( i : ℕ ) + 1 by ring, cumulative_mass_recurrence f n i ( by linarith [ Fin.is_lt i ] ) ] ; ring;
      rw [ ← Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| show 0 ≤ ( m : ℝ ) * bin_masses f n i + ( m : ℝ ) * cumulative_mass f n i from add_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) <| bin_masses_nonneg n f hf_nonneg _ ) <| mul_nonneg ( Nat.cast_nonneg _ ) <| cumulative_mass_nonneg f n i hf_nonneg ), ← Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| show 0 ≤ ( m : ℝ ) * cumulative_mass f n i from mul_nonneg ( Nat.cast_nonneg _ ) <| cumulative_mass_nonneg f n i hf_nonneg ) ] ; norm_cast;
    · unfold discrete_cum_global;
      rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg <| Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _, Int.natAbs_of_nonneg <| Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ];
      gcongr;
      unfold cumulative_mass; simp +decide [ Finset.sum_ite ] ;
      exact Finset.sum_le_sum_of_subset_of_nonneg ( fun x hx => by exact Finset.mem_filter.mpr ⟨ Finset.mem_univ _, Nat.lt_succ_of_lt <| Finset.mem_filter.mp hx |>.2 ⟩ ) fun _ _ _ => bin_masses_nonneg n f hf_nonneg _;
  · -- By definition of $c$, we know that $c i = m - D_{2n-1}$.
    have h_ci : c i = m - discrete_cum_global f n m (2 * n - 1) := by
      rw [ ← hc ];
      unfold canonical_discretization;
      rw [ if_neg ];
      · rw [ show ( i : ℕ ) = 2 * n - 1 from le_antisymm ( Nat.le_sub_one_of_lt i.2 ) ( not_lt.mp h_case ) ];
        unfold discrete_cum_global;
        rw [ show ( ∑ j : Fin ( 2 * n ), bin_masses f n j ) = 1 from ?_ ] ; norm_num [ cumulative_mass ];
        apply sum_bin_masses_eq_one n (by
        grind) f hf_supp hf_int;
      · omega;
    -- By definition of $bin_masses$, we know that $bin_masses f n i = 1 - M_{2n-1}$.
    have h_bin_masses : bin_masses f n i = 1 - ∑ j : Fin (2 * n), if j.1 < 2 * n - 1 then bin_masses f n j else 0 := by
      have h_bin_masses : ∑ j : Fin (2 * n), bin_masses f n j = 1 := by
        apply sum_bin_masses_eq_one n (by
        linarith [ Fin.is_lt i ]) f hf_supp hf_int;
      rw [ eq_sub_iff_add_eq', ← h_bin_masses ];
      rw [ Finset.sum_eq_add_sum_diff_singleton ( Finset.mem_univ i ) ];
      rw [ Finset.sum_eq_add_sum_diff_singleton ( Finset.mem_univ i ) ];
      rw [ Finset.sum_congr rfl fun x hx => if_pos <| ?_ ];
      · rw [ if_neg h_case, zero_add, add_comm ];
      · grind;
    -- By definition of $discrete_cum_global$, we know that $|(discrete_cum_global f n m (2 * n - 1) : ℝ) - cumulative_mass f n (2 * n - 1) * m| < 1$.
    have h_discrete_cum_global : |(discrete_cum_global f n m (2 * n - 1) : ℝ) - cumulative_mass f n (2 * n - 1) * m| < 1 := by
      exact?;
    rw [ h_ci, Nat.cast_sub ];
    · rw [ h_bin_masses, abs_lt ] at *;
      field_simp;
      constructor <;> linarith! [ show ( ∑ j : Fin ( 2 * n ), if j.val < 2 * n - 1 then bin_masses f n j else 0 : ℝ ) = cumulative_mass f n ( 2 * n - 1 ) by rfl ];
    · have h_discrete_cum_global_le : cumulative_mass f n (2 * n - 1) ≤ 1 := by
        have h_discrete_cum_global_le : ∑ j : Fin (2 * n), bin_masses f n j = 1 := by
          apply sum_bin_masses_eq_one n (by
          linarith [ Fin.is_lt i ]) f hf_supp hf_int;
        refine' le_trans _ h_discrete_cum_global_le.le;
        refine' Finset.sum_le_sum fun j _ => _;
        split_ifs <;> norm_num [ bin_masses_nonneg n f hf_nonneg ];
      exact Nat.le_of_lt_succ <| by rw [ ← @Nat.cast_lt ℝ ] ; push_cast; nlinarith [ abs_lt.mp h_discrete_cum_global ] ;

lemma bin_mass_error_case1 (n m : ℕ) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (i : Fin (2 * n)) (hi : i.1 < 2 * n - 1) :
    abs ((c i : ℝ) / m - bin_masses f n i) < 1 / m := by
  exact?

lemma bin_mass_error_case2 (n m : ℕ) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (i : Fin (2 * n)) (hi : i.1 = 2 * n - 1) :
    abs ((c i : ℝ) / m - bin_masses f n i) < 1 / m := by
  -- Apply `bin_mass_error` lemma for `i = 2 * n - 1`.
  have := bin_mass_error n m hm f hf_supp hf_int hf_nonneg c hc i; aesop

lemma bin_mass_error' (n m : ℕ) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (i : Fin (2 * n)) :
    abs ((c i : ℝ) / m - bin_masses f n i) < 1 / m := by
  -- Apply the lemma `bin_mass_error` to conclude the proof.
  apply bin_mass_error n m hm f hf_supp hf_int hf_nonneg c hc i

lemma sum_c_eq (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (a b : ℕ) (hab : a ≤ b) (hb : b < 2 * n) :
    ∑ j : Fin (2 * n), (if a ≤ j.1 ∧ j.1 ≤ b then c j else 0) =
      if b < 2 * n - 1 then
        discrete_cum_global f n m (b + 1) - discrete_cum_global f n m a
      else
        m - discrete_cum_global f n m a := by
  split_ifs;
  · rw [ eq_comm, tsub_eq_of_eq_add ];
    induction' hab with k hk;
    · -- By definition of $c$, we know that $c_j = D(j+1) - D(j)$ for $j < 2n - 1$.
      have hc_def : ∀ j : Fin (2 * n), j.val < 2 * n - 1 → c j = discrete_cum_global f n m (j.val + 1) - discrete_cum_global f n m j.val := by
        intro j hj; have := c_eq_diff_discrete_cum n m hn hm f hf_supp hf_int c hc; aesop;
      rw [ Finset.sum_eq_single ⟨ a, by linarith ⟩ ];
      · simp +zetaDelta at *;
        rw [ hc_def ⟨ a, hb ⟩ ‹_›, Nat.sub_add_cancel ];
        unfold discrete_cum_global;
        rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg <| Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _, Int.natAbs_of_nonneg <| Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ];
        gcongr;
        unfold cumulative_mass; simp +decide [ Finset.sum_ite ] ;
        exact Finset.sum_le_sum_of_subset_of_nonneg ( fun x hx => by exact Finset.mem_filter.mpr ⟨ Finset.mem_univ _, by linarith [ Finset.mem_filter.mp hx ] ⟩ ) fun _ _ _ => bin_masses_nonneg n f hf_nonneg _;
      · simp +contextual [ Fin.ext_iff ];
        intros; omega;
      · aesop;
    · have h_sum_eq : ∑ j : Fin (2 * n), (if a ≤ j.val ∧ j.val ≤ k.succ then c j else 0) = ∑ j : Fin (2 * n), (if a ≤ j.val ∧ j.val ≤ k then c j else 0) + c ⟨k.succ, hb⟩ := by
        rw [ ← Finset.sum_erase_add _ _ ( Finset.mem_univ ⟨ k.succ, hb ⟩ ), add_comm ];
        rw [ add_comm, Finset.sum_eq_sum_diff_singleton_add ( Finset.mem_univ ⟨ k.succ, hb ⟩ ) ];
        simp +decide [ Finset.sdiff_singleton_eq_erase, Nat.lt_succ_iff ];
        rw [ if_pos ( Nat.le_succ_of_le hk ) ];
        refine' congrArg₂ ( · + · ) ( Finset.sum_congr rfl fun x hx => _ ) rfl;
        split_ifs <;> norm_num at *;
        · exact False.elim <| hx <| Fin.ext <| by linarith [ ‹a ≤ ( x : ℕ ) → k < ( x : ℕ ) › ( by linarith ) ] ;
        · linarith [ ‹a ≤ ( x : ℕ ) → k + 1 < ( x : ℕ ) › ( by linarith ) ];
      have h_c_eq : c ⟨k.succ, hb⟩ = discrete_cum_global f n m (k.succ + 1) - discrete_cum_global f n m (k.succ) := by
        have := c_eq_diff_discrete_cum n m hn hm f hf_supp hf_int c hc;
        exact this.1 _ ‹_›;
      have h_discrete_cum_le : discrete_cum_global f n m (k + 1) ≤ discrete_cum_global f n m (k + 2) := by
        have h_discrete_cum_le : cumulative_mass f n (k + 1) ≤ cumulative_mass f n (k + 2) := by
          unfold cumulative_mass; simp +arith +decide [ Finset.sum_ite ] ;
          exact Finset.sum_le_sum_of_subset_of_nonneg ( fun x hx => by exact Finset.mem_filter.mpr ⟨ Finset.mem_univ _, by linarith [ Finset.mem_filter.mp hx ] ⟩ ) fun _ _ _ => bin_masses_nonneg n f hf_nonneg _;
        unfold discrete_cum_global;
        rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ), Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ) ] ; exact Int.floor_mono <| mul_le_mul_of_nonneg_right h_discrete_cum_le <| Nat.cast_nonneg _;
      grind +ring;
  · -- By definition of $c$, we know that for $j.val < 2 * n - 1$, $c j = D(j + 1) - D(j)$, and for $j.val = 2 * n - 1$, $c j = m - D(2 * n - 1)$.
    have h_c_def : ∀ j : Fin (2 * n), c j = if j.val < 2 * n - 1 then discrete_cum_global f n m (j.val + 1) - discrete_cum_global f n m j.val else m - discrete_cum_global f n m (2 * n - 1) := by
      intro j; exact (by
      rw [ ← hc ];
      split_ifs <;> simp +decide [ *, canonical_discretization ];
      · rw [ if_pos ( by omega ) ];
        rw [ show ( ∑ j : Fin ( 2 * n ), bin_masses f n j ) = 1 from ?_ ] ; norm_num [ discrete_cum_global ];
        · unfold cumulative_mass; aesop;
        · exact?;
      · rw [ if_neg ];
        · -- Since $j$ is the last element in the Fin (2 * n), the sum up to $j$ is the same as the sum up to $2n-1$.
          have h_sum_eq : ∑ x : Fin (2 * n), (if x < j then bin_masses f n x else 0) = ∑ x : Fin (2 * n), (if x < 2 * n - 1 then bin_masses f n x else 0) := by
            congr! 2;
            exact ⟨ fun h => lt_of_lt_of_le h ( Nat.le_of_not_lt fun h' => by omega ), fun h => Nat.lt_of_lt_of_le h ( Nat.le_of_not_lt fun h' => by omega ) ⟩;
          rw [ h_sum_eq ];
          unfold discrete_cum_global; norm_num [ sum_bin_masses_eq_one n hn f hf_supp hf_int ] ;
          unfold cumulative_mass; norm_num [ Finset.sum_ite ] ;
        · omega);
    -- Let's simplify the sum by separating the terms where $j.val < 2 * n - 1$ and $j.val = 2 * n - 1$.
    have h_sum_split : ∑ j : Fin (2 * n), (if a ≤ j.val ∧ j.val ≤ b then c j else 0) = ∑ j ∈ Finset.Ico a (2 * n - 1), (discrete_cum_global f n m (j + 1) - discrete_cum_global f n m j) + (if a ≤ 2 * n - 1 ∧ 2 * n - 1 ≤ b then m - discrete_cum_global f n m (2 * n - 1) else 0) := by
      have h_sum_split : ∑ j : Fin (2 * n), (if a ≤ j.val ∧ j.val ≤ b then c j else 0) = ∑ j ∈ Finset.filter (fun j => a ≤ j ∧ j < 2 * n - 1) (Finset.range (2 * n)), (discrete_cum_global f n m (j + 1) - discrete_cum_global f n m j) + ∑ j ∈ Finset.filter (fun j => a ≤ j ∧ j = 2 * n - 1) (Finset.range (2 * n)), (m - discrete_cum_global f n m (2 * n - 1)) := by
        simp +decide only [Finset.sum_filter, Finset.sum_range];
        rw [ ← Finset.sum_add_distrib ];
        grind;
      convert h_sum_split using 2;
      · rcongr j ; simp +decide [ Nat.lt_succ_iff ];
        exact fun _ _ => lt_of_lt_of_le ‹_› ( Nat.sub_le _ _ );
      · rw [ Finset.sum_eq_single ( 2 * n - 1 ) ] <;> norm_num;
        · exact fun h => absurd ( h ( by omega ) ) ( by omega );
        · tauto;
        · exact fun h => absurd ( h hn ) ( by omega );
    -- The sum of differences telescopes to $D(2n-1) - D(a)$.
    have h_telescope : ∑ j ∈ Finset.Ico a (2 * n - 1), (discrete_cum_global f n m (j + 1) - discrete_cum_global f n m j) = discrete_cum_global f n m (2 * n - 1) - discrete_cum_global f n m a := by
      have h_telescope : ∀ {a b : ℕ}, a ≤ b → b < 2 * n → ∑ j ∈ Finset.Ico a b, (discrete_cum_global f n m (j + 1) - discrete_cum_global f n m j) = discrete_cum_global f n m b - discrete_cum_global f n m a := by
        intros a b hab hb; induction hab <;> simp_all +decide [ Finset.sum_Ico_succ_top ] ;
        rename_i k hk₁ hk₂;
        rw [ hk₂ ( by linarith ), tsub_add_eq_add_tsub ];
        · rw [ Nat.add_sub_of_le ];
          unfold discrete_cum_global;
          rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ), Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ) ];
          gcongr;
          unfold cumulative_mass; simp +decide [ Finset.sum_ite ] ;
          exact Finset.sum_le_sum_of_subset_of_nonneg ( fun x hx => by exact Finset.mem_filter.mpr ⟨ Finset.mem_univ _, by linarith [ Finset.mem_filter.mp hx ] ⟩ ) fun _ _ _ => bin_masses_nonneg n f hf_nonneg _;
        · unfold discrete_cum_global;
          rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg <| Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n a hf_nonneg ) <| Nat.cast_nonneg _, Int.natAbs_of_nonneg <| Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ];
          gcongr;
          refine' Finset.sum_le_sum fun i hi => _;
          split_ifs <;> norm_num;
          · linarith;
          · exact bin_masses_nonneg n f hf_nonneg i;
      exact h_telescope ( by omega ) ( by omega );
    split_ifs at * <;> try omega;
    rw [ h_sum_split, h_telescope, tsub_add_eq_add_tsub ];
    · rw [ Nat.add_sub_of_le ];
      unfold discrete_cum_global;
      -- Since the cumulative mass is the sum of the bin masses up to 2n-1, and the total integral of f is 1, the cumulative mass is less than or equal to 1.
      have h_cumulative_mass_le_one : cumulative_mass f n (2 * n - 1) ≤ 1 := by
        have h_cumulative_mass_le_one : ∑ j : Fin (2 * n), bin_masses f n j = 1 := by
          exact?;
        refine' le_trans _ h_cumulative_mass_le_one.le;
        refine' le_trans ( Finset.sum_le_sum fun i hi => _ ) _;
        use fun i => bin_masses f n i;
        · split_ifs <;> norm_num;
          exact bin_masses_nonneg n f hf_nonneg i;
        · norm_num;
      rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ) ] ; exact Int.le_of_lt_add_one <| Int.floor_lt.mpr <| by norm_num; nlinarith [ show ( m : ℝ ) ≥ 1 by exact_mod_cast hm ] ;
    · -- By definition of $discrete_cum_global$, we know that it is non-decreasing.
      have h_discrete_cum_nonneg : ∀ k l : ℕ, k ≤ l → discrete_cum_global f n m k ≤ discrete_cum_global f n m l := by
        intros k l hkl
        unfold discrete_cum_global;
        rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n k hf_nonneg ) <| Nat.cast_nonneg _ ), Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( cumulative_mass_nonneg f n l hf_nonneg ) <| Nat.cast_nonneg _ ) ];
        gcongr;
        exact Finset.sum_le_sum fun i _ => by split_ifs <;> linarith [ show 0 ≤ bin_masses f n i from bin_masses_nonneg n f hf_nonneg i ] ;
      exact h_discrete_cum_nonneg _ _ ( by omega )

lemma discrete_cum_global_mono (f : ℝ → ℝ) (n m : ℕ) (hf_nonneg : ∀ x, 0 ≤ f x) :
    Monotone (discrete_cum_global f n m) := by
  -- The cumulative mass function is non-decreasing because each step adds a non-negative bin mass.
  have h_cumulative_mass_nonneg : Monotone (cumulative_mass f n) := by
    -- Since the bin masses are non-negative, adding more terms to the sum can't decrease the total. Therefore, the cumulative mass function is monotone.
    intros k l hkl
    simp [cumulative_mass, hkl];
    -- Since $k \leq l$, the set of indices where $j < k$ is a subset of the set where $j < l$. Therefore, the sum over the smaller set is less than or equal to the sum over the larger set.
    apply Finset.sum_le_sum; intro j _; split_ifs <;> norm_num ; linarith [hkl];
    exact?
  generalize_proofs at *; (
  intro k l hkl; simp [discrete_cum_global, h_cumulative_mass_nonneg hkl];
  rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( show 0 ≤ cumulative_mass f n k from ?_ ) <| Nat.cast_nonneg m ), Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( show 0 ≤ cumulative_mass f n l from ?_ ) <| Nat.cast_nonneg m ) ] ; exact Int.floor_mono <| mul_le_mul_of_nonneg_right ( h_cumulative_mass_nonneg hkl ) <| Nat.cast_nonneg m ; all_goals exact cumulative_mass_nonneg f n _ hf_nonneg;)

noncomputable def epsilon_error (f : ℝ → ℝ) (n m : ℕ) (i : ℕ) : ℝ :=
  (discrete_cum_global f n m i : ℝ) / m - cumulative_mass f n i

lemma c_sub_mu_eq_epsilon_diff (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (i : Fin (2 * n)) :
    (c i : ℝ) / m - bin_masses f n i =
      if i.1 < 2 * n - 1 then
        epsilon_error f n m (i.1 + 1) - epsilon_error f n m i.1
      else
        - epsilon_error f n m i.1 := by
  split_ifs <;> simp_all +decide [ epsilon_error ];
  · rw [ ← hc ];
    unfold canonical_discretization ; ring;
    rw [ if_pos ];
    · rw [ Nat.cast_sub ] <;> norm_num [ discrete_cum_global, cumulative_mass ] ; ring;
      · rw [ show ( ∑ j : Fin ( 2 * n ), bin_masses f n j ) = 1 from ?_ ] ; ring;
        · rw [ show ( ∑ x : Fin ( 2 * n ), if ( x : ℕ ) < 1 + ( i : ℕ ) then bin_masses f n x else 0 ) = ( ∑ x : Fin ( 2 * n ), if x < i then bin_masses f n x else 0 ) + bin_masses f n i from ?_ ] ; ring;
          rw [ Finset.sum_eq_sum_diff_singleton_add ( Finset.mem_univ i ) ] ; simp +decide [ add_comm, Finset.sum_ite ] ; ring;
          refine' Finset.sum_bij ( fun x hx => x ) _ _ _ _ <;> simp_all +decide [ Fin.ext_iff ];
          · exact fun a ha₁ ha₂ => lt_of_le_of_ne ( Nat.le_of_lt_succ <| by linarith ) ( by simpa [ Fin.ext_iff ] using ha₁ ) ;
          · exact fun b hb => ⟨ b, ⟨ ne_of_lt hb, by linarith [ show ( b : ℕ ) < i from hb ] ⟩, rfl ⟩;
        · convert sum_bin_masses_eq_one n hn f ( show Function.support f ⊆ Set.Ioo ( -1 / 4 ) ( 1 / 4 ) from fun x hx => ⟨ by linarith [ hf_supp x hx ], by linarith [ hf_supp x hx ] ⟩ ) hf_int using 1;
      · rw [ show ( ∑ x : Fin ( 2 * n ), if ( x : ℕ ) < 1 + ( i : ℕ ) then bin_masses f n x else 0 ) = ( ∑ x : Fin ( 2 * n ), if x < i then bin_masses f n x else 0 ) + bin_masses f n i from ?_ ] ; ring_nf ;
        · rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg, Int.natAbs_of_nonneg ] <;> norm_num [ Int.floor_nonneg ];
          · exact Int.floor_mono <| le_add_of_nonneg_right <| mul_nonneg ( mul_nonneg ( inv_nonneg.2 <| Finset.sum_nonneg fun _ _ => bin_masses_nonneg n f hf_nonneg _ ) <| Nat.cast_nonneg _ ) <| bin_masses_nonneg n f hf_nonneg _;
          · refine' add_nonneg _ _ <;> refine' mul_nonneg _ _;
            · exact mul_nonneg ( inv_nonneg.2 ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg n f hf_nonneg _ ) ) ( Nat.cast_nonneg _ );
            · exact Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact bin_masses_nonneg n f hf_nonneg _ ; exact le_rfl ] ;
            · exact mul_nonneg ( inv_nonneg.2 ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg n f hf_nonneg _ ) ) ( Nat.cast_nonneg _ );
            · exact?;
          · exact mul_nonneg ( mul_nonneg ( inv_nonneg.2 ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg n f hf_nonneg _ ) ) ( Nat.cast_nonneg _ ) ) ( Finset.sum_nonneg fun _ _ => by split_ifs <;> linarith [ bin_masses_nonneg n f hf_nonneg ‹_› ] );
        · rw [ Finset.sum_eq_sum_diff_singleton_add ( Finset.mem_univ i ) ] ; simp +decide [ add_comm, Finset.sum_ite ] ; ring;
          refine' Finset.sum_bij ( fun x hx => x ) _ _ _ _ <;> simp_all +decide [ Fin.ext_iff ];
          · exact fun a ha₁ ha₂ => lt_of_le_of_ne ( Nat.le_of_lt_succ <| by linarith ) ( by simpa [ Fin.ext_iff ] using ha₁ ) ;
          · exact fun b hb => ⟨ b, ⟨ ne_of_lt hb, by linarith [ show ( b : ℕ ) < i from hb ] ⟩, rfl ⟩;
    · omega;
  · -- By definition of $c$, we know that $c i = m - discrete_cum_global f n m (2 * n - 1)$.
    have h_ci : c i = m - discrete_cum_global f n m (2 * n - 1) := by
      rw [ ← hc ];
      unfold canonical_discretization;
      norm_num [ show ( i : ℕ ) = 2 * n - 1 by omega ];
      rw [ if_neg ( by omega ) ];
      unfold discrete_cum_global; norm_num [ cumulative_mass ] ;
      rw [ show ( ∑ j : Fin ( 2 * n ), bin_masses f n j ) = 1 from ?_ ] ; norm_num;
      convert sum_bin_masses_eq_one n hn f _ _ ; aesop;
      exact hf_int;
    -- Substitute the definition of `cumulative_mass` into the equation.
    have h_cumulative_mass : cumulative_mass f n i = 1 - bin_masses f n i := by
      have h_cumulative_mass : ∑ j : Fin (2 * n), bin_masses f n j = 1 := by
        convert sum_bin_masses_eq_one n hn f ( show Function.support f ⊆ Set.Ioo ( -1 / 4 ) ( 1 / 4 ) from fun x hx => ⟨ by linarith [ hf_supp x hx ], by linarith [ hf_supp x hx ] ⟩ ) hf_int using 1;
      rw [ ← h_cumulative_mass, show cumulative_mass f n ( i : ℕ ) = ∑ j : Fin ( 2 * n ), if j.1 < i.val then bin_masses f n j else 0 from rfl, Finset.sum_ite ];
      rw [ show ( Finset.univ.filter fun x : Fin ( 2 * n ) => ( x : ℕ ) < i ) = Finset.univ.erase i from ?_, Finset.sum_erase_eq_sub ] <;> norm_num [ Fin.ext_iff ];
      grind;
    rw [ h_ci, Nat.cast_sub ] <;> norm_num [ h_cumulative_mass, hm.ne' ] ; ring; (
    rw [ mul_inv_cancel₀ ( by positivity ) ] ; rw [ show ( i : ℕ ) = 2 * n - 1 by omega ] ; ring;);
    unfold discrete_cum_global;
    -- Since the cumulative mass is the sum of the bin masses up to 2n-1, and the total integral of f is 1, the sum of all bin masses should be 1. Therefore, cumulative_mass f n (2 * n - 1) is at most 1.
    have h_cumulative_mass_le_one : cumulative_mass f n (2 * n - 1) ≤ 1 := by
      have h_cumulative_mass_le_one : ∑ j : Fin (2 * n), bin_masses f n j = 1 := by
        convert sum_bin_masses_eq_one n hn f ( show Function.support f ⊆ Set.Ioo ( -1 / 4 ) ( 1 / 4 ) from fun x hx => ⟨ by linarith [ hf_supp x hx ], by linarith [ hf_supp x hx ] ⟩ ) hf_int using 1;
      refine' h_cumulative_mass_le_one ▸ Finset.sum_le_sum fun j _ => _;
      split_ifs <;> norm_num [ bin_masses_nonneg n f hf_nonneg j ];
    rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr <| mul_nonneg ( show 0 ≤ cumulative_mass f n ( 2 * n - 1 ) from cumulative_mass_nonneg f n _ hf_nonneg ) <| Nat.cast_nonneg _ ) ] ; exact Int.le_of_lt_add_one <| Int.floor_lt.mpr <| by norm_num; nlinarith [ show ( m : ℝ ) ≥ 1 by norm_cast ] ;

lemma epsilon_error_bound (n m : ℕ) (hm : m > 0) (f : ℝ → ℝ) (i : ℕ)
    (hf_nonneg : ∀ x, 0 ≤ f x) :
    |epsilon_error f n m i| < 1 / m := by
  -- By definition of epsilon_error, we have |epsilon_error f n m i| = |(discrete_cum_global f n m i : ℝ) / m - cumulative_mass f n i|.
  have h_eps_def : |epsilon_error f n m i| = |(discrete_cum_global f n m i : ℝ) - cumulative_mass f n i * m| / m := by
    unfold epsilon_error;
    rw [ div_sub', abs_div, abs_of_nonneg ( by positivity : ( 0 : ℝ ) ≤ m ) ] ; ring_nf ; norm_num [ hm.ne' ] ;
  -- By definition of discrete_cum_global, we know that |(discrete_cum_global f n m i : ℝ) - cumulative_mass f n i * m| < 1.
  have h_discrete_cum_global : |(discrete_cum_global f n m i : ℝ) - cumulative_mass f n i * m| < 1 := by
    -- Apply the hypothesis that |(discrete_cum_global f n m i : ℝ) - cumulative_mass f n i * m| < 1.
    apply discrete_cum_error f n m i hf_nonneg;
  -- By combining the results from h_eps_def and h_discrete_cum_global, we can conclude the proof.
  rw [h_eps_def]
  exact div_lt_div_iff_of_pos_right (by positivity) |>.2 h_discrete_cum_global

lemma sum_c_sub_mu_eq (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (a b : ℕ) (hab : a ≤ b) (hb : b < 2 * n) :
    ∑ j : Fin (2 * n), (if a ≤ j.1 ∧ j.1 ≤ b then (c j : ℝ) / m - bin_masses f n j else 0) =
      if b < 2 * n - 1 then
        epsilon_error f n m (b + 1) - epsilon_error f n m a
      else
        - epsilon_error f n m a := by
  have h_telescope : ∀ (i : Fin (2 * n)), (c i : ℝ) / m - bin_masses f n i = if i.1 < 2 * n - 1 then epsilon_error f n m (i.1 + 1) - epsilon_error f n m i.1 else -epsilon_error f n m i.1 := by
    exact?;
  have h_telescope_sum : ∀ (a b : ℕ) (hab : a ≤ b) (hb : b < 2 * n), ∑ i ∈ Finset.Icc a b, (if i < 2 * n - 1 then epsilon_error f n m (i + 1) - epsilon_error f n m i else -epsilon_error f n m i) = if b < 2 * n - 1 then epsilon_error f n m (b + 1) - epsilon_error f n m a else -epsilon_error f n m a := by
    intros a b hab hb
    induction' hab with b hb ih;
    · norm_num;
    · erw [ Finset.sum_Ico_succ_top ( by linarith [ Nat.succ_le_succ ‹a.le b› ] ), ih ( by linarith ) ];
      grind;
  convert h_telescope_sum a b hab hb using 1;
  rw [ ← Finset.sum_filter ];
  refine' Finset.sum_bij ( fun i hi => i ) _ _ _ _ <;> simp +decide [ Finset.mem_filter, Finset.mem_Icc ];
  · exact fun i hi₁ hi₂ j hj₁ hj₂ hij => Fin.ext hij;
  · exact fun x hx₁ hx₂ => ⟨ ⟨ x, by linarith ⟩, ⟨ hx₁, hx₂ ⟩, rfl ⟩;
  · exact fun i hi₁ hi₂ => h_telescope i

lemma sum_delta_bound (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (a b : ℕ) (hab : a ≤ b) (hb : b < 2 * n) :
    |∑ j : Fin (2 * n), (if a ≤ j.1 ∧ j.1 ≤ b then (c j : ℝ) / m - bin_masses f n j else 0)| < 2 / m := by
  rw [ sum_c_sub_mu_eq ];
  any_goals assumption;
  split_ifs;
  · have h_eps_bound : ∀ k : ℕ, |epsilon_error f n m k| < 1 / m := by
      exact?;
    exact lt_of_le_of_lt ( abs_sub _ _ ) ( by convert add_lt_add ( h_eps_bound ( b + 1 ) ) ( h_eps_bound a ) using 1 ; ring );
  · simpa [ abs_neg ] using lt_of_lt_of_le ( epsilon_error_bound n m hm f a hf_nonneg ) ( by gcongr ; linarith )

lemma sum_delta_bound' (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (a b : ℕ) (hab : a ≤ b) (hb : b < 2 * n) :
    |∑ j : Fin (2 * n), (if a ≤ j.1 ∧ j.1 ≤ b then (c j : ℝ) / m - bin_masses f n j else 0)| < 2 / m := by
  rw [ sum_c_sub_mu_eq ];
  any_goals assumption;
  split_ifs;
  · have h_eps_bound : ∀ k : ℕ, |epsilon_error f n m k| < 1 / m := by
      intro k; apply epsilon_error_bound n m hm f k hf_nonneg;
    exact lt_of_le_of_lt ( abs_sub _ _ ) ( by convert add_lt_add ( h_eps_bound ( b + 1 ) ) ( h_eps_bound a ) using 1 ; ring );
  · simpa [ abs_neg ] using lt_of_lt_of_le ( epsilon_error_bound n m hm f a hf_nonneg ) ( by gcongr ; linarith )

lemma sum_delta_bound_final (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (a b : ℕ) (hab : a ≤ b) (hb : b < 2 * n) :
    |∑ j : Fin (2 * n), (if a ≤ j.1 ∧ j.1 ≤ b then (c j : ℝ) / m - bin_masses f n j else 0)| < 2 / m := by
  rw [sum_c_sub_mu_eq n m hn hm f hf_supp hf_int hf_nonneg c hc a b hab hb]
  split_ifs
  · have h1 : |epsilon_error f n m (b + 1)| < 1 / m := epsilon_error_bound n m hm f (b + 1) hf_nonneg
    have h2 : |epsilon_error f n m a| < 1 / m := epsilon_error_bound n m hm f a hf_nonneg
    calc |epsilon_error f n m (b + 1) - epsilon_error f n m a|
      _ ≤ |epsilon_error f n m (b + 1)| + |epsilon_error f n m a| := abs_sub _ _
      _ < 1 / m + 1 / m := add_lt_add h1 h2
      _ = 2 / m := by field_simp; ring
  · have h : |epsilon_error f n m a| < 1 / m := epsilon_error_bound n m hm f a hf_nonneg
    calc |-epsilon_error f n m a|
      _ = |epsilon_error f n m a| := abs_neg _
      _ < 1 / m := h
      _ < 2 / m := by
        rw [div_lt_div_iff_of_pos_right (Nat.cast_pos.mpr hm)]
        norm_num

noncomputable def delta_c (f : ℝ → ℝ) (n m : ℕ) (c : Fin (2 * n) → ℕ) (i : Fin (2 * n)) : ℝ :=
  (c i : ℝ) / m - bin_masses f n i

lemma test_value_expansion (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) :
    test_value n m c ℓ s_lo =
      ideal_test_value f n ℓ s_lo +
      (1 / (4 * n * ℓ : ℝ)) * (
        ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2),
          ∑ i : Fin (2 * n), ∑ j : Fin (2 * n),
            if i.1 + j.1 = k then
              (4 * n : ℝ)^2 * (
                bin_masses f n i * delta_c f n m c j +
                delta_c f n m c i * bin_masses f n j +
                delta_c f n m c i * delta_c f n m c j
              )
            else 0
      ) := by
  unfold test_value ideal_test_value delta_c;
  -- By expanding the discrete_autoconvolution and simplifying, we can see that the sum of the discrete_autoconvolutions is equal to the ideal test value plus the sum of the other terms.
  have h_expand : ∀ k, discrete_autoconvolution (fun i => (4 * n : ℝ) / m * (c i : ℝ)) k = discrete_autoconvolution (fun i => (4 * n : ℝ) * bin_masses f n i) k + ∑ i : Fin (2 * n), ∑ j : Fin (2 * n), if i.1 + j.1 = k then (4 * n : ℝ) ^ 2 * ((bin_masses f n i) * ((c j : ℝ) / m - bin_masses f n j) + ((c i : ℝ) / m - bin_masses f n i) * bin_masses f n j + ((c i : ℝ) / m - bin_masses f n i) * ((c j : ℝ) / m - bin_masses f n j)) else 0 := by
    intro k; unfold discrete_autoconvolution; simp +decide [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_assoc, mul_comm, mul_left_comm, sq ] ; ring;
    simpa only [ ← Finset.sum_add_distrib ] using Finset.sum_congr rfl fun i hi => Finset.sum_congr rfl fun j hj => by split_ifs <;> ring;
  simp +decide only [mul_assoc, h_expand, mul_add, Finset.sum_add_distrib]

lemma epsilon_nonpos (f : ℝ → ℝ) (n m : ℕ) (i : ℕ) (hf_nonneg : ∀ x, 0 ≤ f x) :
    epsilon_error f n m i ≤ 0 := by
      -- Since the floor function is less than or equal to the original number, we have:
      have h_floor_le : (discrete_cum_global f n m i : ℝ) / m ≤ cumulative_mass f n i := by
        -- By definition of discrete_cum_global, we have:
        have h_discrete_cum_global : (discrete_cum_global f n m i : ℝ) = ⌊cumulative_mass f n i * m⌋ := by
          -- By definition of discrete_cum_global, we have that discrete_cum_global f n m i is equal to the floor of cumulative_mass f n i multiplied by m.
          simp [discrete_cum_global];
          exact Int.floor_nonneg.mpr ( mul_nonneg ( cumulative_mass_nonneg f n i hf_nonneg ) ( Nat.cast_nonneg _ ) );
        by_cases hm : m = 0 <;> simp_all +decide [ div_le_iff₀ ];
        · exact?;
        · exact div_le_iff₀ ( by positivity ) |>.2 ( Int.floor_le _ );
      -- By definition of epsilon_error, we have:
      simp [epsilon_error, h_floor_le]

lemma W_bound (n m : ℕ) (hn : n > 0) (hm : m > 0) (f : ℝ → ℝ)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (hf_nonneg : ∀ x, 0 ≤ f x)
    (c : Fin (2 * n) → ℕ) (hc : canonical_discretization f n m = c)
    (ℓ s_lo : ℕ) (hℓ : 2 ≤ ℓ)
    (W : ℝ) (hW : W = (∑ i ∈ contributing_bins n ℓ s_lo, (c i : ℝ)) / m) :
    ∑ i ∈ contributing_bins n ℓ s_lo, bin_masses f n i ≤ W + 1 / m := by
  -- By Lemma~\ref{lem:contributing_bins_iff}, $i \in \text{contributing\_bins} \iff a \le i \le b$.
  set a := Nat.max 0 (s_lo - (2 * n - 1))
  set b := Nat.min (2 * n - 1) (s_lo + ℓ - 2) with hb_def
  have h_cont : contributing_bins n ℓ s_lo = Finset.filter (fun i => a ≤ i.val ∧ i.val ≤ b) Finset.univ := by
    ext i; simp [a, b];
    convert contributing_bins_iff n hn ℓ s_lo hℓ i using 1 ; aesop;
  -- Let's split into cases based on whether $a \leq b$.
  by_cases h_cases : a ≤ b;
  · -- By `sum_delta_bound_final`, we have $|W - \sum_{i=a}^{b} \mu_i| < 1/m$.
    have h_bound : |W - ∑ i ∈ Finset.univ.filter (fun i => a ≤ i.val ∧ i.val ≤ b), bin_masses f n i| < 1 / (m : ℝ) := by
      have h_bound : |∑ i ∈ Finset.univ.filter (fun i => a ≤ i.val ∧ i.val ≤ b), (c i : ℝ) / m - ∑ i ∈ Finset.univ.filter (fun i => a ≤ i.val ∧ i.val ≤ b), bin_masses f n i| < 1 / (m : ℝ) := by
        have h_bound : |∑ i ∈ Finset.univ.filter (fun i => a ≤ i.val ∧ i.val ≤ b), (c i : ℝ) / m - ∑ i ∈ Finset.univ.filter (fun i => a ≤ i.val ∧ i.val ≤ b), bin_masses f n i| ≤ |epsilon_error f n m (b + 1) - epsilon_error f n m a| := by
          have h_bound : ∑ i ∈ Finset.univ.filter (fun i => a ≤ i.val ∧ i.val ≤ b), (c i : ℝ) / m - ∑ i ∈ Finset.univ.filter (fun i => a ≤ i.val ∧ i.val ≤ b), bin_masses f n i = if b < 2 * n - 1 then epsilon_error f n m (b + 1) - epsilon_error f n m a else -epsilon_error f n m a := by
            convert sum_c_sub_mu_eq n m hn hm f hf_supp hf_int hf_nonneg c hc a b h_cases _ using 1;
            · simp +decide [ Finset.sum_ite, Finset.filter_congr ];
            · exact lt_of_le_of_lt ( Nat.min_le_left _ _ ) ( Nat.sub_lt ( by positivity ) ( by positivity ) );
          split_ifs at h_bound <;> simp +decide [ h_bound ];
          rw [ show epsilon_error f n m ( b + 1 ) = 0 from _ ] ; norm_num [ abs_neg ];
          unfold epsilon_error; norm_num [ show b = 2 * n - 1 from le_antisymm ( Nat.min_le_left _ _ ) ( not_lt.mp ‹_› ) ] ;
          rw [ show 2 * n - 1 + 1 = 2 * n from Nat.succ_pred_eq_of_pos ( Nat.mul_pos zero_lt_two hn ) ] ; norm_num [ cumulative_mass, discrete_cum_global ] ; ring;
          rw [ show ( ∑ x : Fin ( 2 * n ), bin_masses f n x ) = 1 by exact sum_bin_masses_eq_one n hn f hf_supp hf_int ] ; norm_num [ hm.ne' ];
        have h_bound : |epsilon_error f n m (b + 1)| < 1 / (m : ℝ) ∧ |epsilon_error f n m a| < 1 / (m : ℝ) := by
          exact ⟨ epsilon_error_bound n m hm f ( b + 1 ) hf_nonneg, epsilon_error_bound n m hm f a hf_nonneg ⟩;
        have h_bound : epsilon_error f n m (b + 1) ≤ 0 ∧ epsilon_error f n m a ≤ 0 := by
          exact ⟨ epsilon_nonpos f n m _ hf_nonneg, epsilon_nonpos f n m _ hf_nonneg ⟩;
        cases abs_cases ( epsilon_error f n m ( b + 1 ) - epsilon_error f n m a ) <;> cases abs_cases ( epsilon_error f n m ( b + 1 ) ) <;> cases abs_cases ( epsilon_error f n m a ) <;> linarith [ show ( 0 : ℝ ) ≤ 1 / m by positivity ] ;
      simp_all +decide [ Finset.sum_div _ _ _ ];
    rw [ h_cont ] ; linarith [ abs_lt.mp h_bound ] ;
  · rw [ h_cont, Finset.sum_eq_zero ];
    · exact add_nonneg ( hW.symm ▸ div_nonneg ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( by positivity );
    · grind