/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f31f701e-b753-4d60-9887-3983b48cee92

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We proved the asymmetry bound for the autoconvolution of a non-negative function $f$ supported on $[-1/4, 1/4]$ with integral 1.
Specifically, we showed that $\|f*f\|_\infty \geq 2L^2$, where $L = \int_{-1/4}^0 f$.
The proof involves restricting $f$ to the left half $f_L$, observing that $f*f \ge f_L * f_L$, and using an averaging principle on the support of $f_L * f_L$, which has measure $1/2$.
We added an assumption that the convolution has finite $L^\infty$ norm to make the statement with `toReal` valid.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def f_L (f : ℝ → ℝ) : ℝ → ℝ := Set.indicator (Set.Ioo (-1/4 : ℝ) 0) f

theorem f_L_le_f (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x) :
    ∀ x, f_L f x ≤ f x := by
  -- By definition of $f_L$, we know that $f_L f x = f x$ if $x \in (-1/4, 0)$ and $f_L f x = 0$ otherwise.
  intros x
  simp [f_L];
  -- By definition of the indicator function, we have two cases: $x \in (-1/4, 0)$ or $x \notin (-1/4, 0)$.
  by_cases hx : x ∈ Set.Ioo (-1 / 4 : ℝ) 0 <;> simp [hx, hf]

theorem f_L_supp (f : ℝ → ℝ) :
    Function.support (f_L f) ⊆ Set.Ioo (-1/4 : ℝ) 0 := by
  -- By definition of $f_L$, we know that $f_L(x) = 0$ for $x \notin (-1/4, 0)$.
  simp [f_L]

theorem f_L_conv_supp (f : ℝ → ℝ) :
    Function.support (MeasureTheory.convolution (f_L f) (f_L f) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆
    Set.Ioo (-1/2 : ℝ) 0 := by
  intro x hx; simp_all +decide [ MeasureTheory.convolution ] ;
  -- By definition of $f_L$, we know that $f_L f t = 0$ outside the interval $(-1/4, 0)$.
  have h_support : ∀ t, f_L f t ≠ 0 → -1 / 4 < t ∧ t < 0 := by
    unfold f_L; aesop;
  contrapose! hx;
  rw [ MeasureTheory.integral_eq_zero_of_ae ];
  filter_upwards [ ] with t ; by_cases ht : f_L f t = 0 <;> by_cases ht' : f_L f ( x - t ) = 0 <;> simp_all +decide [ sub_eq_add_neg ];
  linarith [ h_support t ht, h_support ( x + -t ) ht', hx ( by linarith [ h_support t ht, h_support ( x + -t ) ht' ] ) ]

theorem convolution_mono_ae (f g : ℝ → ℝ)
    (hf : ∀ x, 0 ≤ f x) (hg : ∀ x, 0 ≤ g x) (hfg : ∀ x, f x ≤ g x)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    ∀ᵐ x ∂MeasureTheory.volume,
      MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤
      MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  -- Use `MeasureTheory.Integrable.ae_convolution_exists` to show that for a.e. `x`, the convolution integral for `g` exists.
  have h_convol_g_exists : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.Integrable (fun y => g y * g (x - y)) MeasureTheory.volume := by
    have h_ae_conv : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * g p.2) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
      exact MeasureTheory.Integrable.mul_prod hg_int hg_int;
    have h_ae_conv : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * g (p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
      have h_ae_conv : MeasureTheory.MeasurePreserving (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
        exact?;
      have h_ae_conv : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * g p.2) (MeasureTheory.Measure.map (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume)) := by
        rw [ h_ae_conv.map_eq ] ; assumption;
      rw [ MeasureTheory.integrable_map_measure ] at h_ae_conv ; aesop;
      · exact h_ae_conv.1;
      · exact AEMeasurable.prodMk ( measurable_fst.aemeasurable ) ( measurable_snd.sub measurable_fst |> Measurable.aemeasurable );
    rw [ MeasureTheory.integrable_prod_iff' ] at h_ae_conv ; aesop;
    exact h_ae_conv.1;
  filter_upwards [ h_convol_g_exists ] with x hx;
  refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
  · exact Filter.Eventually.of_forall fun y => mul_nonneg ( hf _ ) ( hf _ );
  · exact hx;
  · filter_upwards [ ] with t using mul_le_mul ( hfg t ) ( hfg ( x - t ) ) ( hf _ ) ( hg _ )

theorem averaging_principle (g : ℝ → ℝ) (hg : ∀ x, 0 ≤ g x)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume)
    (S : Set ℝ) (hS : Function.support g ⊆ S)
    (v : ℝ) (hS_meas : MeasureTheory.volume S = ENNReal.ofReal v)
    (hv : 0 < v) :
    MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume ≥
      ENNReal.ofReal (MeasureTheory.integral MeasureTheory.volume g / v) := by
  -- Since $g$ is zero outside $S$, we can restrict the integral to $S$.
  have h_integral_restrict : ∫ x, g x ∂MeasureTheory.volume = ∫ x in S, g x ∂MeasureTheory.volume := by
    rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero fun x hx => by_contra fun hx' => hx <| hS <| by aesop ];
  have h_integral_bound : (∫⁻ x in S, ENNReal.ofReal (g x) ∂MeasureTheory.volume) ≤ (MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume) * (MeasureTheory.MeasureSpace.volume S) := by
    have h_integral_bound : ∀ᵐ x ∂MeasureTheory.Measure.restrict MeasureTheory.volume S, ENNReal.ofReal (g x) ≤ MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume := by
      have h_integral_bound : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, ENNReal.ofReal (g x) ≤ MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume := by
        have h_integral_bound : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, ‖g x‖ₑ ≤ essSup (fun x => ‖g x‖ₑ) MeasureTheory.MeasureSpace.volume := by
          exact?;
        filter_upwards [ h_integral_bound ] with x hx using le_trans ( by simp +decide [ Real.enorm_eq_ofReal ( hg x ) ] ) hx;
      exact MeasureTheory.ae_restrict_of_ae h_integral_bound;
    refine' le_trans ( MeasureTheory.lintegral_mono_ae h_integral_bound ) _ ; aesop;
  simp_all +decide [ ENNReal.ofReal_div_of_pos hv ];
  rw [ ENNReal.div_le_iff_le_mul ] <;> norm_num [ hv ];
  refine' le_trans _ h_integral_bound;
  rw [ MeasureTheory.ofReal_integral_eq_lintegral_ofReal ];
  · exact hg_int.integrableOn;
  · exact Filter.Eventually.of_forall hg

theorem integral_convolution_square (f : ℝ → ℝ)
    (hf : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.integral MeasureTheory.volume (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) =
    (MeasureTheory.integral MeasureTheory.volume f) ^ 2 := by
  rw [ sq ];
  -- Apply the convolution theorem which states that the integral of the convolution of two functions is the product of their integrals.
  apply MeasureTheory.integral_convolution;
  · exact hf;
  · exact hf

theorem f_L_integrable (f : ℝ → ℝ) (hf : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.Integrable (f_L f) MeasureTheory.volume := by
  convert hf.indicator measurableSet_Ioo using 1

theorem convolution_nonneg {f g : ℝ → ℝ} (hf : ∀ x, 0 ≤ f x) (hg : ∀ x, 0 ≤ g x) :
    ∀ x, 0 ≤ MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  intro x
  simp [MeasureTheory.convolution];
  exact MeasureTheory.integral_nonneg fun t => mul_nonneg ( hf t ) ( hg ( x - t ) )

theorem f_L_nonneg (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x) :
    ∀ x, 0 ≤ f_L f x := by
  exact fun x => Set.indicator_nonneg ( fun _ _ => hf _ ) _

theorem f_L_conv_integrable (f : ℝ → ℝ) (hf : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.Integrable (MeasureTheory.convolution (f_L f) (f_L f) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) MeasureTheory.volume := by
  have h_conv_integrable : MeasureTheory.Integrable (f_L f) MeasureTheory.volume := by
    exact?;
  exact?

theorem volume_Ioo_half :
    MeasureTheory.volume (Set.Ioo (-1/2 : ℝ) 0) = ENNReal.ofReal (1/2) := by
  norm_num

theorem f_L_conv_bound (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume) :
    let L := MeasureTheory.integral MeasureTheory.volume (f_L f)
    MeasureTheory.eLpNorm (MeasureTheory.convolution (f_L f) (f_L f)
      (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≥ ENNReal.ofReal (2 * L ^ 2) := by
        -- Let's denote g as the convolution of f_L with itself.
        set g := MeasureTheory.convolution (f_L f) (f_L f) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume;
        -- By the averaging principle, since g is non-negative and integrable with support in (-1/2, 0), we have:
        have h_avg : MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume ≥ ENNReal.ofReal (MeasureTheory.integral MeasureTheory.volume g / (1 / 2)) := by
          apply_rules [ averaging_principle, g ];
          any_goals exact Set.Ioo ( -1 / 2 ) 0;
          · apply convolution_nonneg; exact f_L_nonneg f hf_nonneg; exact f_L_nonneg f hf_nonneg;
          · exact?;
          · convert f_L_conv_supp f using 1;
          · norm_num;
          · norm_num;
        convert h_avg using 1;
        rw [ integral_convolution_square ] ; ring;
        exact?

theorem asymmetry_bound (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Icc (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (h_bdd : MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≠ ⊤) :
    let L := MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ioo (-1/4 : ℝ) 0) f)
    (MeasureTheory.eLpNorm (MeasureTheory.convolution f f
      (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥ 2 * L ^ 2 := by
        -- Apply the convolution_mono_ae theorem to get the inequality between the convolutions.
        have h_conv_mono : MeasureTheory.eLpNorm (MeasureTheory.convolution (f_L f) (f_L f) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≤ MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume := by
          -- Apply the convolution_mono_ae theorem to get the inequality between the convolutions. We need to show that $f_L * f_L \leq f * f$ almost everywhere.
          have h_conv_mono : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.convolution (f_L f) (f_L f) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤ MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
            apply convolution_mono_ae (f_L f) f (fun x => f_L_nonneg f hf_nonneg x) hf_nonneg (fun x => f_L_le_f f hf_nonneg x) (f_L_integrable f (by
            exact MeasureTheory.integrable_of_integral_eq_one hf_int)) (by
            exact MeasureTheory.integrable_of_integral_eq_one hf_int);
          apply_rules [ MeasureTheory.eLpNorm_mono_ae ];
          filter_upwards [ h_conv_mono ] with x hx using by rw [ Real.norm_of_nonneg ( convolution_nonneg ( f_L_nonneg f hf_nonneg ) ( f_L_nonneg f hf_nonneg ) x ), Real.norm_of_nonneg ( convolution_nonneg hf_nonneg hf_nonneg x ) ] ; exact hx;
        refine' le_trans _ ( ENNReal.toReal_mono _ h_conv_mono );
        · convert ENNReal.toReal_mono _ ( f_L_conv_bound f hf_nonneg <| ?_ ) using 1 <;> norm_num [ * ];
          · unfold f_L; norm_num [ ENNReal.toReal_ofReal ( sq_nonneg _ ) ] ;
          · exact ne_of_lt ( lt_of_le_of_lt h_conv_mono ( lt_top_iff_ne_top.mpr h_bdd ) );
          · exact MeasureTheory.integrable_of_integral_eq_one hf_int;
        · assumption