/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 31103b4c-cf4c-4f19-abf6-fe75cd7e9ee4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We prove combinatorial completeness claims for the branch-and-prune cascade.
Claim 3.1: The number of compositions of m into d parts is (m+d-1) choose (d-1).
Claim 3.2a: The number of choices for a bin c_i with capacity x_cap is min(c_i, x_cap) - max(0, c_i - x_cap) + 1.
Claim 3.2c: Children preserve total mass.
Claim 3.2d: Child bins sum to parent bin.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The number of compositions of $m$ into $d$ nonneg integer parts is $\binom{m+d-1}{d-1}$.
-/
theorem composition_count (m d : ℕ) (hd : d > 0) :
    Finset.card (Finset.filter (fun c : Fin d → Fin (m + 1) =>
      ∑ i, (c i : ℕ) = m) Finset.univ) = Nat.choose (m + d - 1) (d - 1) := by
  have h_stars_and_bars : ∀ m d : ℕ, d > 0 → Finset.card (Finset.filter (fun (c : Fin d → ℕ) => (∑ i, c i) = m) (Finset.Iic (fun _ => m))) = Nat.choose (m + d - 1) (d - 1) := by
    intro m d hd
    induction' d with d ih generalizing m;
    · contradiction;
    · -- We can split the sum into the sum over the first element and the sum over the remaining elements.
      have h_split : Finset.filter (fun (c : Fin (d + 1) → ℕ) => (∑ i, c i) = m) (Finset.Iic (fun _ => m)) = Finset.biUnion (Finset.range (m + 1)) (fun k => Finset.image (fun (c : Fin d → ℕ) => Fin.cons k c) (Finset.filter (fun (c : Fin d → ℕ) => (∑ i, c i) = m - k) (Finset.Iic (fun _ => m - k)))) := by
        ext c; simp [Finset.mem_biUnion, Finset.mem_image];
        constructor <;> intro h;
        · refine' ⟨ c 0, _, Fin.tail c, _, _ ⟩ <;> simp_all +decide [ Fin.sum_univ_succ ];
          · linarith [ h.1 0, Nat.zero_le ( ∑ i : Fin d, c i.succ ) ];
          · exact ⟨ fun i => Nat.le_sub_of_add_le <| by linarith! [ h.1 i.succ, Finset.single_le_sum ( fun a _ => Nat.zero_le ( c ( Fin.succ a ) ) ) ( Finset.mem_univ i ) ], eq_tsub_of_add_eq <| by linarith! ⟩;
        · rcases h with ⟨ a, ha, b, ⟨ hb₁, hb₂ ⟩, rfl ⟩ ; simp_all +decide [ Fin.sum_univ_succ ];
          exact ⟨ fun i => by cases i using Fin.inductionOn <;> [ exact Nat.le_of_lt_succ ha; exact le_trans ( hb₁ _ ) ( Nat.sub_le _ _ ) ], Nat.add_sub_of_le ( Nat.le_of_lt_succ ha ) ⟩;
      rw [ h_split, Finset.card_biUnion ];
      · rcases d with ( _ | d ) <;> simp_all +decide [ Finset.card_image_of_injective, Function.Injective ];
        · rw [ Finset.sum_eq_single m ] <;> simp +decide [ Finset.card_range ];
          intros; omega;
        · exact Nat.recOn m ( by simp +arith +decide ) fun n ih => by simp +arith +decide [ Nat.choose, Finset.sum_range_succ' ] at * ; linarith;
      · intro k hk l hl hkl; simp_all +decide [ Finset.disjoint_left ] ;
        intro a x hx₁ hx₂ hx₃ y hy₁ hy₂ hy₃; contrapose! hkl; aesop;
  convert h_stars_and_bars m d hd using 1;
  refine' Finset.card_bij ( fun c hc => fun i => c i ) _ _ _ <;> simp +decide [ funext_iff ];
  · exact fun a ha => ⟨ fun i => Nat.le_of_lt_succ <| Fin.is_lt _, ha ⟩;
  · exact fun a₁ ha₁ a₂ ha₂ h x => Fin.ext <| h x;
  · exact fun b hb hm => ⟨ fun i => ⟨ b i, Nat.lt_succ_of_le ( hb i ) ⟩, hm, fun i => rfl ⟩

/-
The number of choices for a bin $c_i$ with capacity $x_{cap}$ is $\min(c_i, x_{cap}) - \max(0, c_i - x_{cap}) + 1$, assuming $c_i \le 2 x_{cap}$.
-/
theorem per_bin_choices (c_i x_cap : ℕ) (h : c_i ≤ 2 * x_cap) :
    Finset.card (Finset.Icc (Nat.max 0 (c_i - x_cap)) (Nat.min c_i x_cap)) =
    Nat.min c_i x_cap - Nat.max 0 (c_i - x_cap) + 1 := by
  simp +zetaDelta at *;
  grind +ring

/-
If $\sum_{i=0}^{d-1} c_i = m$ (parent sums to $m$) and child is $(a_0, c_0-a_0, \ldots, a_{d-1}, c_{d-1}-a_{d-1})$ where $0 \leq a_i \leq c_i$, then $\sum_{j=0}^{2d-1} \text{child}_j = m$.
-/
theorem child_preserves_mass (d m : ℕ) (parent : Fin d → ℕ) (a : Fin d → ℕ)
    (hp : ∑ i, parent i = m) (ha : ∀ i, a i ≤ parent i)
    (child : Fin (2 * d) → ℕ)
    (hc_even : ∀ i : Fin d, child ⟨2 * i.1, by
      linarith [ Fin.is_lt i ]⟩ = a i)
    (hc_odd : ∀ i : Fin d, child ⟨2 * i.1 + 1, by
      linarith [ Fin.is_lt i ]⟩ = parent i - a i) :
    ∑ j, child j = m := by
  all_goals generalize_proofs at *;
  -- By definition of `child`, we can split the sum into sums over the even and odd indices.
  have h_split : ∑ j : Fin (2 * d), child j = ∑ i : Fin d, child ⟨2 * i, by
    exact?⟩ + ∑ i : Fin d, child ⟨2 * i + 1, by
    solve_by_elim⟩ := by
    have h_split : Finset.range (2 * d) = Finset.image (fun i => 2 * i) (Finset.range d) ∪ Finset.image (fun i => 2 * i + 1) (Finset.range d) := by
      ext i
      simp [Finset.mem_range, Finset.mem_image];
      exact ⟨ fun hi => by rcases Nat.even_or_odd' i with ⟨ k, rfl | rfl ⟩ <;> [ left; right ] <;> exact ⟨ k, by linarith, rfl ⟩, fun hi => by rcases hi with ( ⟨ k, hk, rfl ⟩ | ⟨ k, hk, rfl ⟩ ) <;> linarith ⟩;
    rw [ Finset.sum_fin_eq_sum_range ];
    rw [ h_split, Finset.sum_union ] <;> norm_num [ Finset.sum_range, Fin.cast_val_eq_self ];
    · exact Finset.sum_congr rfl fun i hi => by aesop;
    · norm_num [ Finset.disjoint_right ];
      intros; omega;
  generalize_proofs at *;
  simp_all +decide [ ← Finset.sum_add_distrib, Nat.sub_add_cancel ( ha _ ) ]

/-
Each parent bin's total mass is preserved in its two child bins.
-/
theorem child_bin_sum (d : ℕ) (parent : Fin d → ℕ) (a : Fin d → ℕ)
    (ha : ∀ i, a i ≤ parent i)
    (child : Fin (2 * d) → ℕ)
    (hc_even : ∀ i : Fin d, child ⟨2 * i.1, by
      grind⟩ = a i)
    (hc_odd : ∀ i : Fin d, child ⟨2 * i.1 + 1, by
      grind⟩ = parent i - a i)
    (i : Fin d) :
    child ⟨2 * i.1, by
      all_goals generalize_proofs at *;
      exact?⟩ + child ⟨2 * i.1 + 1, by
      all_goals generalize_proofs at *;
      solve_by_elim⟩ = parent i := by
  rw [ hc_even, hc_odd, add_tsub_cancel_of_le ( ha i ) ]