/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 5ae99659-51de-47f2-8af5-8b44e25ea651

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the autoconvolution ratio R(f) = ||f * f||_infty / (int f)^2.
-/
noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  let norm_inf := (MeasureTheory.eLpNorm conv ⊤ MeasureTheory.volume).toReal
  let integral := MeasureTheory.integral MeasureTheory.volume f
  norm_inf / (integral ^ 2)

/-
Definition of the autoconvolution constant c = inf { R(f) | f >= 0, supp(f) subset (-1/4, 1/4) }.
-/
noncomputable def autoconvolution_constant : ℝ :=
  sInf {r : ℝ | ∃ (f : ℝ → ℝ), (∀ x, 0 ≤ f x) ∧ (Function.support f ⊆ Set.Ioo (-1/4) (1/4)) ∧ r = autoconvolution_ratio f}

/-
Definition of the discrete autoconvolution array conv[k] = sum_{i+j=k} a_i a_j.
-/
def discrete_autoconvolution {d : ℕ} (a : Fin d → ℝ) (k : ℕ) : ℝ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then a i * a j else 0

/-
Definition of the test value TV(ell, s_lo).
-/
noncomputable def test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let a : Fin d → ℝ := fun i => (4 * n : ℝ) / m * (c i : ℝ)
  let conv := discrete_autoconvolution a
  let sum_conv := ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), conv k
  (1 / (4 * n * ℓ : ℝ)) * sum_conv

/-
Definition of the max test value b_{n,m}(c).
-/
noncomputable def max_test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) : ℝ :=
  let d := 2 * n
  let range_ell := Finset.Icc 2 (2 * d)
  let range_s_lo := Finset.range (2 * d) -- Sufficient range to cover the convolution
  let values := range_ell.biUnion (fun ℓ => range_s_lo.image (fun s_lo => test_value n m c ℓ s_lo))
  if h : values.Nonempty then values.max' h else 0

/-
Definition of a composition: a vector of bin masses summing to m.
-/
def is_composition (n m : ℕ) (c : Fin (2 * n) → ℕ) : Prop :=
  ∑ i, c i = m

/-
Helper definitions for the canonical discretization of f into m bins.
bin_masses computes the integral of f over each bin.
canonical_discretization computes integer bin counts summing to m using partial sum rounding (floor).
-/
noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

noncomputable def canonical_discretization (f : ℝ → ℝ) (n m : ℕ) : Fin (2 * n) → ℕ :=
  fun i =>
    let masses := bin_masses f n
    let total_mass := ∑ j, masses j
    let cum_mass (k : ℕ) := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
    let target_cum (k : ℕ) := (cum_mass k) / total_mass * m
    let discrete_cum (k : ℕ) := ⌊target_cum k⌋.natAbs
    if i.1 + 1 < 2 * n then discrete_cum (i.1 + 1) - discrete_cum i.1
    else m - discrete_cum i.1

/-
Definition of contributing bins B for a window (ell, s_lo).
-/
def contributing_bins (n : ℕ) (ℓ s_lo : ℕ) : Finset (Fin (2 * n)) :=
  let d := 2 * n
  Finset.filter (fun i => ∃ j : Fin d, s_lo ≤ i.1 + j.1 ∧ i.1 + j.1 ≤ s_lo + ℓ - 2) Finset.univ

/-
Helper definition for the cumulative distribution function used in canonical_discretization.
-/
noncomputable def canonical_cumulative_distribution (f : ℝ → ℝ) (n m : ℕ) (k : ℕ) : ℕ :=
  let masses := bin_masses f n
  let total_mass := ∑ j, masses j
  let cum_mass := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
  let target_cum := cum_mass / total_mass * m
  ⌊target_cum⌋.natAbs

/-
Rewrite canonical_discretization in terms of canonical_cumulative_distribution.
-/
theorem canonical_discretization_eq (f : ℝ → ℝ) (n m : ℕ) (i : Fin (2 * n)) :
    canonical_discretization f n m i =
    if i.1 + 1 < 2 * n then
      canonical_cumulative_distribution f n m (i.1 + 1) - canonical_cumulative_distribution f n m i.1
    else
      m - canonical_cumulative_distribution f n m i.1 := by
        unfold canonical_discretization canonical_cumulative_distribution;
        simp +zetaDelta at *

/-
Lemma: D(0) = 0.
Proof: The sum in the numerator is over j < 0, which is empty, so the sum is 0.
0 / total_mass * m = 0.
floor(0).natAbs = 0.
-/
theorem canonical_cumulative_distribution_zero (f : ℝ → ℝ) (n m : ℕ) :
    canonical_cumulative_distribution f n m 0 = 0 := by
      unfold canonical_cumulative_distribution; aesop;

/-
Lemma: D(2n) = m, provided total mass is non-zero.
Proof:
cum_mass(2n) = sum_{j < 2n} masses j = total_mass.
target_cum(2n) = total_mass / total_mass * m = 1 * m = m.
floor(m) = m.
natAbs(m) = m.
-/
theorem canonical_cumulative_distribution_2n (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_pos : ∑ j : Fin (2 * n), bin_masses f n j ≠ 0) :
    canonical_cumulative_distribution f n m (2 * n) = m := by
      unfold canonical_cumulative_distribution; aesop;

/-
If f is non-negative, then bin_masses are non-negative.
-/
theorem bin_masses_nonneg (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n : ℕ) (i : Fin (2 * n)) :
    0 ≤ bin_masses f n i := by
      apply_rules [ MeasureTheory.integral_nonneg, Set.indicator_nonneg ] ; aesop

theorem canonical_discretization_sum_zero_mass (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_zero : ∑ j : Fin (2 * n), bin_masses f n j = 0) :
    ∑ i : Fin (2 * n), canonical_discretization f n m i = m := by
      rw [ Finset.sum_eq_single ⟨ 2 * n - 1, Nat.sub_lt ( by positivity ) ( by positivity ) ⟩ ] <;> norm_num [ canonical_discretization ];
      · rw [ Nat.sub_add_cancel ( by linarith ) ] ; aesop;
      · simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg, bin_masses_nonneg ];
        exact fun i hi₁ hi₂ => False.elim <| hi₁ <| Fin.ext <| by linarith [ Fin.is_lt i, Nat.sub_add_cancel <| show 1 ≤ 2 * n from by linarith ] ;

theorem canonical_discretization_eq_diff (f : ℝ → ℝ) (n m : ℕ)
    (h_D_2n : canonical_cumulative_distribution f n m (2 * n) = m) (i : Fin (2 * n)) :
    canonical_discretization f n m i = canonical_cumulative_distribution f n m (i.1 + 1) - canonical_cumulative_distribution f n m i.1 := by
      convert canonical_discretization_eq f n m i using 1;
      grind

theorem sum_fin_telescope {M : Type*} [AddCommGroup M] (f : ℕ → M) (n : ℕ) :
    ∑ i : Fin n, (f (i + 1) - f i) = f n - f 0 := by
      convert Finset.sum_range_sub ( fun i => f i ) n using 1;
      rw [ Finset.sum_range ]

theorem canonical_cumulative_distribution_mono (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n m : ℕ) :
    Monotone (canonical_cumulative_distribution f n m) := by
      -- Since the sum of non-negative terms is non-negative, the floor of that sum is also non-negative.
      have h_floor_nonneg : ∀ k l : ℕ, k ≤ l → ⌊(∑ j : Fin (2 * n), if j.1 < k then bin_masses f n j else 0) / (∑ j : Fin (2 * n), bin_masses f n j) * m⌋ ≤ ⌊(∑ j : Fin (2 * n), if j.1 < l then bin_masses f n j else 0) / (∑ j : Fin (2 * n), bin_masses f n j) * m⌋ := by
        intros k l hkl
        have h_sum_le : (∑ j : Fin (2 * n), if j.1 < k then bin_masses f n j else 0) ≤ (∑ j : Fin (2 * n), if j.1 < l then bin_masses f n j else 0) := by
          exact Finset.sum_le_sum fun i _ => by split_ifs <;> linarith [ show 0 ≤ bin_masses f n i from by exact MeasureTheory.integral_nonneg fun x => by exact Set.indicator_nonneg ( fun x hx => hf_nonneg x ) _ ] ;
        gcongr;
        exact Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _;
      intro k l hkl; specialize h_floor_nonneg k l hkl; simp_all +decide [ canonical_cumulative_distribution ] ;
      rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr _ ), Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr _ ) ];
      · convert h_floor_nonneg using 1;
      · exact mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact bin_masses_nonneg f hf_nonneg n _ ; norm_num ] ) ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _ ) ) ( Nat.cast_nonneg _ );
      · exact mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact bin_masses_nonneg f hf_nonneg n _ ; exact le_rfl ] ) ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _ ) ) ( Nat.cast_nonneg _ )

theorem canonical_cumulative_distribution_mono_new (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n m : ℕ) :
    Monotone (canonical_cumulative_distribution f n m) := by
      exact?

theorem canonical_discretization_sum_eq_telescope (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_pos : ∑ j : Fin (2 * n), bin_masses f n j ≠ 0) :
    ∑ i : Fin (2 * n), canonical_discretization f n m i =
    ∑ i : Fin (2 * n), (canonical_cumulative_distribution f n m (i + 1) - canonical_cumulative_distribution f n m i) := by
      convert Finset.sum_congr rfl fun i _ => canonical_discretization_eq_diff f n m ?_ i;
      exact?