/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 305874b1-3eed-4942-afb4-5daac0ccf2ac

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized and proved the incremental autoconvolution update correctness.
Verified that the delta between new and old autoconvolutions decomposes into disjoint groups based on the set of changed indices S.
Proved that terms where neither index is in S contribute zero, and cross-terms simplify as expected.
Confirmed that the incremental update yields the bit-exact same result as full recomputation.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators
open scoped Classical

def int_autoconvolution {d : ℕ} (c : Fin d → ℤ) (t : ℕ) : ℤ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = t then c i * c j else 0

/-- The delta between new and old autoconvolution. -/
def autoconv_delta {d : ℕ} (c c' : Fin d → ℤ) (t : ℕ) : ℤ :=
  int_autoconvolution c' t - int_autoconvolution c t

theorem delta_eq_sum {d : ℕ} (c c' : Fin d → ℤ) (t : ℕ) :
    autoconv_delta c c' t =
    ∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t then c' i * c' j - c i * c j else 0 := by
  -- By definition of autoconv_delta, we can expand it as the difference of two sums using the linearity of summation.
  simp [autoconv_delta, int_autoconvolution];
  -- By linearity of summation, the difference of two sums is the sum of the differences.
  simp [← Finset.sum_sub_distrib];
  -- By linearity of summation, we can split the sum into two separate sums.
  apply Finset.sum_congr rfl
  intro i _
  apply Finset.sum_congr rfl
  intro j _
  aesop

theorem unchanged_terms_zero {d : ℕ} (c c' : Fin d → ℤ)
    (S : Finset (Fin d)) (hS : ∀ i : Fin d, i ∉ S → c' i = c i)
    (i j : Fin d) (hi : i ∉ S) (hj : j ∉ S) :
    c' i * c' j - c i * c j = 0 := by
  -- Since $i \notin S$ and $j \notin S$, we have $c' i = c i$ and $c' j = c j$ by $hS$.
  simp [hS i hi, hS j hj]

theorem delta_three_way_split {d : ℕ} (c c' : Fin d → ℤ)
    (S : Finset (Fin d)) (hS : ∀ i : Fin d, i ∉ S → c' i = c i)
    (t : ℕ) :
    autoconv_delta c c' t =
    -- Terms where both i,j ∈ S
    (∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t ∧ i ∈ S ∧ j ∈ S then c' i * c' j - c i * c j else 0) +
    -- Terms where i ∈ S, j ∉ S
    (∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t ∧ i ∈ S ∧ j ∉ S then c' i * c' j - c i * c j else 0) +
    -- Terms where i ∉ S, j ∈ S
    (∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t ∧ i ∉ S ∧ j ∈ S then c' i * c' j - c i * c j else 0) := by
  rw [ ← Finset.sum_add_distrib, ← Finset.sum_add_distrib ];
  convert delta_eq_sum c c' t using 2;
  rename_i i hi; rw [ ← Finset.sum_add_distrib, ← Finset.sum_add_distrib ] ; congr ; ext j ; aesop;

theorem cross_term_simplify {d : ℕ} (c c' : Fin d → ℤ)
    (S : Finset (Fin d)) (hS : ∀ i : Fin d, i ∉ S → c' i = c i)
    (i j : Fin d) (hi : i ∈ S) (hj : j ∉ S) :
    c' i * c' j - c i * c j = (c' i - c i) * c j := by
  -- Since $j \notin S$, we have $c' j = c j$ by hypothesis $hS$.
  rw [hS j hj];
  -- By the distributive property of multiplication over subtraction, we can factor out $c_j$ from the left-hand side.
  ring

theorem incremental_update_correct {d : ℕ} (c c' : Fin d → ℤ) (t : ℕ) :
    int_autoconvolution c t + autoconv_delta c c' t = int_autoconvolution c' t := by
  -- By definition of autoconv_delta, we have autoconv_delta c c' t = int_autoconvolution c' t - int_autoconvolution c t.
  rw [show autoconv_delta c c' t = int_autoconvolution c' t - int_autoconvolution c t from rfl]
  -- Adding int_autoconvolution c t to both sides gives the desired equality.
  ring

theorem groups_exhaustive {d : ℕ} (S : Finset (Fin d)) (i j : Fin d) :
    (i ∈ S ∧ j ∈ S) ∨ (i ∈ S ∧ j ∉ S) ∨ (i ∉ S ∧ j ∈ S) ∨ (i ∉ S ∧ j ∉ S) := by
  tauto

theorem groups_disjoint {d : ℕ} (S : Finset (Fin d)) (i j : Fin d) :
    ¬((i ∈ S ∧ j ∈ S) ∧ (i ∈ S ∧ j ∉ S)) ∧
    ¬((i ∈ S ∧ j ∈ S) ∧ (i ∉ S ∧ j ∈ S)) ∧
    ¬((i ∈ S ∧ j ∈ S) ∧ (i ∉ S ∧ j ∉ S)) ∧
    ¬((i ∈ S ∧ j ∉ S) ∧ (i ∉ S ∧ j ∈ S)) ∧
    ¬((i ∈ S ∧ j ∉ S) ∧ (i ∉ S ∧ j ∉ S)) ∧
    ¬((i ∉ S ∧ j ∈ S) ∧ (i ∉ S ∧ j ∉ S)) := by
  tauto