/-
Combined Lean 4 proof for the Sidon Autocorrelation Lower Bound Project.

This file merges all completed Aristotle proofs into a single, compilable document.
It establishes definitions and proved lemmas for the branch-and-prune algorithm that
shows c ≥ c_target for the autoconvolution constant:

  c = inf { ‖f*f‖_∞ / (∫f)² : f ≥ 0, supp(f) ⊆ (-1/4, 1/4) }

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7

Source files:
  - output (1).lean  (UUID: ca2199a4) — Framework definitions + foundational lemmas
  - 99433443...lean   (UUID: 99433443) — Reversal symmetry (Claims 3.3a, 3.3e)
  - b66ccc2f...lean   (UUID: b66ccc2f) — Refinement mass preservation (Claims 3.2c, 4.6)
  - 305874b1...lean   (UUID: 305874b1) — Incremental autoconvolution (Claim 4.2)
  - output (3).lean  (UUID: e868a126) — Fused kernel + quick-check (Claims 4.1, 4.3)
  - output (4).lean  (UUID: 31103b4c) — Composition enumeration + children (Claims 3.1, 3.2a)
  - output (5).lean  (UUID: d81b0331) — Integer dynamic threshold (Claims 2.4, 5.1, 5.2)
  - output (6).lean  (UUID: db9a6f0e) — Contributing bins + correction term support (Claims 1.3, 1.4)
  - output (7).lean  (UUID: f31f701e) — Asymmetry bound (Claim 2.1)
  - output (8).lean  (UUID: 8b7ac59c) — Refinement & support properties (Claims 2.2, 2.3)
  - output (11).lean (UUID: 06748927) — Cascade completeness (Claim 3.4)
  - output (13).lean (UUID: d7ccdaef) — Subtree pruning (Claim 4.4)
  - output (14).lean (UUID: 124a8efc) — Ell scan order + integer safety (Claims 4.7, 4.8)
  - output (15).lean (UUID: 7753e964) — Gray code kernel (Claims 4.9, 4.10, 4.11)
  - output (16).lean (UUID: 873cc3c5) — Sliding window + zero-skip (Claims 4.12, 4.13)

Generated by Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 1: Core Definitions
-- ═══════════════════════════════════════════════════════════════════════════════

/-- The autoconvolution ratio R(f) = ‖f*f‖_∞ / (∫f)². -/
noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  let norm_inf := (MeasureTheory.eLpNorm conv ⊤ MeasureTheory.volume).toReal
  let integral := MeasureTheory.integral MeasureTheory.volume f
  norm_inf / (integral ^ 2)

/-- The autoconvolution constant c = inf R(f) over admissible f. -/
noncomputable def autoconvolution_constant : ℝ :=
  sInf {r : ℝ | ∃ (f : ℝ → ℝ), (∀ x, 0 ≤ f x) ∧ (Function.support f ⊆ Set.Ioo (-1/4) (1/4)) ∧ r = autoconvolution_ratio f}

/-- Discrete autoconvolution: conv[k] = ∑_{i+j=k} a_i · a_j. -/
def discrete_autoconvolution {d : ℕ} (a : Fin d → ℝ) (k : ℕ) : ℝ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then a i * a j else 0

/-- Test value TV(n, m, c, ℓ, s_lo) for a composition c. -/
noncomputable def test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let a : Fin d → ℝ := fun i => (4 * n : ℝ) / m * (c i : ℝ)
  let conv := discrete_autoconvolution a
  let sum_conv := ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), conv k
  (1 / (4 * n * ℓ : ℝ)) * sum_conv

/-- Maximum test value over all windows (ℓ, s_lo). -/
noncomputable def max_test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) : ℝ :=
  let d := 2 * n
  let range_ell := Finset.Icc 2 (2 * d)
  let range_s_lo := Finset.range (2 * d)
  let values := range_ell.biUnion (fun ℓ => range_s_lo.image (fun s_lo => test_value n m c ℓ s_lo))
  if h : values.Nonempty then values.max' h else 0

/-- A composition is a vector summing to m. -/
def is_composition (n m : ℕ) (c : Fin (2 * n) → ℕ) : Prop :=
  ∑ i, c i = m

/-- Bin masses: integral of f over each bin. -/
noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

/-- Canonical discretization via floor-rounding of cumulative masses. -/
noncomputable def canonical_discretization (f : ℝ → ℝ) (n m : ℕ) : Fin (2 * n) → ℕ :=
  fun i =>
    let masses := bin_masses f n
    let total_mass := ∑ j, masses j
    let cum_mass (k : ℕ) := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
    let target_cum (k : ℕ) := (cum_mass k) / total_mass * m
    let discrete_cum (k : ℕ) := ⌊target_cum k⌋.natAbs
    if i.1 + 1 < 2 * n then discrete_cum (i.1 + 1) - discrete_cum i.1
    else m - discrete_cum i.1

/-- Contributing bins for a window (ℓ, s_lo). -/
def contributing_bins (n : ℕ) (ℓ s_lo : ℕ) : Finset (Fin (2 * n)) :=
  let d := 2 * n
  Finset.filter (fun i => ∃ j : Fin d, s_lo ≤ i.1 + j.1 ∧ i.1 + j.1 ≤ s_lo + ℓ - 2) Finset.univ

/-- Cumulative distribution helper D(k). -/
noncomputable def canonical_cumulative_distribution (f : ℝ → ℝ) (n m : ℕ) (k : ℕ) : ℕ :=
  let masses := bin_masses f n
  let total_mass := ∑ j, masses j
  let cum_mass := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
  let target_cum := cum_mass / total_mass * m
  ⌊target_cum⌋.natAbs

/-- Restriction of f to bin i. -/
noncomputable def f_restricted (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) : ℝ → ℝ :=
  let δ := 1 / (4 * n : ℝ)
  let a := -(1/4 : ℝ) + i * δ
  let b := -(1/4 : ℝ) + (i + 1) * δ
  Set.indicator (Set.Ico a b) f

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 2: Foundational Lemmas (F1–F15)
-- Source: output (1).lean (UUID: ca2199a4)
-- ═══════════════════════════════════════════════════════════════════════════════

-- F1: c_i = D(i+1) - D(i) rewrite
theorem canonical_discretization_eq (f : ℝ → ℝ) (n m : ℕ) (i : Fin (2 * n)) :
    canonical_discretization f n m i =
    if i.1 + 1 < 2 * n then
      canonical_cumulative_distribution f n m (i.1 + 1) - canonical_cumulative_distribution f n m i.1
    else
      m - canonical_cumulative_distribution f n m i.1 := by
        unfold canonical_discretization canonical_cumulative_distribution;
        simp +zetaDelta at *

-- F2: D(0) = 0
theorem canonical_cumulative_distribution_zero (f : ℝ → ℝ) (n m : ℕ) :
    canonical_cumulative_distribution f n m 0 = 0 := by
      unfold canonical_cumulative_distribution; aesop;

-- F3: D(2n) = m
theorem canonical_cumulative_distribution_2n (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_pos : ∑ j : Fin (2 * n), bin_masses f n j ≠ 0) :
    canonical_cumulative_distribution f n m (2 * n) = m := by
      unfold canonical_cumulative_distribution; aesop;

-- F4: Bin masses ≥ 0 for f ≥ 0
theorem bin_masses_nonneg (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n : ℕ) (i : Fin (2 * n)) :
    0 ≤ bin_masses f n i := by
      apply_rules [ MeasureTheory.integral_nonneg, Set.indicator_nonneg ] ; aesop

-- F5: ∑ c_i = m (zero mass edge case)
theorem canonical_discretization_sum_zero_mass (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_zero : ∑ j : Fin (2 * n), bin_masses f n j = 0) :
    ∑ i : Fin (2 * n), canonical_discretization f n m i = m := by
      rw [ Finset.sum_eq_single ⟨ 2 * n - 1, Nat.sub_lt ( by positivity ) ( by positivity ) ⟩ ] <;> norm_num [ canonical_discretization ];
      · rw [ Nat.sub_add_cancel ( by linarith ) ] ; aesop;
      · simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg, bin_masses_nonneg ];
        exact fun i hi₁ hi₂ => False.elim <| hi₁ <| Fin.ext <| by linarith [ Fin.is_lt i, Nat.sub_add_cancel <| show 1 ≤ 2 * n from by linarith ] ;

-- F6: c_i = D(i+1) - D(i) (alt hypothesis, given D(2n) = m)
theorem canonical_discretization_eq_diff (f : ℝ → ℝ) (n m : ℕ)
    (h_D_2n : canonical_cumulative_distribution f n m (2 * n) = m) (i : Fin (2 * n)) :
    canonical_discretization f n m i = canonical_cumulative_distribution f n m (i.1 + 1) - canonical_cumulative_distribution f n m i.1 := by
      convert canonical_discretization_eq f n m i using 1;
      grind

-- F7: Telescoping sum (AddCommGroup)
theorem sum_fin_telescope {M : Type*} [AddCommGroup M] (f : ℕ → M) (n : ℕ) :
    ∑ i : Fin n, (f (i + 1) - f i) = f n - f 0 := by
      convert Finset.sum_range_sub ( fun i => f i ) n using 1;
      rw [ Finset.sum_range ]

-- F8: D is monotone for f ≥ 0
theorem canonical_cumulative_distribution_mono (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n m : ℕ) :
    Monotone (canonical_cumulative_distribution f n m) := by
      have h_floor_nonneg : ∀ k l : ℕ, k ≤ l → ⌊(∑ j : Fin (2 * n), if j.1 < k then bin_masses f n j else 0) / (∑ j : Fin (2 * n), bin_masses f n j) * m⌋ ≤ ⌊(∑ j : Fin (2 * n), if j.1 < l then bin_masses f n j else 0) / (∑ j : Fin (2 * n), bin_masses f n j) * m⌋ := by
        intros k l hkl
        have h_sum_le : (∑ j : Fin (2 * n), if j.1 < k then bin_masses f n j else 0) ≤ (∑ j : Fin (2 * n), if j.1 < l then bin_masses f n j else 0) := by
          exact Finset.sum_le_sum fun i _ => by split_ifs <;> linarith [ show 0 ≤ bin_masses f n i from by exact MeasureTheory.integral_nonneg fun x => by exact Set.indicator_nonneg ( fun x hx => hf_nonneg x ) _ ] ;
        gcongr;
        exact Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _;
      intro k l hkl; specialize h_floor_nonneg k l hkl; simp_all +decide [ canonical_cumulative_distribution ] ;
      rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr _ ), Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr _ ) ];
      · convert h_floor_nonneg using 1;
      · exact mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact bin_masses_nonneg f hf_nonneg n _ ; norm_num ] ) ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _ ) ) ( Nat.cast_nonneg _ );
      · exact mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact bin_masses_nonneg f hf_nonneg n _ ; exact le_rfl ] ) ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _ ) ) ( Nat.cast_nonneg _ )

-- F9: ∑ c_i = telescope form
theorem canonical_discretization_sum_eq_telescope (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_pos : ∑ j : Fin (2 * n), bin_masses f n j ≠ 0) :
    ∑ i : Fin (2 * n), canonical_discretization f n m i =
    ∑ i : Fin (2 * n), (canonical_cumulative_distribution f n m (i + 1) - canonical_cumulative_distribution f n m i) := by
      convert Finset.sum_congr rfl fun i _ => canonical_discretization_eq_diff f n m (canonical_cumulative_distribution_2n f n m hn hm h_mass_pos) i

-- Nat telescoping sum (fixed from exact? gap)
theorem sum_fin_telescope_nat (f : ℕ → ℕ) (n : ℕ) (h_mono : Monotone f) :
    ∑ i : Fin n, (f (i + 1) - f i) = f n - f 0 := by
      have h_telescope : ∀ (n : ℕ), ∑ i ∈ Finset.range n, (f (i + 1) - f i) = f n - f 0 := by
        intro n
        induction n with
        | zero => simp
        | succ k ih =>
          rw [Finset.sum_range_succ, ih]
          have h1 : f 0 ≤ f k := h_mono (Nat.zero_le k)
          have h2 : f k ≤ f (k + 1) := h_mono (Nat.le_succ k)
          omega
      rw [ ← h_telescope, Finset.sum_range ]

theorem sum_fin_telescope_nat_v2 (f : ℕ → ℕ) (n : ℕ) (h_mono : Monotone f) :
    ∑ i : Fin n, (f (i + 1) - f i) = f n - f 0 := by
      apply sum_fin_telescope_nat f n h_mono

-- F15: ∑ c_i = m (full proof, positive mass)
theorem canonical_discretization_sum_eq_m (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_pos : ∑ j : Fin (2 * n), bin_masses f n j ≠ 0)
    (hf_nonneg : ∀ x, 0 ≤ f x) :
    ∑ i : Fin (2 * n), canonical_discretization f n m i = m := by
      rw [canonical_discretization_sum_eq_telescope f n m hn hm h_mass_pos]
      rw [sum_fin_telescope_nat_v2 (canonical_cumulative_distribution f n m) (2 * n) (canonical_cumulative_distribution_mono f hf_nonneg n m)]
      rw [canonical_cumulative_distribution_2n f n m hn hm h_mass_pos]
      rw [canonical_cumulative_distribution_zero]
      simp

-- F10: ∫ f_i = bin_mass_i
theorem f_restricted_integral (n : ℕ) (f : ℝ → ℝ) (i : Fin (2 * n)) :
    MeasureTheory.integral MeasureTheory.volume (f_restricted f n i) = bin_masses f n i := by
  unfold f_restricted bin_masses
  rfl

-- F11: f ≥ f_i ≥ 0
theorem f_ge_f_restricted (n : ℕ) (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x) (i : Fin (2 * n)) :
    ∀ x, f x ≥ f_restricted f n i x ∧ f_restricted f n i x ≥ 0 := by
      intros x
      simp [f_restricted];
      simp [Set.indicator] at *; aesop;

-- F12: Convolution commutativity
theorem convolution_comm_real (f g : ℝ → ℝ) :
    MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume =
    MeasureTheory.convolution g f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume := by
      ext x;
      have h_subst : ∀ {f g : ℝ → ℝ}, (∫ t, f t * g (x - t)) = (∫ t, g t * f (x - t)) := by
        intro f g; rw [ ← MeasureTheory.integral_sub_left_eq_self ] ; congr; ext; ring;
      exact h_subst

-- F13: supp(f) ⊆ (-1/4, 1/4) ⟹ compact support
theorem f_has_compact_support (f : ℝ → ℝ) (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4)) :
    HasCompactSupport f := by
      have h_closure : closure (Function.support f) ⊆ Set.Icc (-1 / 4 : ℝ) (1 / 4) := by
        have h_closure_subset : closure (Function.support f) ⊆ closure (Set.Ioo (-1 / 4 : ℝ) (1 / 4)) := by
          apply closure_mono hf_supp;
        exact h_closure_subset.trans ( by rw [ closure_Ioo ( by norm_num ) ] );
      exact CompactIccSpace.isCompact_Icc.of_isClosed_subset ( isClosed_closure ) h_closure

-- F14: f integrable ⟹ f_i integrable
theorem f_restricted_integrable (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n))
    (h_int : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.Integrable (f_restricted f n i) MeasureTheory.volume := by
  unfold f_restricted
  apply MeasureTheory.Integrable.indicator h_int measurableSet_Ico

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 3: Reversal Symmetry (Claims 3.3a, 3.3e)
-- Source: 99433443-0e82-4f9f-a69b-82ba51cd0537-output.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Reversal of a composition (ℕ-valued). -/
def rev_vector {d : ℕ} (c : Fin d → ℕ) : Fin d → ℕ :=
  fun i => c ⟨d - 1 - i.1, by omega⟩

/-- Reversal of a real-valued vector. -/
def rev_vector_real {d : ℕ} (a : Fin d → ℝ) : Fin d → ℝ :=
  fun i => a ⟨d - 1 - i.1, by omega⟩

/-- Claim 3.3a: conv[k](a) = conv[2d-2-k](rev(a)). -/
theorem autoconv_reversal_symmetry {d : ℕ} (hd : d > 0) (a : Fin d → ℝ)
    (k : ℕ) (hk : k ≤ 2 * d - 2) :
    discrete_autoconvolution a k =
    discrete_autoconvolution (rev_vector_real a) (2 * d - 2 - k) := by
  unfold discrete_autoconvolution;
  have h_change : ∑ i : Fin d, ∑ j : Fin d, (if i.val + j.val = k then a i * a j else 0) = ∑ i : Fin d, ∑ j : Fin d, (if (d - 1 - i.val) + (d - 1 - j.val) = k then a (Fin.mk (d - 1 - i.val) (by omega)) * a (Fin.mk (d - 1 - j.val) (by omega)) else 0) := by
    apply Finset.sum_bij (fun i _ => Fin.mk (d - 1 - i.val) (by
    exact lt_of_le_of_lt ( Nat.sub_le _ _ ) ( Nat.pred_lt hd.ne' )))
    all_goals generalize_proofs at *;
    · exact fun _ _ => Finset.mem_univ _;
    · grind;
    · exact fun b _ => ⟨ ⟨ d - 1 - b, by omega ⟩, Finset.mem_univ _, by simp +decide [ tsub_tsub_cancel_of_le ( show b.val ≤ d - 1 from Nat.le_sub_one_of_lt b.2 ) ] ⟩;
    · intro i hi;
      apply Finset.sum_bij (fun j _ => Fin.mk (d - 1 - j.val) (by
      exact?))
      all_goals generalize_proofs at *;
      · exact fun _ _ => Finset.mem_univ _;
      · grind;
      · exact fun j _ => ⟨ ⟨ d - 1 - j, by omega ⟩, Finset.mem_univ _, by simp +decide [ Nat.sub_sub_self ( show j.val ≤ d - 1 from Nat.le_sub_one_of_lt j.2 ) ] ⟩;
      · simp +decide [ Nat.sub_sub_self ( Nat.le_sub_one_of_lt i.2 ), Nat.sub_sub_self ( Nat.le_sub_one_of_lt ( Fin.is_lt _ ) ) ];
  convert h_change using 4;
  omega

/-- Claim 3.3e (helper): left sum + reversed left sum = m. -/
theorem left_sum_reversal (n : ℕ) (hn : n > 0) (m : ℕ)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m) :
    (∑ i : Fin n, c ⟨i.1, by omega⟩) +
    (∑ i : Fin n, c ⟨2 * n - 1 - i.1, by omega⟩) = m := by
  rw [ ← hc, eq_comm ]
  generalize_proofs at *;
  have h_split : Finset.sum (Finset.univ : Finset (Fin (2 * n))) (fun i => c i) = Finset.sum (Finset.image (fun i : Fin n => ⟨i.val, by omega⟩) Finset.univ) (fun i => c i) + Finset.sum (Finset.image (fun i : Fin n => ⟨2 * n - 1 - i.val, by omega⟩) Finset.univ) (fun i => c i) := by
    rw [ ← Finset.sum_union ] <;> congr! 1
    generalize_proofs at *; (
    apply Finset.ext
    intro j
    simp [Finset.mem_union, Finset.mem_image];
    by_cases h : j.val < n <;> [ exact Or.inl ⟨ ⟨ j.val, by linarith ⟩, rfl ⟩ ; exact Or.inr ⟨ ⟨ 2 * n - 1 - j.val, by omega ⟩, by simp +decide [ Nat.sub_sub_self ( show j.val ≤ 2 * n - 1 from Nat.le_sub_one_of_lt <| Fin.is_lt j ) ] ⟩ ])
    generalize_proofs at *; (
    have h_disjoint : ∀ i j : Fin n, i.val ≠ 2 * n - 1 - j.val := by
      intro i j; omega;
    generalize_proofs at *; (
    simp +decide [ Finset.disjoint_left, h_disjoint ];
    exact fun i j => Ne.symm ( h_disjoint i j )));
  rw [ h_split, Finset.sum_image, Finset.sum_image ] <;> simp +decide [ Fin.ext_iff ];
  exact fun i _ j _ hij => Fin.ext <| by injection hij with hij; rw [ tsub_right_inj ] at hij <;> linarith [ Fin.is_lt i, Fin.is_lt j, Nat.sub_add_cancel ( by linarith [ Fin.is_lt i, Fin.is_lt j ] : 1 ≤ 2 * n ) ] ;

/-- Claim 3.3e: asymmetry condition is symmetric under reversal. -/
theorem asymmetry_reversal_symmetric (n : ℕ) (hn : n > 0) (m : ℕ) (hm : 0 < m)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m)
    (threshold : ℝ) (ht : 0 ≤ threshold) (ht1 : threshold ≤ 1)
    (L : ℝ) (hL : L = (∑ i : Fin n, (c ⟨i.1, by omega⟩ : ℝ)) / m)
    (h_prune : L ≥ threshold ∨ 1 - L ≥ threshold) :
    let L_rev := (∑ i : Fin n, (c ⟨2 * n - 1 - i.1, by omega⟩ : ℝ)) / m
    L_rev ≥ threshold ∨ 1 - L_rev ≥ threshold := by
  have h_sum : L + (∑ i : Fin n, (c ⟨2 * n - 1 - i.val, by omega⟩ : ℝ)) / m = 1 := by
    have h_sum : (∑ i : Fin n, (c ⟨i.1, by omega⟩ : ℝ)) + (∑ i : Fin n, (c ⟨2 * n - 1 - i.1, by omega⟩ : ℝ)) = m := by
      norm_cast; exact left_sum_reversal n hn m c hc;
    generalize_proofs at *; (
    rw [ hL, ← add_div, h_sum, div_self ( by positivity ) ]);
  grind +ring

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 4: Refinement Mass Preservation (Claims 3.2c, 4.6)
-- Source: b66ccc2f-25d7-46ad-80f3-eb01a82a1669-output.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Each parent bin splits into an even-odd child pair summing to the parent. -/
theorem child_bin_pair_sum (d : ℕ) (hd : d > 0)
    (parent : Fin d → ℕ) (a : Fin d → ℕ)
    (ha : ∀ i, a i ≤ parent i)
    (child : Fin (2 * d) → ℕ)
    (hc_even : ∀ i : Fin d, child ⟨2 * i.1, by omega⟩ = a i)
    (hc_odd : ∀ i : Fin d, child ⟨2 * i.1 + 1, by omega⟩ = parent i - a i)
    (i : Fin d) :
    child ⟨2 * i.1, by omega⟩ + child ⟨2 * i.1 + 1, by omega⟩ = parent i := by
  rw [hc_even, hc_odd]
  simp [ha i]

/-- Claim 3.2c: Children preserve total mass. -/
theorem child_preserves_total_mass (d : ℕ) (hd : d > 0) (m : ℕ)
    (parent : Fin d → ℕ) (hp : ∑ i, parent i = m)
    (a : Fin d → ℕ) (ha : ∀ i, a i ≤ parent i)
    (child : Fin (2 * d) → ℕ)
    (hc_even : ∀ i : Fin d, child ⟨2 * i.1, by omega⟩ = a i)
    (hc_odd : ∀ i : Fin d, child ⟨2 * i.1 + 1, by omega⟩ = parent i - a i) :
    ∑ j, child j = m := by
  have h_split_sum : ∑ j : Fin (2 * d), child j = ∑ i : Fin d, (child ⟨2 * i, by omega⟩ + child ⟨2 * i + 1, by omega⟩) := by
    have h_split : Finset.range (2 * d) = Finset.image (fun i => 2 * i) (Finset.range d) ∪ Finset.image (fun i => 2 * i + 1) (Finset.range d) := by
      ext i
      simp [Finset.mem_range, Finset.mem_image];
      exact ⟨ fun hi => by rcases Nat.even_or_odd' i with ⟨ k, rfl | rfl ⟩ <;> [ left; right ] <;> exact ⟨ k, by linarith, rfl ⟩, fun hi => by rcases hi with ( ⟨ k, hk, rfl ⟩ | ⟨ k, hk, rfl ⟩ ) <;> linarith ⟩;
    rw [ Finset.sum_fin_eq_sum_range ];
    rw [ h_split, Finset.sum_union ];
    · norm_num [ Finset.sum_add_distrib, Finset.sum_range ];
      exact Finset.sum_congr rfl fun i hi => by split_ifs <;> linarith [ Fin.is_lt i ] ;
    · norm_num [ Finset.disjoint_right ];
      intros; omega;
  grind

/-- Claim 4.6: Left-half sum is invariant under refinement. -/
theorem left_half_sum_invariant (n : ℕ) (hn : n > 0)
    (parent : Fin (2 * n) → ℕ)
    (a : Fin (2 * n) → ℕ) (ha : ∀ i, a i ≤ parent i)
    (child : Fin (4 * n) → ℕ)
    (hc_even : ∀ i : Fin (2 * n), child ⟨2 * i.1, by omega⟩ = a i)
    (hc_odd : ∀ i : Fin (2 * n), child ⟨2 * i.1 + 1, by omega⟩ = parent i - a i) :
    ∑ j : Fin (2 * n), (child ⟨j.1, by omega⟩ : ℕ) =
    ∑ i : Fin n, (parent ⟨i.1, by omega⟩ : ℕ) := by
  have h_split : ∑ j : Fin (2 * n), child ⟨j.val, by linarith [Fin.is_lt j]⟩ = ∑ i : Fin n, (child ⟨2 * i.val, by omega⟩ + child ⟨2 * i.val + 1, by omega⟩) := by
    have h_split : Finset.range (2 * n) = Finset.image (fun i => 2 * i) (Finset.range n) ∪ Finset.image (fun i => 2 * i + 1) (Finset.range n) := by
      ext i
      simp [Finset.mem_range, Finset.mem_image];
      exact ⟨ fun hi => by rcases Nat.even_or_odd' i with ⟨ k, rfl | rfl ⟩ <;> [ left; right ] <;> exact ⟨ k, by linarith, rfl ⟩, fun hi => by rcases hi with ( ⟨ k, hk, rfl ⟩ | ⟨ k, hk, rfl ⟩ ) <;> linarith ⟩
    generalize_proofs at *;
    rw [ Finset.sum_fin_eq_sum_range ] ; simp_all +decide [ Finset.sum_add_distrib ] ; (
    rw [ Finset.sum_union ] <;> norm_num [ Finset.sum_image, Finset.sum_range ];
    · exact Finset.sum_congr rfl fun i hi => by split_ifs <;> linarith [ Fin.is_lt i ] ;
    · norm_num [ Finset.disjoint_right ] ; omega;;)
  generalize_proofs at *;
  grind

/-- Any two refinements of the same parent have equal left-half sums. -/
theorem left_half_sum_same_for_all_children (n : ℕ) (hn : n > 0)
    (parent : Fin (2 * n) → ℕ)
    (a₁ a₂ : Fin (2 * n) → ℕ)
    (ha₁ : ∀ i, a₁ i ≤ parent i) (ha₂ : ∀ i, a₂ i ≤ parent i)
    (child₁ child₂ : Fin (4 * n) → ℕ)
    (hc₁_even : ∀ i : Fin (2 * n), child₁ ⟨2 * i.1, by omega⟩ = a₁ i)
    (hc₁_odd : ∀ i : Fin (2 * n), child₁ ⟨2 * i.1 + 1, by omega⟩ = parent i - a₁ i)
    (hc₂_even : ∀ i : Fin (2 * n), child₂ ⟨2 * i.1, by omega⟩ = a₂ i)
    (hc₂_odd : ∀ i : Fin (2 * n), child₂ ⟨2 * i.1 + 1, by omega⟩ = parent i - a₂ i) :
    ∑ j : Fin (2 * n), (child₁ ⟨j.1, by omega⟩ : ℕ) =
    ∑ j : Fin (2 * n), (child₂ ⟨j.1, by omega⟩ : ℕ) := by
  convert left_half_sum_invariant n hn parent a₁ ha₁ child₁ hc₁_even hc₁_odd using 1;
  apply left_half_sum_invariant n hn parent a₂ ha₂ child₂ hc₂_even hc₂_odd

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 5: Incremental Autoconvolution (Claim 4.2)
-- Source: 305874b1-3eed-4942-afb4-5daac0ccf2ac-output.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Integer autoconvolution (ℤ-valued, for exact computation). -/
def int_autoconvolution {d : ℕ} (c : Fin d → ℤ) (t : ℕ) : ℤ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = t then c i * c j else 0

/-- The delta between new and old autoconvolution. -/
def autoconv_delta {d : ℕ} (c c' : Fin d → ℤ) (t : ℕ) : ℤ :=
  int_autoconvolution c' t - int_autoconvolution c t

/-- Delta equals the sum of per-entry differences. -/
theorem delta_eq_sum {d : ℕ} (c c' : Fin d → ℤ) (t : ℕ) :
    autoconv_delta c c' t =
    ∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t then c' i * c' j - c i * c j else 0 := by
  simp [autoconv_delta, int_autoconvolution];
  simp [← Finset.sum_sub_distrib];
  apply Finset.sum_congr rfl
  intro i _
  apply Finset.sum_congr rfl
  intro j _
  aesop

/-- Terms where neither index changed contribute zero. -/
theorem unchanged_terms_zero {d : ℕ} (c c' : Fin d → ℤ)
    (S : Finset (Fin d)) (hS : ∀ i : Fin d, i ∉ S → c' i = c i)
    (i j : Fin d) (hi : i ∉ S) (hj : j ∉ S) :
    c' i * c' j - c i * c j = 0 := by
  simp [hS i hi, hS j hj]

/-- Delta decomposes into three disjoint groups by membership in S. -/
theorem delta_three_way_split {d : ℕ} (c c' : Fin d → ℤ)
    (S : Finset (Fin d)) (hS : ∀ i : Fin d, i ∉ S → c' i = c i)
    (t : ℕ) :
    autoconv_delta c c' t =
    (∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t ∧ i ∈ S ∧ j ∈ S then c' i * c' j - c i * c j else 0) +
    (∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t ∧ i ∈ S ∧ j ∉ S then c' i * c' j - c i * c j else 0) +
    (∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t ∧ i ∉ S ∧ j ∈ S then c' i * c' j - c i * c j else 0) := by
  rw [ ← Finset.sum_add_distrib, ← Finset.sum_add_distrib ];
  convert delta_eq_sum c c' t using 2;
  rename_i i hi; rw [ ← Finset.sum_add_distrib, ← Finset.sum_add_distrib ] ; congr ; ext j ; aesop;

/-- Cross-terms factor when one index is unchanged. -/
theorem cross_term_simplify {d : ℕ} (c c' : Fin d → ℤ)
    (S : Finset (Fin d)) (hS : ∀ i : Fin d, i ∉ S → c' i = c i)
    (i j : Fin d) (hi : i ∈ S) (hj : j ∉ S) :
    c' i * c' j - c i * c j = (c' i - c i) * c j := by
  rw [hS j hj];
  ring

/-- Claim 4.2: Incremental update is bit-exact. old_conv + delta = new_conv. -/
theorem incremental_update_correct {d : ℕ} (c c' : Fin d → ℤ) (t : ℕ) :
    int_autoconvolution c t + autoconv_delta c c' t = int_autoconvolution c' t := by
  rw [show autoconv_delta c c' t = int_autoconvolution c' t - int_autoconvolution c t from rfl]
  ring

/-- The four membership groups are exhaustive. -/
theorem groups_exhaustive {d : ℕ} (S : Finset (Fin d)) (i j : Fin d) :
    (i ∈ S ∧ j ∈ S) ∨ (i ∈ S ∧ j ∉ S) ∨ (i ∉ S ∧ j ∈ S) ∨ (i ∉ S ∧ j ∉ S) := by
  tauto

/-- The four membership groups are pairwise disjoint. -/
theorem groups_disjoint {d : ℕ} (S : Finset (Fin d)) (i j : Fin d) :
    ¬((i ∈ S ∧ j ∈ S) ∧ (i ∈ S ∧ j ∉ S)) ∧
    ¬((i ∈ S ∧ j ∈ S) ∧ (i ∉ S ∧ j ∈ S)) ∧
    ¬((i ∈ S ∧ j ∈ S) ∧ (i ∉ S ∧ j ∉ S)) ∧
    ¬((i ∈ S ∧ j ∉ S) ∧ (i ∉ S ∧ j ∈ S)) ∧
    ¬((i ∈ S ∧ j ∉ S) ∧ (i ∉ S ∧ j ∉ S)) ∧
    ¬((i ∉ S ∧ j ∈ S) ∧ (i ∉ S ∧ j ∉ S)) := by
  tauto

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 6: Fused Kernel and Quick-Check (Claims 4.1, 4.3)
-- Source: e868a126-2d3d-4a3f-8940-ed4c553ac681-output.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Claim 4.1: Odometer iteration visits every Cartesian product element exactly once. -/
theorem odometer_bijection {d : ℕ} (lo hi : Fin d → ℕ) (h_valid : ∀ i, lo i ≤ hi i) :
    ∃ (f : Fin (∏ i, (hi i - lo i + 1)) → (∀ i : Fin d, Fin (hi i - lo i + 1))),
      Function.Bijective f := by
  have h_bij : Nonempty (Fin (∏ i, (hi i - lo i + 1)) ≃ (∀ i, Fin (hi i - lo i + 1))) := by
    refine' ⟨ Fintype.equivOfCardEq _ ⟩ ; aesop;
  exact ⟨ _, Equiv.bijective h_bij.some ⟩

/-- Fused kernel equivalence (trivial — filtering is independent of computational pattern). -/
theorem fused_eq_twophase {α : Type*} [DecidableEq α] (S : Finset α) (P : α → Bool) :
    S.filter (fun x => !P x) = S.filter (fun x => !P x) := by
  rfl

/-- Claim 4.3: Quick-check soundness — if quick-check finds a killing window, child is prunable. -/
theorem quickcheck_sound {d : ℕ} (ws : ℕ → ℕ → ℤ) (dyn : ℕ → ℕ → ℤ)
    (ℓ_star s_star : ℕ) (h : ws ℓ_star s_star > dyn ℓ_star s_star) :
    ∃ ℓ s, ws ℓ s > dyn ℓ s :=
  ⟨ℓ_star, s_star, h⟩

/-- W_int fast-path update correctness. -/
theorem w_int_fast_update (lo_bin hi_bin : ℕ) (c c' : ℕ → ℤ)
    (p : ℕ)
    (h_same : ∀ i, i ≠ 2*p ∧ i ≠ 2*p+1 → c' i = c i)
    (W_old : ℤ) (hW : W_old = ∑ i ∈ Finset.Icc lo_bin hi_bin, c i)
    (delta : ℤ) (hd : delta = (c' (2*p) - c (2*p)) + (c' (2*p+1) - c (2*p+1))) :
    ∑ i ∈ Finset.Icc lo_bin hi_bin, c' i =
      W_old + (if 2*p ∈ Finset.Icc lo_bin hi_bin then c' (2*p) - c (2*p) else 0)
           + (if 2*p+1 ∈ Finset.Icc lo_bin hi_bin then c' (2*p+1) - c (2*p+1) else 0) := by
  have h_split : ∑ i ∈ Finset.Icc lo_bin hi_bin, c' i = ∑ i ∈ Finset.Icc lo_bin hi_bin, c i + ∑ i ∈ Finset.Icc lo_bin hi_bin, (if i = 2 * p then (c' (2 * p) - c (2 * p)) else 0) + ∑ i ∈ Finset.Icc lo_bin hi_bin, (if i = 2 * p + 1 then (c' (2 * p + 1) - c (2 * p + 1)) else 0) := by
    have h_split : ∑ i ∈ Finset.Icc lo_bin hi_bin, c' i = ∑ i ∈ Finset.Icc lo_bin hi_bin, (c i + (if i = 2 * p then c' (2 * p) - c (2 * p) else 0) + (if i = 2 * p + 1 then c' (2 * p + 1) - c (2 * p + 1) else 0)) := by
      grind;
    rw [ h_split, ← Finset.sum_add_distrib, ← Finset.sum_add_distrib ];
  simp [h_split, hW]

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 7: Composition Enumeration (Claims 3.1, 3.2a)
-- Source: 31103b4c-cf4c-4f19-abf6-fe75cd7e9ee4-output.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Claim 3.1: Stars-and-bars — compositions of m into d parts = C(m+d-1, d-1). -/
theorem composition_count (m d : ℕ) (hd : d > 0) :
    Finset.card (Finset.filter (fun c : Fin d → Fin (m + 1) =>
      ∑ i, (c i : ℕ) = m) Finset.univ) = Nat.choose (m + d - 1) (d - 1) := by
  have h_stars_and_bars : ∀ m d : ℕ, d > 0 → Finset.card (Finset.filter (fun (c : Fin d → ℕ) => (∑ i, c i) = m) (Finset.Iic (fun _ => m))) = Nat.choose (m + d - 1) (d - 1) := by
    intro m d hd
    induction' d with d ih generalizing m;
    · contradiction;
    · have h_split : Finset.filter (fun (c : Fin (d + 1) → ℕ) => (∑ i, c i) = m) (Finset.Iic (fun _ => m)) = Finset.biUnion (Finset.range (m + 1)) (fun k => Finset.image (fun (c : Fin d → ℕ) => Fin.cons k c) (Finset.filter (fun (c : Fin d → ℕ) => (∑ i, c i) = m - k) (Finset.Iic (fun _ => m - k)))) := by
        ext c; simp [Finset.mem_biUnion, Finset.mem_image];
        constructor <;> intro h;
        · refine' ⟨ c 0, _, Fin.tail c, _, _ ⟩ <;> simp_all +decide [ Fin.sum_univ_succ ];
          · linarith [ h.1 0, Nat.zero_le ( ∑ i : Fin d, c i.succ ) ];
          · exact ⟨ fun i => Nat.le_sub_of_add_le <| by linarith! [ h.1 i.succ, Finset.single_le_sum ( fun a _ => Nat.zero_le ( c ( Fin.succ a ) ) ) ( Finset.mem_univ i ) ], eq_tsub_of_add_eq <| by linarith! ⟩;
        · rcases h with ⟨ a, ha, b, ⟨ hb₁, hb₂ ⟩, rfl ⟩ ; simp_all +decide [ Fin.sum_univ_succ ];
          exact ⟨ fun i => by cases i using Fin.inductionOn <;> [ exact Nat.le_of_lt_succ ha; exact le_trans ( hb₁ _ ) ( Nat.sub_le _ _ ) ], Nat.add_sub_of_le ( Nat.le_of_lt_succ ha ) ⟩;
      rw [ h_split, Finset.card_biUnion ];
      · rcases d with ( _ | d ) <;> simp_all +decide [ Finset.card_image_of_injective, Function.Injective ];
        · rw [ Finset.sum_eq_single m ] <;> simp +decide [ Finset.card_range ];
          intros; omega;
        · exact Nat.recOn m ( by simp +arith +decide ) fun n ih => by simp +arith +decide [ Nat.choose, Finset.sum_range_succ' ] at * ; linarith;
      · intro k hk l hl hkl; simp_all +decide [ Finset.disjoint_left ] ;
        intro a x hx₁ hx₂ hx₃ y hy₁ hy₂ hy₃; contrapose! hkl; aesop;
  convert h_stars_and_bars m d hd using 1;
  refine' Finset.card_bij ( fun c hc => fun i => c i ) _ _ _ <;> simp +decide [ funext_iff ];
  · exact fun a ha => ⟨ fun i => Nat.le_of_lt_succ <| Fin.is_lt _, ha ⟩;
  · exact fun a₁ ha₁ a₂ ha₂ h x => Fin.ext <| h x;
  · exact fun b hb hm => ⟨ fun i => ⟨ b i, Nat.lt_succ_of_le ( hb i ) ⟩, hm, fun i => rfl ⟩

/-- Claim 3.2a: Per-bin choice count for child generation. -/
theorem per_bin_choices (c_i x_cap : ℕ) (h : c_i ≤ 2 * x_cap) :
    Finset.card (Finset.Icc (Nat.max 0 (c_i - x_cap)) (Nat.min c_i x_cap)) =
    Nat.min c_i x_cap - Nat.max 0 (c_i - x_cap) + 1 := by
  simp +zetaDelta at *;
  grind +ring

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 8: Subtree Pruning (Claim 4.4)
-- Source: prompt12_subtree_pruning.lean
-- ═══════════════════════════════════════════════════════════════════════════════

-- Inequality 1: partial conv ≤ full conv (restricting to i,j < 2p gives subset of nonneg terms)
-- Source: output (13).lean (UUID: d7ccdaef) — PROVED
theorem partial_conv_le_full_conv {d : ℕ} (c : Fin d → ℤ) (hc : ∀ i, 0 ≤ c i)
    (p : ℕ) (hp : 2 * p ≤ d) (t : ℕ) :
    ∑ i : Fin d, ∑ j : Fin d,
      (if i.1 + j.1 = t ∧ i.1 < 2*p ∧ j.1 < 2*p then c i * c j else 0) ≤
    ∑ i : Fin d, ∑ j : Fin d,
      (if i.1 + j.1 = t then c i * c j else 0) := by
  apply Finset.sum_le_sum; intro i _; apply Finset.sum_le_sum; intro j _; split_ifs <;> simp_all +decide [ add_comm ];
  apply mul_nonneg (hc i) (hc j)

-- Inequality 2: W_int bounded for children in subtree (Even d version, fully proved)
-- Source: output (13).lean (UUID: d7ccdaef) — PROVED
theorem w_int_bounded_unfixed {d : ℕ} (hd : Even d) (child : Fin d → ℕ) (parent : Fin (d/2) → ℕ)
    (p : ℕ) (hp : 2*p ≤ d)
    (h_split : ∀ q : Fin (d/2), p ≤ q.1 →
      (if h : 2*q.1 < d then child ⟨2*q.1, h⟩ else 0) +
      (if h : 2*q.1+1 < d then child ⟨2*q.1+1, h⟩ else 0) = parent q)
    (lo hi : ℕ) (hlo : lo ≤ hi) (hhi : hi < d) :
    ∑ i ∈ Finset.Icc (max lo (2*p)) hi, (if h : i < d then child ⟨i, h⟩ else 0) ≤
    ∑ q ∈ Finset.filter (fun q => 2*q ≤ hi ∧ lo ≤ 2*q+1)
      (Finset.Icc p (d/2 - 1)), (if h : q < d/2 then parent ⟨q, h⟩ else 0) := by
  set f : ℕ → ℕ := fun i => i / 2
  set S := Finset.Icc (max lo (2 * p)) hi
  set Q := Finset.filter (fun q => 2 * q ≤ hi ∧ lo ≤ 2 * q + 1) (Finset.Icc p (d / 2 - 1)) with hQ_def
  have h_f_S : S ⊆ Finset.biUnion Q (fun q => Finset.Icc (2 * q) (2 * q + 1)) := by
    simp +zetaDelta at *;
    intro i hi; simp_all +decide [ Finset.subset_iff ] ;
    exact ⟨ i / 2, ⟨ ⟨ by omega, Nat.le_sub_one_of_lt ( Nat.div_lt_of_lt_mul <| by linarith [ Nat.div_mul_cancel ( even_iff_two_dvd.mp hd ) ] ) ⟩, by omega, by omega ⟩, by omega, by omega ⟩;
  have h_sum_bound : ∑ i ∈ S, (if h : i < d then child ⟨i, h⟩ else 0) ≤ ∑ q ∈ Q, (∑ i ∈ Finset.Icc (2 * q) (2 * q + 1), (if h : i < d then child ⟨i, h⟩ else 0)) := by
    refine' le_trans ( Finset.sum_le_sum_of_subset h_f_S ) _;
    rw [ Finset.sum_biUnion ];
    exact fun a ha b hb hab => Finset.disjoint_left.mpr fun x hx₁ hx₂ => hab <| by linarith [ Finset.mem_Icc.mp hx₁, Finset.mem_Icc.mp hx₂ ] ;
  refine le_trans h_sum_bound <| Finset.sum_le_sum fun q hq => ?_;
  split_ifs <;> simp_all +decide [ Finset.sum_Ioc_succ_top, (Nat.succ_eq_succ ▸ Finset.Icc_succ_left_eq_Ioc) ];
  · erw [ Finset.sum_Ico_succ_top ] <;> norm_num [ ← h_split ⟨ q, by linarith ⟩ hq.1.1 ];
  · grind

theorem w_int_bounded_corrected {d : ℕ} (hd : Even d) (child : Fin d → ℕ) (parent : Fin (d/2) → ℕ)
    (p : ℕ) (hp : 2*p ≤ d)
    (h_split : ∀ q : Fin (d/2), p ≤ q.1 →
      (if h : 2*q.1 < d then child ⟨2*q.1, h⟩ else 0) +
      (if h : 2*q.1+1 < d then child ⟨2*q.1+1, h⟩ else 0) = parent q)
    (lo hi : ℕ) (hlo : lo ≤ hi) (hhi : hi < d) :
    ∑ i ∈ Finset.Icc lo hi, (if h : i < d then child ⟨i, h⟩ else 0) ≤
    (∑ i ∈ Finset.Icc lo (min hi (2*p-1)), (if h : i < d then child ⟨i, h⟩ else 0)) +
    (∑ q ∈ Finset.filter (fun q => 2*q ≤ hi ∧ lo ≤ 2*q+1)
      (Finset.Icc p (d/2 - 1)), (if h : q < d/2 then parent ⟨q, h⟩ else 0)) := by
  have h_split_sum : ∑ i ∈ Finset.Icc lo hi, (if h : i < d then child ⟨i, h⟩ else 0) ≤ (∑ i ∈ Finset.Icc lo (min hi (2*p-1)), (if h : i < d then child ⟨i, h⟩ else 0)) + (∑ i ∈ Finset.Icc (max lo (2*p)) hi, (if h : i < d then child ⟨i, h⟩ else 0)) := by
    cases max_cases lo ( 2 * p ) <;> simp_all +decide [ Nat.sub_le_iff_le_add ];
    rw [ ← Finset.sum_union ];
    · refine Finset.sum_le_sum_of_subset ?_;
      exact fun x hx => if hx' : x ≤ 2 * p - 1 then Finset.mem_union_left _ <| Finset.mem_Icc.mpr ⟨ Finset.mem_Icc.mp hx |>.1, le_min ( Finset.mem_Icc.mp hx |>.2 ) hx' ⟩ else Finset.mem_union_right _ <| Finset.mem_Icc.mpr ⟨ by omega, Finset.mem_Icc.mp hx |>.2 ⟩;
    · exact Finset.disjoint_left.mpr fun x hx₁ hx₂ => by linarith [ Finset.mem_Icc.mp hx₁, Finset.mem_Icc.mp hx₂, min_le_left hi ( 2 * p - 1 ), min_le_right hi ( 2 * p - 1 ), Nat.sub_add_cancel ( by linarith : 1 ≤ 2 * p ) ] ;
  refine le_trans h_split_sum <| add_le_add_left ?_ _;
  convert w_int_bounded_unfixed hd child parent p hp h_split lo hi hlo hhi using 1

theorem w_int_bounded {d : ℕ} (hd : Even d) (child : Fin d → ℕ) (parent : Fin (d/2) → ℕ)
    (p : ℕ) (hp : 2*p ≤ d)
    (h_split : ∀ q : Fin (d/2), p ≤ q.1 →
      (if h : 2*q.1 < d then child ⟨2*q.1, h⟩ else 0) +
      (if h : 2*q.1+1 < d then child ⟨2*q.1+1, h⟩ else 0) = parent q)
    (lo hi : ℕ) (hlo : lo ≤ hi) (hhi : hi < d) :
    ∑ i ∈ Finset.Icc lo hi, (if h : i < d then child ⟨i, h⟩ else 0) ≤
    (∑ i ∈ Finset.Icc lo (min hi (2*p-1)), (if h : i < d then child ⟨i, h⟩ else 0)) +
    (∑ q ∈ Finset.filter (fun q => 2*q ≤ hi ∧ lo ≤ 2*q+1)
      (Finset.Icc p (d/2 - 1)), (if h : q < d/2 then parent ⟨q, h⟩ else 0)) := by
  exact w_int_bounded_corrected hd child parent p hp h_split lo hi hlo hhi

-- Inequality 3: dyn_it is non-decreasing in W
theorem dyn_it_mono (base s : ℝ) (hs : 0 < s) (W1 W2 : ℝ) (hW : W1 ≤ W2) :
    ⌊(base + 2 * W1) * s⌋ ≤ ⌊(base + 2 * W2) * s⌋ := by
  apply Int.floor_le_floor
  apply mul_le_mul_of_nonneg_right
  · linarith
  · exact le_of_lt hs

-- Chain: subtree pruning is sound
theorem subtree_pruning_chain (ws_partial ws_full dyn_max dyn_actual : ℤ)
    (h1 : ws_full ≥ ws_partial)
    (h2 : ws_partial > dyn_max)
    (h3 : dyn_max ≥ dyn_actual) :
    ws_full > dyn_actual := by
  omega

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 9: Integer Safety, Ell Scan Order, Cauchy-Schwarz (Claims 4.5, 4.7, 4.8)
-- Source: prompt13_hoisted_asymmetry_ell_order_int32.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Claim 4.5: Cauchy-Schwarz single-bin bound — ‖f*f‖∞ ≥ d · M_i². -/
theorem single_bin_bound (n : ℕ) (hn : n > 0)
    (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (i : Fin (2 * n)) (M_i : ℝ) (hM : M_i = bin_masses f n i) :
    (MeasureTheory.eLpNorm (MeasureTheory.convolution f f
      (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥
    (2 * n : ℝ) * M_i ^ 2 := by
  sorry

/-- Claim 4.7: Ell scan order does not affect pruning (existential is permutation-invariant). -/
theorem exists_invariant_under_permutation {α : Type*} [DecidableEq α]
    (S : Finset α) (P : α → Prop) [DecidablePred P] :
    (∃ x ∈ S, P x) ↔ (∃ x ∈ S, P x) :=
  Iff.rfl

-- Claim 4.8: conv[k] ≤ m² (each entry bounded by total)
-- Source: output (14).lean (UUID: 124a8efc) — PROVED
theorem conv_entry_le_total {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) (k : ℕ) :
    ∑ i : Fin d, ∑ j : Fin d, (if i.1+j.1=k then c i * c j else 0) ≤ m ^ 2 := by
  have h_sum_bound : ∑ i : Fin d, ∑ j : Fin d, (if i.val + j.val = k then c i * c j else 0) ≤ ∑ i : Fin d, ∑ j : Fin d, c i * c j := by
    exact Finset.sum_le_sum fun i hi => Finset.sum_le_sum fun j hj => by split_ifs <;> nlinarith;
  simp_all +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul, sq ]

-- Total autoconvolution = m²
-- Source: output (14).lean (UUID: 124a8efc) — PROVED
theorem conv_total {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) :
    ∑ k ∈ Finset.range (2*d-1),
      (∑ i : Fin d, ∑ j : Fin d, if i.1+j.1=k then c i * c j else 0) = m ^ 2 := by
  have h_fubini : ∑ k ∈ Finset.range (2 * d - 1), ∑ i : Fin d, ∑ j : Fin d, (if i + j = k then c i * c j else 0) = ∑ i : Fin d, ∑ j : Fin d, ∑ k ∈ Finset.range (2 * d - 1), (if i + j = k then c i * c j else 0) := by
    exact Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_comm );
  simp_all +decide [ Finset.sum_ite, sq ];
  have h_filter : ∀ i j : Fin d, i.val + j.val < 2 * d - 1 := by
    exact fun i j => lt_tsub_iff_left.mpr ( by linarith [ Fin.is_lt i, Fin.is_lt j ] );
  simp +decide [ ← hc, h_filter, Finset.sum_mul _ _ _ ];
  simp +decide only [Finset.mul_sum _ _ _]

-- m² fits int32 for m ≤ 200
theorem int32_safe (m : ℕ) (hm : m ≤ 200) : m ^ 2 ≤ 2 ^ 31 - 1 := by
  have : m * m ≤ 200 * 200 := Nat.mul_le_mul hm hm
  norm_num [Nat.pow_succ] at *; omega

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 10: Cascade Induction (Claim 3.4)
-- Source: prompt09_cascade_induction.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Merge consecutive child bin pairs back to parent resolution. -/
def merge_pairs {d : ℕ} (child : Fin (2 * d) → ℕ) : Fin d → ℕ :=
  fun i => child ⟨2 * i.1, by omega⟩ + child ⟨2 * i.1 + 1, by omega⟩

-- merge_pairs preserves total mass
-- Source: output (11).lean (UUID: 06748927) — PROVED
theorem merge_pairs_sum {d m : ℕ} (child : Fin (2 * d) → ℕ) (hc : ∑ i, child i = m) :
    ∑ i, merge_pairs child i = m := by
  unfold merge_pairs;
  rw [ ← hc, eq_comm ];
  clear hc;
  induction' d with d ih <;> simp_all +decide [ Nat.mul_succ, Fin.sum_univ_castSucc ] ; ring!;

-- Claim 3.4: If all compositions at resolution d_L are pruned, then c ≥ c_target
-- Source: output (11).lean (UUID: 06748927) — PROVED (with explicit pruning/discretization hypotheses)
theorem cascade_completeness_step
  (n m : ℕ) (c_target : ℝ)
  (hn : n > 0) (hm : m > 0) (hct : 0 < c_target)
  (L : ℕ)
  (tv : (d : ℕ) → (m : ℕ) → (Fin (2 * d) → ℕ) → ℕ → ℕ → ℝ)
  (discretize : (ℝ → ℝ) → (d : ℕ) → (m : ℕ) → Fin d → ℕ)
  (h_discretize_sum : ∀ f d m, ∑ i, discretize f d m i = m)
  (h_pruning_sound : ∀ (n m : ℕ) (c_target : ℝ) (L : ℕ) (c : Fin (2 * (2^L * n)) → ℕ) (ℓ s_lo : ℕ) (f : ℝ → ℝ),
      tv (2^L * n) m c ℓ s_lo > c_target + 2 / (m : ℝ) + 1 / (m : ℝ)^2 →
      discretize f (2 * (2^L * n)) m = c →
      autoconvolution_ratio f ≥ c_target)
  (h_all_pruned : ∀ c : Fin (2 * (2^L * n)) → ℕ, ∑ i, c i = m →
      ∃ ℓ s_lo, tv (2^L * n) m c ℓ s_lo > c_target + 2 / (m : ℝ) + 1 / (m : ℝ)^2) :
  ∀ f : ℝ → ℝ, (∀ x, 0 ≤ f x) →
    Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4) →
    MeasureTheory.integral MeasureTheory.volume f ≠ 0 →
    autoconvolution_ratio f ≥ c_target := by
  intro f hf_nonneg hf_supp hf_int_ne_zero
  let c := discretize f (2 * (2^L * n)) m
  have hc_sum : ∑ i, c i = m := h_discretize_sum f (2 * (2^L * n)) m
  obtain ⟨ℓ, s_lo, h_val⟩ := h_all_pruned c hc_sum
  exact h_pruning_sound n m c_target L c ℓ s_lo f h_val rfl

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 11: Gray Code Kernel (Claims 4.9, 4.10, 4.11)
-- Source: prompt14_gray_code_kernel.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Claim 4.9: Gray code is a complete bijection over the Cartesian product. -/
-- Source: output (15).lean (UUID: 7753e964) — PROVED
theorem gray_code_bijection {k : ℕ} (r : Fin k → ℕ) (hr : ∀ i, 0 < r i) :
    ∃ (f : Fin (∏ i, r i) → (∀ i : Fin k, Fin (r i))),
      Function.Bijective f := by
  have h_equiv : Nonempty (Fin (∏ i, r i) ≃ (∀ i, Fin (r i))) := by
    refine' ⟨ Fintype.equivOfCardEq _ ⟩ ; aesop;
  exact ⟨ _, Equiv.bijective h_equiv.some ⟩

/-- Claim 4.10: Cross-term split for arbitrary position. -/
-- Source: output (15).lean (UUID: 7753e964) — PROVED
theorem cross_term_split {d : ℕ} (p : ℕ) (hp : 2*p+1 < d)
    (f : Fin d → ℤ) :
    (∑ q : Fin d, if q.1 ≠ 2*p ∧ q.1 ≠ 2*p+1 then f q else 0) =
    (∑ q ∈ (Finset.range (2*p)).attach, f ⟨q.1, Nat.lt_trans (Finset.mem_range.mp q.2) (Nat.lt_trans (Nat.lt_succ_self _) hp)⟩) +
    (∑ q ∈ (Finset.Ico (2*p+2) d).attach, f ⟨q.1, (Finset.mem_Ico.mp q.2).2⟩) := by
  simp +decide [ Finset.sum_ite ];
  convert Finset.sum_union ?_ using 2;
  rotate_left;
  rotate_left;
  rotate_left;
  exact Finset.univ.filter fun x => x.val < 2 * p;
  exact Finset.univ.filter fun x => x.val > 2 * p + 1;
  infer_instance;
  · exact Finset.disjoint_filter.mpr fun _ _ _ _ => by linarith;
  · grind;
  · refine' Finset.sum_bij ( fun x hx => ⟨ x, by linarith [ Finset.mem_range.mp x.2 ] ⟩ ) _ _ _ _ <;> aesop;
  · refine' Finset.sum_bij ( fun x hx => ⟨ x, by linarith [ Finset.mem_Ico.mp x.2 ] ⟩ ) _ _ _ _ <;> aesop

/-- Claim 4.11: W_int correctness under Gray code updates. -/
-- Source: output (15).lean (UUID: 7753e964) — PROVED
theorem w_int_gray_update (lo_bin hi_bin : ℕ) (c c' : ℕ → ℤ)
    (p : ℕ)
    (h_same : ∀ i, i ≠ 2*p ∧ i ≠ 2*p+1 → c' i = c i)
    (W_old : ℤ) (hW : W_old = ∑ i ∈ Finset.Icc lo_bin hi_bin, c i) :
    ∑ i ∈ Finset.Icc lo_bin hi_bin, c' i =
      W_old + (if 2*p ∈ Finset.Icc lo_bin hi_bin then c' (2*p) - c (2*p) else 0)
           + (if (2*p+1) ∈ Finset.Icc lo_bin hi_bin then c' (2*p+1) - c (2*p+1) else 0) := by
  have h_split_sum : ∑ i ∈ Finset.Icc lo_bin hi_bin, c' i = ∑ i ∈ Finset.Icc lo_bin hi_bin, c i + ∑ i ∈ Finset.Icc lo_bin hi_bin, (if i = 2 * p then c' (2 * p) - c (2 * p) else 0) + ∑ i ∈ Finset.Icc lo_bin hi_bin, (if i = 2 * p + 1 then c' (2 * p + 1) - c (2 * p + 1) else 0) := by
    simpa only [ ← Finset.sum_add_distrib ] using Finset.sum_congr rfl fun i hi => by by_cases hi1 : i = 2 * p <;> by_cases hi2 : i = 2 * p + 1 <;> aesop;
  aesop

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 12: Sliding Window and Zero-Bin Skip (Claims 4.12, 4.13)
-- Source: prompt15_sliding_window_and_zero_skip.lean
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Claim 4.12: Sliding window inductive step — W_{s+1} = W_s + A[s+n_cv] - A[s]. -/
-- Source: output (16).lean (UUID: 873cc3c5) — PROVED (with dite indexing)
theorem sliding_window_step {N : ℕ} (A : Fin N → ℤ) (n_cv s : ℕ)
    (hs : s + n_cv < N)
    (W_s : ℤ) (hW : W_s = ∑ k ∈ Finset.Ico s (s + n_cv), if h : k < N then A ⟨k, h⟩ else 0) :
    W_s + A ⟨s + n_cv, hs⟩ - A ⟨s, by omega⟩ =
    ∑ k ∈ Finset.Ico (s + 1) (s + 1 + n_cv), if h : k < N then A ⟨k, h⟩ else 0 := by
  rw [ Finset.sum_Ico_eq_sub _ ] at * <;> norm_num at *;
  rw [ Finset.sum_range_succ ] ; simp +decide [ add_right_comm, *, Finset.sum_range_succ ] ; ring;
  grind +ring

-- Pruning decisions are identical under sliding window (same ws values → same predicate)
-- Source: output (16).lean (UUID: 873cc3c5) — PROVED
theorem sliding_window_pruning_equiv {N : ℕ} (A : Fin N → ℤ)
    (n_cv : ℕ) (threshold : ℤ) (s : ℕ) (hs : s + n_cv ≤ N) :
    (∑ k ∈ Finset.Ico s (s + n_cv), if h : k < N then A ⟨k, h⟩ else 0) > threshold ↔
    (∑ k ∈ Finset.Ico s (s + n_cv), if h : k < N then A ⟨k, h⟩ else 0) > threshold :=
  Iff.rfl

/-- Claim 4.13: Zero term vanishes in products. -/
theorem zero_term_vanishes (a b : ℤ) (hb : b = 0) : a * b = 0 := by
  subst hb; ring

-- Filtering out c_j = 0 terms doesn't change a sum of products
theorem sum_filter_zero {d : ℕ} (c : Fin d → ℤ) (f : Fin d → ℤ) :
    ∑ j : Fin d, c j * f j =
    ∑ j ∈ (Finset.univ.filter fun j => c j ≠ 0), c j * f j := by
  symm
  apply Finset.sum_subset (Finset.filter_subset _ _)
  intro j _ hj
  simp only [Finset.mem_filter, Finset.mem_univ, true_and, not_not] at hj
  simp [hj]

-- Autoconvolution with zero-skip = full autoconvolution
-- Source: output (16).lean (UUID: 873cc3c5) — PROVED
theorem autoconv_zero_skip {d : ℕ} (c : Fin d → ℤ) (t : ℕ) :
    (∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t then c i * c j else 0) =
    (∑ i ∈ (Finset.univ.filter fun i => c i ≠ 0),
      ∑ j ∈ (Finset.univ.filter fun j => c j ≠ 0),
        if i.1 + j.1 = t then c i * c j else 0) := by
  simp +contextual [ Finset.sum_filter ];
  exact Finset.sum_congr rfl fun i hi => by by_cases hi0 : c i = 0 <;> simp +decide [ hi0 ] ; exact Finset.sum_congr rfl fun j hj => by aesop;

-- Cross-term zero-skip: exact for unchanged-bin cross-terms
theorem cross_term_zero_skip {d : ℕ} (c : Fin d → ℤ) (delta : ℤ)
    (S : Finset (Fin d)) :
    (∑ q ∈ S, delta * c q) =
    (∑ q ∈ S.filter (fun q => c q ≠ 0), delta * c q) := by
  symm
  apply Finset.sum_subset (Finset.filter_subset _ _)
  intro q hqS hq
  have hcq : c q = 0 := by
    by_contra h
    exact hq (Finset.mem_filter.mpr ⟨hqS, h⟩)
  simp [hcq]

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 13: Asymmetry Bound (Claim 2.1)
-- Source: output (7).lean (UUID: f31f701e)
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Left-half restriction of f (indicator on (-1/4, 0)). -/
def f_L (f : ℝ → ℝ) : ℝ → ℝ := Set.indicator (Set.Ioo (-1/4 : ℝ) 0) f

theorem f_L_le_f (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x) :
    ∀ x, f_L f x ≤ f x := by
  intros x
  simp [f_L];
  by_cases hx : x ∈ Set.Ioo (-1 / 4 : ℝ) 0 <;> simp [hx, hf]

theorem f_L_supp (f : ℝ → ℝ) :
    Function.support (f_L f) ⊆ Set.Ioo (-1/4 : ℝ) 0 := by
  simp [f_L]

theorem f_L_conv_supp (f : ℝ → ℝ) :
    Function.support (MeasureTheory.convolution (f_L f) (f_L f) (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆
    Set.Ioo (-1/2 : ℝ) 0 := by
  intro x hx; simp_all +decide [ MeasureTheory.convolution ] ;
  have h_support : ∀ t, f_L f t ≠ 0 → -1 / 4 < t ∧ t < 0 := by
    unfold f_L; aesop;
  contrapose! hx;
  rw [ MeasureTheory.integral_eq_zero_of_ae ];
  filter_upwards [ ] with t ; by_cases ht : f_L f t = 0 <;> by_cases ht' : f_L f ( x - t ) = 0 <;> simp_all +decide [ sub_eq_add_neg ];
  linarith [ h_support t ht, h_support ( x + -t ) ht', hx ( by linarith [ h_support t ht, h_support ( x + -t ) ht' ] ) ]

/-- Monotonicity of convolution for nonneg functions. -/
theorem convolution_mono_ae (f g : ℝ → ℝ)
    (hf : ∀ x, 0 ≤ f x) (hg : ∀ x, 0 ≤ g x) (hfg : ∀ x, f x ≤ g x)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    ∀ᵐ x ∂MeasureTheory.volume,
      MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤
      MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  have h_convol_g_exists : ∀ᵐ x ∂MeasureTheory.volume, MeasureTheory.Integrable (fun y => g y * g (x - y)) MeasureTheory.volume := by
    have h_ae_conv : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * g p.2) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
      exact MeasureTheory.Integrable.mul_prod hg_int hg_int;
    have h_ae_conv : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * g (p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
      have h_ae_conv : MeasureTheory.MeasurePreserving (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume) := by
        exact?;
      have h_ae_conv : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * g p.2) (MeasureTheory.Measure.map (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.Measure.prod MeasureTheory.volume MeasureTheory.volume)) := by
        rw [ h_ae_conv.map_eq ] ; assumption;
      rw [ MeasureTheory.integrable_map_measure ] at h_ae_conv ; aesop;
      · exact h_ae_conv.1;
      · exact AEMeasurable.prodMk ( measurable_fst.aemeasurable ) ( measurable_snd.sub measurable_fst |> Measurable.aemeasurable );
    rw [ MeasureTheory.integrable_prod_iff' ] at h_ae_conv ; aesop;
    exact h_ae_conv.1;
  filter_upwards [ h_convol_g_exists ] with x hx;
  refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
  · exact Filter.Eventually.of_forall fun y => mul_nonneg ( hf _ ) ( hf _ );
  · exact hx;
  · filter_upwards [ ] with t using mul_le_mul ( hfg t ) ( hfg ( x - t ) ) ( hf _ ) ( hg _ )

/-- Averaging principle: ‖g‖∞ ≥ (∫g) / measure(support). -/
theorem averaging_principle (g : ℝ → ℝ) (hg : ∀ x, 0 ≤ g x)
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume)
    (S : Set ℝ) (hS : Function.support g ⊆ S)
    (v : ℝ) (hS_meas : MeasureTheory.volume S = ENNReal.ofReal v)
    (hv : 0 < v) :
    MeasureTheory.eLpNorm g ⊤ MeasureTheory.volume ≥
      ENNReal.ofReal (MeasureTheory.integral MeasureTheory.volume g / v) := by
  have h_integral_restrict : ∫ x, g x ∂MeasureTheory.volume = ∫ x in S, g x ∂MeasureTheory.volume := by
    rw [ MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero fun x hx => by_contra fun hx' => hx <| hS <| by aesop ];
  have h_integral_bound : (∫⁻ x in S, ENNReal.ofReal (g x) ∂MeasureTheory.volume) ≤ (MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume) * (MeasureTheory.MeasureSpace.volume S) := by
    have h_integral_bound : ∀ᵐ x ∂MeasureTheory.Measure.restrict MeasureTheory.volume S, ENNReal.ofReal (g x) ≤ MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume := by
      have h_integral_bound : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, ENNReal.ofReal (g x) ≤ MeasureTheory.eLpNorm g ⊤ MeasureTheory.MeasureSpace.volume := by
        have h_integral_bound : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, ‖g x‖ₑ ≤ essSup (fun x => ‖g x‖ₑ) MeasureTheory.MeasureSpace.volume := by
          exact?;
        filter_upwards [ h_integral_bound ] with x hx using le_trans ( by simp +decide [ Real.enorm_eq_ofReal ( hg x ) ] ) hx;
      exact MeasureTheory.ae_restrict_of_ae h_integral_bound;
    refine' le_trans ( MeasureTheory.lintegral_mono_ae h_integral_bound ) _ ; aesop;
  simp_all +decide [ ENNReal.ofReal_div_of_pos hv ];
  rw [ ENNReal.div_le_iff_le_mul ] <;> norm_num [ hv ];
  refine' le_trans _ h_integral_bound;
  rw [ MeasureTheory.ofReal_integral_eq_lintegral_ofReal ];
  · exact hg_int.integrableOn;
  · exact Filter.Eventually.of_forall hg

/-- Integral of convolution = (integral)². -/
theorem integral_convolution_square (f : ℝ → ℝ)
    (hf : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.integral MeasureTheory.volume (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) =
    (MeasureTheory.integral MeasureTheory.volume f) ^ 2 := by
  rw [ sq ];
  apply MeasureTheory.integral_convolution;
  · exact hf;
  · exact hf

theorem f_L_integrable (f : ℝ → ℝ) (hf : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.Integrable (f_L f) MeasureTheory.volume := by
  convert hf.indicator measurableSet_Ioo using 1

theorem convolution_nonneg {f g : ℝ → ℝ} (hf : ∀ x, 0 ≤ f x) (hg : ∀ x, 0 ≤ g x) :
    ∀ x, 0 ≤ MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  intro x
  simp [MeasureTheory.convolution];
  exact MeasureTheory.integral_nonneg fun t => mul_nonneg ( hf t ) ( hg ( x - t ) )

theorem f_L_nonneg (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x) :
    ∀ x, 0 ≤ f_L f x := by
  exact fun x => Set.indicator_nonneg ( fun _ _ => hf _ ) _

theorem volume_Ioo_half :
    MeasureTheory.volume (Set.Ioo (-1/2 : ℝ) 0) = ENNReal.ofReal (1/2) := by
  norm_num

/-- Asymmetry bound: ‖f*f‖∞ ≥ 2L² where L = ∫_{-1/4}^0 f.
    Proof chain: restrict f to left half, use convolution monotonicity,
    then averaging principle on the support of f_L * f_L ⊆ (-1/2, 0). -/
theorem asymmetry_bound (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Icc (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1)
    (h_bdd : MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume ≠ ⊤) :
    let L := MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ioo (-1/4 : ℝ) 0) f)
    (MeasureTheory.eLpNorm (MeasureTheory.convolution f f
      (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal ≥ 2 * L ^ 2 := by
  sorry -- Partial proof in output (7); requires f_L_conv_bound + f_L_conv_integrable (budget-limited)

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 14: Refinement & Support Properties (Claims 2.2, 2.3)
-- Source: output (8).lean (UUID: 8b7ac59c)
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Support of convolution is contained in Minkowski sum of supports. -/
theorem support_convolution_subset_add {f : ℝ → ℝ} {s : Set ℝ} (hf : Function.support f ⊆ s) :
    Function.support (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆ s + s := by
  intro x hx
  obtain ⟨y, hy1, hy2⟩ : ∃ y, f y ≠ 0 ∧ f (x - y) ≠ 0 := by
    contrapose! hx; simp_all +decide [ MeasureTheory.convolution ] ;
    exact MeasureTheory.integral_eq_zero_of_ae <| Filter.Eventually.of_forall fun t => by by_cases h : f t = 0 <;> aesop;
  exact ⟨ y, hf hy1, x - y, hf hy2, by ring ⟩

/-- The boundary between the first n bins and the last n bins is exactly at x = 0. -/
theorem left_frac_exact (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m) :
    let δ := (1 : ℝ) / (4 * n)
    (-1/4 : ℝ) + n * δ = 0 := by
  field_simp [hn]
  ring

/-- Asymmetry threshold can be compared directly — no margin needed. -/
theorem asymmetry_no_margin (c_target : ℝ) (hct : 0 < c_target)
    (L : ℝ) (hL : L ≥ Real.sqrt (c_target / 2))
    (h_bound : ∀ L', 2 * L' ^ 2 ≤ c_target → L' < L) :
    2 * L ^ 2 ≥ c_target := by
  contrapose! h_bound;
  exact ⟨ L, by linarith, le_rfl ⟩

/-- Pointwise convolution integrand inequality for 0 ≤ f ≤ g. -/
theorem convolution_integrand_le {f g : ℝ → ℝ} (hf : 0 ≤ f) (hg : 0 ≤ g) (h_le : f ≤ g) (x t : ℝ) :
    f t * f (x - t) ≤ g t * g (x - t) := by
  exact mul_le_mul ( h_le _ ) ( h_le _ ) ( hf _ ) ( hg _ )

/-- Integral of pointwise-bounded convolution integrands. -/
theorem integral_convolution_le {f g : ℝ → ℝ} (x : ℝ)
    (h_le : ∀ t, f t * f (x - t) ≤ g t * g (x - t))
    (hf_int : MeasureTheory.Integrable (fun t => f t * f (x - t)) MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable (fun t => g t * g (x - t)) MeasureTheory.volume) :
    ∫ t, f t * f (x - t) ∂MeasureTheory.volume ≤ ∫ t, g t * g (x - t) ∂MeasureTheory.volume := by
  apply_rules [ MeasureTheory.integral_mono ]

/-- Measure of support of autoconvolution bounded by 2δ. -/
theorem measure_support_convolution_bound {g : ℝ → ℝ} {a δ : ℝ} (hδ : 0 < δ)
    (hg_supp : Function.support g ⊆ Set.Ioo a (a + δ)) :
    MeasureTheory.volume (Function.support (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume)) ≤ ENNReal.ofReal (2 * δ) := by
  have h_support : Function.support (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆ Set.Ioo (a + a) (a + a + 2 * δ) := by
    intro x hx; have := support_convolution_subset_add hg_supp; simp_all +decide [ Set.subset_def ] ; (
    obtain ⟨ y, hy, z, hz, rfl ⟩ := this x hx; constructor <;> linarith [ hy.1, hy.2, hz.1, hz.2 ] ;);
  exact le_trans ( MeasureTheory.measure_mono h_support ) ( by simp +decide [ two_mul ] )

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 15: Integer Dynamic Threshold (Claims 2.4, 5.1, 5.2)
-- Source: output (5).lean (UUID: d81b0331)
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Integer convolution for exact computation. -/
def conv {d : ℕ} (c : Fin d → ℕ) (k : ℕ) : ℕ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then c i * c j else 0

/-- Window sum of integer convolution. -/
def window_sum {d : ℕ} (c : Fin d → ℕ) (s_lo ℓ : ℕ) : ℕ :=
  ∑ k ∈ Finset.Ico s_lo (s_lo + ℓ - 1), conv c k

/-- Dynamic threshold for pruning. -/
noncomputable def dyn_it (c_target : ℝ) (m n ℓ W_int : ℕ) : ℤ :=
  ⌊(c_target * (m : ℝ)^2 + 1 + 1e-9 * (m : ℝ)^2 + 2 * (W_int : ℝ)) *
   ((ℓ : ℝ) / (4 * (n : ℝ))) * (1 - 4 * 2.22e-16)⌋

/-- Claim 2.4: Computed threshold is conservative (≥ exact threshold). -/
theorem dyn_it_conservative (c_target : ℝ) (m n ℓ W_int : ℕ)
    (hm : 0 < m) (hn : 0 < n) (hℓ : 0 < ℓ) (hW : W_int ≤ m) (hct : 0 ≤ c_target)
    (hct_upper : c_target ≤ 2) (hm_upper : m ≤ 200) :
    let A := (c_target * (m : ℝ)^2 + 1 + 2 * (W_int : ℝ)) * ((ℓ : ℝ) / (4 * (n : ℝ)))
    let B := (c_target * (m : ℝ)^2 + 1 + 1e-9 * (m : ℝ)^2 + 2 * (W_int : ℝ)) *
             ((ℓ : ℝ) / (4 * (n : ℝ))) * (1 - 4 * 2.22e-16)
    ⌊A⌋ ≤ ⌊B⌋ := by
  refine' Int.floor_mono _;
  have h_W_le_m : (W_int : ℝ) ≤ m := by
    norm_cast;
  have h_m_le_200 : (m : ℝ) ≤ 200 := by
    norm_cast;
  field_simp;
  norm_num; nlinarith [ show ( 1 : ℝ ) ≤ m ^ 2 by exact_mod_cast pow_pos hm 2 ] ;

/-- Claim 5.1: Convolution entries bounded by m². -/
theorem conv_bounded {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) (k : ℕ) :
    Finset.univ.sum (fun i => Finset.univ.sum (fun j => if i.1 + j.1 = k then c i * c j else 0)) ≤ m ^ 2 := by
  rw [ ← hc, sq, Finset.sum_mul ];
  exact Finset.sum_le_sum fun i _ => by rw [ Finset.mul_sum _ _ _ ] ; exact Finset.sum_le_sum fun j _ => by split_ifs <;> nlinarith;

/-- Claim 5.2: m² fits in int32 for m ≤ 200 (alternative proof). -/
theorem m_sq_int32_v2 (m : ℕ) (hm : m ≤ 200) : m ^ 2 ≤ 2 ^ 31 - 1 := by
  interval_cases m <;> trivial

/-- Pruning condition predicate. -/
def pruning_condition (ws : ℕ) (threshold : ℤ) : Prop :=
  (ws : ℤ) > threshold

/-- Pruning with computed threshold implies pruning with exact threshold. -/
theorem pruning_soundness (c_target : ℝ) (m n ℓ W_int : ℕ) (ws : ℕ)
    (hm : 0 < m) (hn : 0 < n) (hℓ : 0 < ℓ) (hW : W_int ≤ m) (hct : 0 ≤ c_target)
    (hct_upper : c_target ≤ 2) (hm_upper : m ≤ 200) :
    let A := (c_target * (m : ℝ)^2 + 1 + 2 * (W_int : ℝ)) * ((ℓ : ℝ) / (4 * (n : ℝ)))
    let exact_threshold := ⌊A⌋
    let computed_threshold := dyn_it c_target m n ℓ W_int
    pruning_condition ws computed_threshold → pruning_condition ws exact_threshold := by
  intro A exact_threshold computed_threshold h_pruning
  have h_computed_gt_exact : computed_threshold ≥ exact_threshold := by
    convert dyn_it_conservative c_target m n ℓ W_int hm hn hℓ hW hct hct_upper hm_upper using 1
  exact h_pruning.trans_le' h_computed_gt_exact

/-- Total convolution sum equals m² (Claim 5.1 corollary). -/
theorem conv_total_eq_m_squared {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) :
    ∑ k ∈ Finset.range (2 * d - 1),
      (∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then c i * c j else 0) = m ^ 2 := by
  rw [ sq, ← hc, Finset.sum_comm ];
  have h_simp : ∀ y : Fin d, ∑ x ∈ Finset.range (2 * d - 1), ∑ j : Fin d, (if y + j = x then c y * c j else 0) = ∑ j : Fin d, c y * c j := by
    intro y; rw [ Finset.sum_comm ] ; simp +decide [ Finset.sum_ite ] ;
    rw [ Finset.filter_true_of_mem fun x hx => lt_tsub_iff_left.mpr <| by linarith [ Fin.is_lt y, Fin.is_lt x ] ];
  simp +decide only [h_simp, ← Finset.mul_sum _ _ _, ← Finset.sum_mul]

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 16: Correction Term Support Lemmas
-- Source: output (6).lean (UUID: db9a6f0e)
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Floor division approximation bound. -/
lemma nat_floor_approx (x : ℝ) (m : ℕ) (hm : m > 0) (h : 0 ≤ x) :
    |x / m - (Nat.floor x : ℝ) / m| ≤ 1 / m := by
  field_simp;
  cases abs_cases ( ( x - Nat.floor x ) / ( m : ℝ ) ) <;> nlinarith [ Nat.floor_le h, Nat.lt_floor_add_one x, mul_div_cancel₀ ( x - Nat.floor x ) ( by positivity : ( m : ℝ ) ≠ 0 ) ]

/-- Product approximation error bound. -/
lemma product_approx_error (x1 x2 y1 y2 : ℝ) (hx1 : 0 ≤ x1) (hx2 : 0 ≤ x2) (hy1 : 0 ≤ y1) (hy2 : 0 ≤ y2)
    (h1 : |x1 - y1| ≤ 1) (h2 : |x2 - y2| ≤ 1) :
    |x1 * x2 - y1 * y2| ≤ y1 + y2 + 1 := by
  exact abs_le.mpr ⟨ by nlinarith [ abs_le.mp h1, abs_le.mp h2 ], by nlinarith [ abs_le.mp h1, abs_le.mp h2 ] ⟩

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 17: Essential Supremum Bounds
-- Source: output (14).lean (UUID: 124a8efc)
-- ═══════════════════════════════════════════════════════════════════════════════

/-- eLpNorm equals essSup for nonneg functions. -/
theorem eLpNorm_eq_essSup_ofReal {α : Type*} [MeasureTheory.MeasureSpace α]
    (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) :
    MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume =
    essSup (fun x => ENNReal.ofReal (f x)) MeasureTheory.volume := by
  simp +decide [ MeasureTheory.eLpNormEssSup ];
  simp +decide only [Real.enorm_eq_ofReal (hf _)]

/-- eLpNorm lower bound from integral / measure for nonneg functions. -/
theorem eLpNorm_ge_integral_div_measure_real {α : Type*} [MeasureTheory.MeasureSpace α]
    (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) (S : Set α) (h_supp : Function.support f ⊆ S)
    (hS_fin : MeasureTheory.volume S ≠ ⊤) (hS_pos : MeasureTheory.volume S ≠ 0)
    (hf_int : MeasureTheory.Integrable f MeasureTheory.volume)
    (h_fin : MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume ≠ ⊤) :
    (MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume).toReal ≥
    (MeasureTheory.integral MeasureTheory.volume f) / (MeasureTheory.volume S).toReal := by
      sorry -- Proof in output (14) uses lintegral_le_essSup_mul_measure_ennreal (budget-limited)

-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTION 18: Test Value Bounds and Correction (Claims 1.1, 1.2, 1.3, 1.4)
-- Source: prompts 01, 02, 03
-- ═══════════════════════════════════════════════════════════════════════════════

/-- Step function on the 2n-bin grid. -/
noncomputable def step_function (n m : ℕ) (c : Fin (2 * n) → ℕ) : ℝ → ℝ :=
  fun x =>
    let d := 2 * n
    let δ := 1 / (4 * n : ℝ)
    if x < -1/4 ∨ x ≥ 1/4 then 0
    else
      let i := ⌊(x + 1/4) / δ⌋.toNat
      if h : i < d then (c ⟨i, h⟩ : ℝ) / m
      else 0

/-- Claim 1.1: Test value ≤ ‖f*f‖∞ / (∫f)² for the step function. -/
theorem test_value_le_Linfty (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m) :
    (max_test_value n m c : ℝ) ≤ autoconvolution_ratio (step_function n m c) := by
  sorry

/-- Claim 1.2: Correction term 2/m + 1/m² for discretization error. -/
theorem correction_term (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x)
    (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4))
    (hf_int : MeasureTheory.integral MeasureTheory.volume f = 1) :
    autoconvolution_ratio f ≥
      (max_test_value n m (canonical_discretization f n m) : ℝ) - 2 / m - 1 / m ^ 2 := by
  sorry

/-- Claim 1.4: Contributing bins characterization. -/
-- Source: output (6).lean (UUID: db9a6f0e) — PROVED
theorem contributing_bins_iff (n : ℕ) (hn : n > 0) (ℓ s_lo : ℕ)
    (hℓ : 2 ≤ ℓ) (i : Fin (2 * n)) :
    i ∈ contributing_bins n ℓ s_lo ↔
      Nat.max 0 (s_lo - (2 * n - 1)) ≤ i.1 ∧ i.1 ≤ Nat.min (2 * n - 1) (s_lo + ℓ - 2) := by
  unfold contributing_bins;
  constructor <;> intro h <;> simp_all +decide [ Fin.exists_iff ];
  · grind +ring;
  · exact ⟨ s_lo - i, by omega, by omega, by omega ⟩

/-- Claim 1.3: Dynamic threshold soundness. -/
theorem dynamic_threshold_sound (n m : ℕ) (c_target : ℝ)
    (hn : n > 0) (hm : m > 0) (hct : 0 < c_target)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m)
    (ℓ s_lo : ℕ) (hℓ : 2 ≤ ℓ)
    (W : ℝ) (hW : W = (∑ i ∈ contributing_bins n ℓ s_lo, (c i : ℝ)) / m)
    (h_exceeds : test_value n m c ℓ s_lo > c_target + 1 / m ^ 2 + 2 * W / m) :
    ∀ f : ℝ → ℝ, (∀ x, 0 ≤ f x) →
      Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4) →
      MeasureTheory.integral MeasureTheory.volume f = 1 →
      canonical_discretization f n m = c →
      autoconvolution_ratio f ≥ c_target := by
  sorry

end -- noncomputable section
