/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 873cc3c5-259b-4694-9dbc-eab25a2dfaab

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formal verification of sliding-window scan and zero-bin skipping optimizations (Claims 4.12 and 4.13).
Proves that the sliding window update formula is correct and equivalent to the direct sum, ensuring the pruning predicate is unchanged.
Proves that skipping zero-valued bins in autoconvolution and cross-term updates preserves the computed values.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise

theorem sliding_window_step {N : ℕ} (A : Fin N → ℤ) (n_cv s : ℕ)
    (hs : s + n_cv < N)
    (W_s : ℤ) (hW : W_s = ∑ k ∈ Finset.Ico s (s + n_cv), if h : k < N then A ⟨k, h⟩ else 0) :
    W_s + A ⟨s + n_cv, hs⟩ - A ⟨s, by omega⟩ =
    ∑ k ∈ Finset.Ico (s + 1) (s + 1 + n_cv), if h : k < N then A ⟨k, h⟩ else 0 := by
  rw [ Finset.sum_Ico_eq_sub _ ] at * <;> norm_num at *;
  rw [ Finset.sum_range_succ ] ; simp +decide [ add_right_comm, *, Finset.sum_range_succ ] ; ring;
  grind +ring

theorem sliding_window_pruning_equiv {N : ℕ} (A : Fin N → ℤ)
    (n_cv : ℕ) (threshold : ℤ) (s : ℕ) (hs : s + n_cv ≤ N) :
    (∑ k ∈ Finset.Ico s (s + n_cv), if h : k < N then A ⟨k, h⟩ else 0) > threshold ↔
    (∑ k ∈ Finset.Ico s (s + n_cv), if h : k < N then A ⟨k, h⟩ else 0) > threshold :=
  Iff.rfl

theorem autoconv_zero_skip {d : ℕ} (c : Fin d → ℤ) (t : ℕ) :
    (∑ i : Fin d, ∑ j : Fin d,
      if i.1 + j.1 = t then c i * c j else 0) =
    (∑ i ∈ (Finset.univ.filter fun i => c i ≠ 0),
      ∑ j ∈ (Finset.univ.filter fun j => c j ≠ 0),
        if i.1 + j.1 = t then c i * c j else 0) := by
  simp +contextual [ Finset.sum_filter ];
  exact Finset.sum_congr rfl fun i hi => by by_cases hi0 : c i = 0 <;> simp +decide [ hi0 ] ; exact Finset.sum_congr rfl fun j hj => by aesop;

theorem cross_term_zero_skip {d : ℕ} (c : Fin d → ℤ) (delta : ℤ)
    (S : Finset (Fin d)) :
    (∑ q ∈ S, delta * c q) =
    (∑ q ∈ S.filter (fun q => c q ≠ 0), delta * c q) := by
      -- Since $delta * c q = 0$ for $q \notin S.filter (fun q => c q ≠ 0)$, the sums are equal.
      simp [Finset.sum_filter];
      -- Since $c q = 0$ implies $\delta * c q = 0$, the sums are equal.
      apply Finset.sum_congr rfl
      intro q hq
      aesop

theorem zero_term_vanishes (a b : ℤ) (hb : b = 0) : a * b = 0 := by
  subst hb; ring

theorem sum_filter_zero {d : ℕ} (c : Fin d → ℤ) (f : Fin d → ℤ) :
    ∑ j : Fin d, c j * f j =
    ∑ j ∈ (Finset.univ.filter fun j => c j ≠ 0), c j * f j := by
      -- Since $c_j$ is zero outside the support, the sum over the entire set is equal to the sum over the support.
      simp [Finset.sum_filter];
      -- Since $c_j$ is zero outside the support, the sum over the entire set is equal to the sum over the support. We can split the sum into two parts: the terms where $c_j$ is zero and the terms where it's not.
      apply Finset.sum_congr rfl
      intro j _
      aesop