/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 8b7ac59c-3fe1-407e-a487-2c6ef2a58ae7

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of bin_masses and autoconvolution_ratio as specified in the problem context.
-/
noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) : ℝ :=
  ∫ x in (-1/4 + i / (4 * n : ℝ))..(-1/4 + (i + 1) / (4 * n : ℝ)), f x

noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  (ENNReal.toReal (essSup (fun x => ENNReal.ofReal |conv x|) MeasureTheory.volume)) / (MeasureTheory.integral MeasureTheory.volume f) ^ 2

/-
The support of the convolution f * f is contained in s + s if the support of f is contained in s.
-/
theorem support_convolution_subset_add {f : ℝ → ℝ} {s : Set ℝ} (hf : Function.support f ⊆ s) :
    Function.support (MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆ s + s := by
  -- By definition of convolution, if $x \in \text{supp}(f * f)$, then there exists some $y$ such that $f(y) \neq 0$ and $f(x - y) \neq 0$.
  intro x hx
  obtain ⟨y, hy1, hy2⟩ : ∃ y, f y ≠ 0 ∧ f (x - y) ≠ 0 := by
    contrapose! hx; simp_all +decide [ MeasureTheory.convolution ] ;
    exact MeasureTheory.integral_eq_zero_of_ae <| Filter.Eventually.of_forall fun t => by by_cases h : f t = 0 <;> aesop;
  exact ⟨ y, hf hy1, x - y, hf hy2, by ring ⟩

/-
The ENNReal integral of f is bounded by (essSup f) * (volume s) if supp f is contained in s.
-/
theorem integral_le_essSup_mul_measure_ennreal {f : ℝ → ENNReal} {s : Set ℝ}
    (hf_supp : Function.support f ⊆ s) (hs_meas : MeasurableSet s) :
    ∫⁻ x, f x ∂MeasureTheory.volume ≤ (essSup f MeasureTheory.volume) * (MeasureTheory.volume s) := by
  by_contra! h_contra;
  -- Since $f$ is non-negative and its support is contained in $s$, we have $f \leq \essSup f$ almost everywhere on $s$.
  have h_le_essSup : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume.restrict s, f x ≤ essSup f MeasureTheory.volume := by
    have h_le_essSup : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, f x ≤ essSup f MeasureTheory.volume := by
      exact?;
    exact MeasureTheory.ae_restrict_of_ae h_le_essSup;
  -- Applying the inequality $f(x) \leq \essSup f$ almost everywhere on $s$, we get $\int_s f(x) \, dx \leq \int_s \essSup f \, dx$.
  have h_integral_le_essSup_integral : ∫⁻ x in s, f x ∂MeasureTheory.MeasureSpace.volume ≤ ∫⁻ x in s, essSup f MeasureTheory.MeasureSpace.volume ∂MeasureTheory.MeasureSpace.volume := by
    apply_rules [ MeasureTheory.lintegral_mono_ae ];
  simp_all +decide [ mul_comm ];
  refine' h_contra.not_le ( le_trans _ h_integral_le_essSup_integral );
  rw [ ← MeasureTheory.lintegral_indicator hs_meas ] ; exact MeasureTheory.lintegral_mono fun x => by by_cases hx : f x = 0 <;> aesop;

/-
The boundary between the first n bins and the last n bins is exactly at x = 0.
-/
theorem left_frac_exact (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (hc : ∑ i, c i = m) :
    let δ := (1 : ℝ) / (4 * n)
    -- Boundary of left half is at x = 0 = -1/4 + n * δ
    (-1/4 : ℝ) + n * δ = 0 := by
      -- Substitute δ with 1/(4n) and simplify the expression.
      field_simp [hn]
      ring

/-
Refinement preserves the sum of the left half of the distribution.
-/
theorem refinement_preserves_left_sum (n : ℕ) (hn : n > 0)
    (parent : Fin (2 * n) → ℕ) (a : Fin (2 * n) → ℕ)
    (ha : ∀ i, a i ≤ parent i)
    (child : Fin (4 * n) → ℕ)
    (hc_even : ∀ i : Fin (2 * n), child ⟨2 * i.1, by omega⟩ = a i)
    (hc_odd : ∀ i : Fin (2 * n), child ⟨2 * i.1 + 1, by omega⟩ = parent i - a i) :
    ∑ j : Fin (2 * n), (child ⟨j.1, by omega⟩ : ℕ) = ∑ i : Fin n, (parent ⟨i.1, by omega⟩ : ℕ) := by
  -- By definition of child, we can split the sum into the sum over even indices and the sum over odd indices.
  have h_split : ∑ j : Fin (2 * n), child ⟨j.val, by
    linarith [ Fin.is_lt j ]⟩ = ∑ i : Fin n, (child ⟨2 * i, by
    linarith [ Fin.is_lt i ]⟩ + child ⟨2 * i + 1, by
    linarith [ Fin.is_lt i ]⟩) := by
    have h_split : Finset.range (2 * n) = Finset.image (fun i => 2 * i) (Finset.range n) ∪ Finset.image (fun i => 2 * i + 1) (Finset.range n) := by
      ext i
      simp [Finset.mem_range, Finset.mem_image];
      exact ⟨ fun hi => by rcases Nat.even_or_odd' i with ⟨ k, rfl | rfl ⟩ <;> [ left; right ] <;> exact ⟨ k, by linarith, rfl ⟩, fun hi => by rcases hi with ( ⟨ k, hk, rfl ⟩ | ⟨ k, hk, rfl ⟩ ) <;> linarith ⟩
    generalize_proofs at *;
    rw [ Finset.sum_fin_eq_sum_range ];
    rw [ h_split, Finset.sum_union ] <;> norm_num [ Finset.sum_add_distrib ];
    · norm_num [ Finset.sum_range, Nat.lt_succ_iff ];
      grind;
    · norm_num [ Finset.disjoint_right ];
      intros; omega;
  generalize_proofs at *;
  grind

/-
If 2 * L'^2 <= c_target implies L' < L, then 2 * L^2 >= c_target.
-/
theorem asymmetry_no_margin (c_target : ℝ) (hct : 0 < c_target)
    (L : ℝ) (hL : L ≥ Real.sqrt (c_target / 2))
    (h_bound : ∀ L', 2 * L' ^ 2 ≤ c_target → L' < L) :
    2 * L ^ 2 ≥ c_target := by
  contrapose! h_bound;
  exact ⟨ L, by linarith, le_rfl ⟩

/-
If 0 <= f <= g, then f(t)f(x-t) <= g(t)g(x-t).
-/
theorem convolution_integrand_le {f g : ℝ → ℝ} (hf : 0 ≤ f) (hg : 0 ≤ g) (h_le : f ≤ g) (x t : ℝ) :
    f t * f (x - t) ≤ g t * g (x - t) := by
  exact mul_le_mul ( h_le _ ) ( h_le _ ) ( hf _ ) ( hg _ )

/-
If the integrand of the convolution of f is less than or equal to the integrand of the convolution of g, then the convolution of f is less than or equal to the convolution of g at x.
-/
theorem integral_convolution_le {f g : ℝ → ℝ} (x : ℝ)
    (h_le : ∀ t, f t * f (x - t) ≤ g t * g (x - t))
    (hf_int : MeasureTheory.Integrable (fun t => f t * f (x - t)) MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable (fun t => g t * g (x - t)) MeasureTheory.volume) :
    ∫ t, f t * f (x - t) ∂MeasureTheory.volume ≤ ∫ t, g t * g (x - t) ∂MeasureTheory.volume := by
  apply_rules [ MeasureTheory.integral_mono ]

/-
If 0 <= f <= g and the convolutions are defined at x, then (f * f)(x) <= (g * g)(x).
-/
theorem convolution_le_of_le {f g : ℝ → ℝ} (x : ℝ) (hf : 0 ≤ f) (hg : 0 ≤ g) (h_le : f ≤ g)
    (hf_int : MeasureTheory.Integrable (fun t => f t * f (x - t)) MeasureTheory.volume)
    (hg_int : MeasureTheory.Integrable (fun t => g t * g (x - t)) MeasureTheory.volume) :
    MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ≤
    MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x := by
  convert integral_convolution_le x _ hf_int hg_int using 1;
  exact?

/-
The integral of the convolution of g with itself is the square of the integral of g.
-/
theorem integral_convolution_eq_sq_integral {g : ℝ → ℝ}
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    ∫ x, MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x ∂MeasureTheory.volume =
    (∫ x, g x ∂MeasureTheory.volume) ^ 2 := by
  rw [ sq, MeasureTheory.integral_congr_ae ];
  any_goals exact fun x => ∫ y, g y * g ( x - y ) ∂MeasureTheory.MeasureSpace.volume;
  · rw [ ← MeasureTheory.integral_integral_swap ];
    · simp +decide only [MeasureTheory.integral_const_mul, MeasureTheory.integral_sub_right_eq_self];
      rw [ MeasureTheory.integral_mul_const ];
    · have h_conv : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * g p.2) (MeasureTheory.MeasureSpace.volume.prod MeasureTheory.MeasureSpace.volume) := by
        exact hg_int.prod_mul hg_int;
      -- The transformation $(x, y) \mapsto (x, y - x)$ is measure-preserving.
      have h_measure_preserving : MeasureTheory.MeasurePreserving (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.MeasureSpace.volume.prod MeasureTheory.MeasureSpace.volume) (MeasureTheory.MeasureSpace.volume.prod MeasureTheory.MeasureSpace.volume) := by
        exact?;
      have h_integrable : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * g p.2) (MeasureTheory.Measure.map (fun p : ℝ × ℝ => (p.1, p.2 - p.1)) (MeasureTheory.MeasureSpace.volume.prod MeasureTheory.MeasureSpace.volume)) := by
        rw [ h_measure_preserving.map_eq ] ; exact h_conv;
      rw [ MeasureTheory.integrable_map_measure ] at h_integrable ; aesop;
      · exact h_integrable.1;
      · exact AEMeasurable.prodMk ( measurable_fst.aemeasurable ) ( measurable_snd.sub measurable_fst |> Measurable.aemeasurable );
  · exact Filter.Eventually.of_forall fun x => rfl

/-
The measure of the support of the convolution of g with itself is at most 2 * delta.
-/
theorem measure_support_convolution_bound {g : ℝ → ℝ} {a δ : ℝ} (hδ : 0 < δ)
    (hg_supp : Function.support g ⊆ Set.Ioo a (a + δ)) :
    MeasureTheory.volume (Function.support (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume)) ≤ ENNReal.ofReal (2 * δ) := by
  -- The support of the convolution of $g$ with itself is contained in the sum of the supports of $g$ and $g$, which is $(a + a, a + \delta + a + \delta) = (2a, 2a + 2\delta)$.
  have h_support : Function.support (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆ Set.Ioo (a + a) (a + a + 2 * δ) := by
    intro x hx; have := support_convolution_subset_add hg_supp; simp_all +decide [ Set.subset_def ] ; (
    obtain ⟨ y, hy, z, hz, rfl ⟩ := this x hx; constructor <;> linarith [ hy.1, hy.2, hz.1, hz.2 ] ;);
  exact le_trans ( MeasureTheory.measure_mono h_support ) ( by simp +decide [ two_mul ] )

/-
The ENNReal integral of the convolution of g with itself is bounded by its essential supremum times 2 * delta.
-/
theorem ennreal_inequality_for_convolution {g : ℝ → ℝ} {a δ : ℝ} (hδ : 0 < δ)
    (hg_nonneg : 0 ≤ g)
    (hg_supp : Function.support g ⊆ Set.Ioo a (a + δ)) :
    ∫⁻ x, ENNReal.ofReal (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x) ∂MeasureTheory.volume ≤
    (essSup (fun x => ENNReal.ofReal (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x)) MeasureTheory.volume) * ENNReal.ofReal (2 * δ) := by
  have h_support : Function.support (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume) ⊆ Set.Ioo (2 * a) (2 * a + 2 * δ) := by
    intro x hx; have := support_convolution_subset_add hg_supp; simp_all +decide [ Set.subset_def ] ; (
    rcases this x hx with ⟨ y, hy, z, hz, rfl ⟩ ; constructor <;> linarith [ hy.1, hy.2, hz.1, hz.2 ] ;);
  have := @integral_le_essSup_mul_measure_ennreal ( fun x => ENNReal.ofReal ( MeasureTheory.convolution g g ( ContinuousLinearMap.mul ℝ ℝ ) MeasureTheory.MeasureSpace.volume x ) ) ( Set.Ioo ( 2 * a ) ( 2 * a + 2 * δ ) ) ?_ ?_ <;> norm_num at *;
  · convert this using 1;
  · exact fun x hx => h_support x <| ne_of_gt hx

/-
The ENNReal essential supremum of the convolution is at least (integral g)^2 / (2 * delta).
-/
theorem essSup_convolution_lower_bound_ennreal {g : ℝ → ℝ} {a δ : ℝ} (hδ : 0 < δ)
    (hg_nonneg : 0 ≤ g)
    (hg_supp : Function.support g ⊆ Set.Ioo a (a + δ))
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume) :
    essSup (fun x => ENNReal.ofReal (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x)) MeasureTheory.volume ≥
    ENNReal.ofReal ((MeasureTheory.integral MeasureTheory.volume g) ^ 2 / (2 * δ)) := by
  -- By the properties of integrals and essential suprema, we know that
  have h_integral_le_essSup_mul_measure : (ENNReal.ofReal ((MeasureTheory.integral MeasureTheory.volume g) ^ 2)) ≤ (essSup (fun x => ENNReal.ofReal (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x)) MeasureTheory.volume) * (ENNReal.ofReal (2 * δ)) := by
    have := @ennreal_inequality_for_convolution g a δ hδ hg_nonneg hg_supp;
    convert this using 1;
    rw [ ← MeasureTheory.ofReal_integral_eq_lintegral_ofReal ];
    · rw [ integral_convolution_eq_sq_integral hg_int ];
    · exact?;
    · filter_upwards [ ] with x using MeasureTheory.integral_nonneg fun t => mul_nonneg ( hg_nonneg _ ) ( hg_nonneg _ );
  rw [ ENNReal.ofReal_div_of_pos ];
  · exact ENNReal.div_le_of_le_mul <| h_integral_le_essSup_mul_measure.trans_eq <| by rw [ mul_comm ] ;
  · positivity

/-
If the essential supremum of the convolution is finite, then it is lower bounded by (integral g)^2 / (2 * delta).
-/
theorem essSup_convolution_lower_bound {g : ℝ → ℝ} {a δ : ℝ} (hδ : 0 < δ)
    (hg_nonneg : 0 ≤ g)
    (hg_supp : Function.support g ⊆ Set.Ioo a (a + δ))
    (hg_int : MeasureTheory.Integrable g MeasureTheory.volume)
    (h_essSup_ne_top : essSup (fun x => ENNReal.ofReal (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x)) MeasureTheory.volume ≠ ⊤) :
    ENNReal.toReal (essSup (fun x => ENNReal.ofReal (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x)) MeasureTheory.volume) ≥
    (MeasureTheory.integral MeasureTheory.volume g) ^ 2 / (2 * δ) := by
  have h_lower_bound : essSup (fun x => ENNReal.ofReal (MeasureTheory.convolution g g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume x)) MeasureTheory.volume ≥ ENNReal.ofReal ((MeasureTheory.integral MeasureTheory.volume g) ^ 2 / (2 * δ)) := by
    apply essSup_convolution_lower_bound_ennreal hδ hg_nonneg hg_supp hg_int;
  rw [ ge_iff_le, ENNReal.ofReal_le_iff_le_toReal ] at h_lower_bound <;> aesop