/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: db9a6f0e-8909-499e-9e54-9ce840a0b36d

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Characterization of contributing bins.
-/
def contributing_bins (n ℓ s_lo : ℕ) : Finset (Fin (2 * n)) :=
  Finset.univ.filter fun i => ∃ j : Fin (2 * n), s_lo ≤ (i : ℕ) + j ∧ (i : ℕ) + j ≤ s_lo + ℓ - 2

theorem contributing_bins_iff (n : ℕ) (hn : n > 0) (ℓ s_lo : ℕ)
    (hℓ : 2 ≤ ℓ) (i : Fin (2 * n)) :
    i ∈ contributing_bins n ℓ s_lo ↔
      Nat.max 0 (s_lo - (2 * n - 1)) ≤ i.1 ∧ i.1 ≤ Nat.min (2 * n - 1) (s_lo + ℓ - 2) := by
  unfold contributing_bins;
  constructor <;> intro h <;> simp_all +decide [ Fin.exists_iff ];
  · grind +ring;
  · exact ⟨ s_lo - i, by omega, by omega, by omega ⟩

/-
Discrete convolution of a composition c.
-/
def discrete_convolution (n : ℕ) (c : Fin (2 * n) → ℕ) (k : ℕ) : ℕ :=
  Finset.sum Finset.univ fun i => Finset.sum Finset.univ fun j => if i.1 + j.1 = k then c i * c j else 0

/-
Definition of test value.
-/
def test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) : ℝ :=
  (1 / (4 * n * ℓ : ℝ)) * Finset.sum (Finset.Icc s_lo (s_lo + ℓ - 2)) fun k => (discrete_convolution n c k : ℝ)

/-
Definition of bin mass.
-/
def bin_mass (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) : ℝ :=
  ∫ x in Set.Ico (-1/4 + (i : ℝ) / (4 * n : ℝ)) (-1/4 + ((i : ℝ) + 1) / (4 * n : ℝ)), f x

/-
Definition of canonical discretization.
-/
def canonical_discretization (f : ℝ → ℝ) (n m : ℕ) : Fin (2 * n) → ℕ :=
  fun i => Nat.floor (m * bin_mass f n i)

/-
Definition of autoconvolution ratio.
-/
noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  (MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.lsmul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal / (∫ x, f x) ^ 2

/-
Definition of continuous test value.
-/
noncomputable def continuous_test_value (f : ℝ → ℝ) (n ℓ s_lo : ℕ) : ℝ :=
  (4 * n / ℓ : ℝ) * ∫ x in Set.Icc (-0.5 + s_lo / (4 * n : ℝ)) (-0.5 + (s_lo + ℓ - 2) / (4 * n : ℝ)), (MeasureTheory.convolution f f (ContinuousLinearMap.lsmul ℝ ℝ) MeasureTheory.volume) x

/-
Definition of autoconvolution ratio using ENNReal.
-/
noncomputable def autoconvolution_ratio_enn (f : ℝ → ℝ) : ENNReal :=
  (MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.lsmul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume) / (ENNReal.ofReal (∫ x, f x) ^ 2)

/-
Definition of continuous test value using ENNReal.
-/
noncomputable def continuous_test_value_enn (f : ℝ → ℝ) (n ℓ s_lo : ℕ) : ENNReal :=
  (4 * n / ℓ : ENNReal) * ∫⁻ x in Set.Icc (-0.5 + s_lo / (4 * n : ℝ)) (-0.5 + (s_lo + ℓ - 2) / (4 * n : ℝ)), ENNReal.ofReal ((MeasureTheory.convolution f f (ContinuousLinearMap.lsmul ℝ ℝ) MeasureTheory.volume) x)

/-
Integral is bounded by essential supremum times measure (ENNReal version).
-/
lemma integral_le_essSup_mul_measure_ennreal {α : Type*} [MeasureTheory.MeasureSpace α]
    (f : α → ENNReal) (s : Set α) (h_meas : MeasurableSet s) :
    ∫⁻ x in s, f x ≤ (MeasureTheory.eLpNorm f ⊤ MeasureTheory.volume) * (MeasureTheory.volume s) := by
  -- By definition of essential supremum, we know that for any $M > \text{ess sup}(f)$, there exists a set $s'$ with measure zero such that $|f(x)| \leq M$ for all $x \notin s'$.
  have h_ess_sup : ∀ᵐ x ∂MeasureTheory.MeasureSpace.volume, f x ≤ MeasureTheory.eLpNorm f ⊤ MeasureTheory.MeasureSpace.volume := by
    exact?;
  refine' le_trans ( MeasureTheory.lintegral_mono_ae _ ) _;
  exacts [ fun _ => MeasureTheory.eLpNorm f ⊤ MeasureTheory.MeasureSpace.volume, MeasureTheory.ae_restrict_of_ae h_ess_sup, by simp +decide [ mul_comm ] ]

/-
Definition of scaled continuous test value.
-/
noncomputable def continuous_test_value_scaled (f : ℝ → ℝ) (n m ℓ s_lo : ℕ) : ℝ :=
  (m ^ 2 / (4 * n * ℓ : ℝ)) * ∫ x in Set.Icc (-0.5 + s_lo / (4 * n : ℝ)) (-0.5 + (s_lo + ℓ - 2) / (4 * n : ℝ)), (MeasureTheory.convolution f f (ContinuousLinearMap.lsmul ℝ ℝ) MeasureTheory.volume) x

/-
Approximation property of natural floor division.
-/
lemma nat_floor_approx (x : ℝ) (m : ℕ) (hm : m > 0) (h : 0 ≤ x) :
    |x / m - (Nat.floor x : ℝ) / m| ≤ 1 / m := by
  field_simp;
  cases abs_cases ( ( x - Nat.floor x ) / ( m : ℝ ) ) <;> nlinarith [ Nat.floor_le h, Nat.lt_floor_add_one x, mul_div_cancel₀ ( x - Nat.floor x ) ( by positivity : ( m : ℝ ) ≠ 0 ) ]

/-
Final definitions for test values.
-/
def discrete_convolution_real (n : ℕ) (μ : Fin (2 * n) → ℝ) (k : ℕ) : ℝ :=
  Finset.sum Finset.univ fun i => Finset.sum Finset.univ fun j => if i.1 + j.1 = k then μ i * μ j else 0

def test_value_final (n m : ℕ) (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) : ℝ :=
  (1 / (4 * n * ℓ : ℝ)) * Finset.sum (Finset.Icc s_lo (s_lo + ℓ - 2)) fun k => (discrete_convolution n c k : ℝ)

noncomputable def continuous_test_value_final (f : ℝ → ℝ) (n m ℓ s_lo : ℕ) : ℝ :=
  (m ^ 2 / (4 * n * ℓ : ℝ)) * ∫ x in Set.Icc (-0.5 + s_lo / (4 * n : ℝ)) (-0.5 + (s_lo + ℓ - 2) / (4 * n : ℝ)), (MeasureTheory.convolution f f (ContinuousLinearMap.lsmul ℝ ℝ) MeasureTheory.volume) x

noncomputable def exact_discrete_test_value_final (f : ℝ → ℝ) (n m ℓ s_lo : ℕ) : ℝ :=
  (1 / (4 * n * ℓ : ℝ)) * Finset.sum (Finset.Icc s_lo (s_lo + ℓ - 2)) fun k => (discrete_convolution_real n (fun i => m * bin_mass f n i) k)

/-
Bound on the error of a product of approximated values.
-/
lemma product_approx_error (x1 x2 y1 y2 : ℝ) (hx1 : 0 ≤ x1) (hx2 : 0 ≤ x2) (hy1 : 0 ≤ y1) (hy2 : 0 ≤ y2)
    (h1 : |x1 - y1| ≤ 1) (h2 : |x2 - y2| ≤ 1) :
    |x1 * x2 - y1 * y2| ≤ y1 + y2 + 1 := by
  exact abs_le.mpr ⟨ by nlinarith [ abs_le.mp h1, abs_le.mp h2 ], by nlinarith [ abs_le.mp h1, abs_le.mp h2 ] ⟩

/-
Bound on the sum of errors for contributing bins (corrected hypotheses).
-/
lemma sum_error_bound (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) (hℓ : 2 ≤ ℓ) (W : ℝ)
    (hW : W = (∑ i ∈ contributing_bins n ℓ s_lo, (c i : ℝ)) / m) :
    ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), ∑ i ∈ Finset.univ, ∑ j ∈ Finset.univ, (if i.1 + j.1 = k then (c i : ℝ) + (c j : ℝ) + 1 else 0) ≤ 2 * (ℓ - 1) * m * W + (ℓ - 1) * (contributing_bins n ℓ s_lo).card := by
  -- The sum is over triples $(k, i, j)$ such that $i+j=k$ and $k \in [s_{lo}, s_{lo}+\ell-2]$.
  -- This is equivalent to summing over pairs $(i,j)$ such that $i+j \in [s_{lo}, s_{lo}+\ell-2]$.
  have h_sum_pairs : ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), ∑ i : Fin (2 * n), ∑ j : Fin (2 * n), (if i.val + j.val = k then (c i : ℝ) + (c j : ℝ) + 1 else 0) = ∑ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then (c i : ℝ) + (c j : ℝ) + 1 else 0) := by
    rw [ ← Finset.sum_product' ];
    rw [ ← Finset.sum_product' ];
    rw [ ← Finset.sum_product' ];
    rw [ ← Finset.sum_filter ];
    rw [ ← Finset.sum_filter ] ; refine' Finset.sum_bij ( fun x hx => ( x.1.2, x.2 ) ) _ _ _ _ <;> simp +decide ;
    · intro a b c ha hb hab; simp_all +decide [ contributing_bins ] ;
      exact ⟨ ⟨ c, by linarith, by linarith ⟩, ⟨ b, by linarith, by linarith ⟩ ⟩;
    · aesop;
    · tauto;
  -- For each such pair, we sum $c_i + c_j + 1$.
  have h_sum_pairs_bound : ∑ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then (c i : ℝ) + (c j : ℝ) + 1 else 0) ≤ ∑ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then (c i : ℝ) else 0) + ∑ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then (c j : ℝ) else 0) + ∑ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then 1 else 0) := by
    simpa only [ ← Finset.sum_add_distrib ] using Finset.sum_le_sum fun i hi => Finset.sum_le_sum fun j hj => by split_ifs <;> linarith;
  -- The number of $j$ is at most $\ell-1$.
  have h_num_j : ∀ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then (1 : ℝ) else 0) ≤ (ℓ - 1) := by
    intro i hi
    have h_num_j : Finset.card (Finset.filter (fun j : Fin (2 * n) => i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2)) (contributing_bins n ℓ s_lo)) ≤ ℓ - 1 := by
      have h_num_j_bound : Finset.card (Finset.image (fun j : Fin (2 * n) => j.val) (Finset.filter (fun j : Fin (2 * n) => i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2)) (contributing_bins n ℓ s_lo))) ≤ ℓ - 1 := by
        have h_num_j_bound : Finset.image (fun j : Fin (2 * n) => j.val) (Finset.filter (fun j : Fin (2 * n) => i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2)) (contributing_bins n ℓ s_lo)) ⊆ Finset.Icc (Nat.max 0 (s_lo - i.val)) (Nat.min (2 * n - 1) (s_lo + ℓ - 2 - i.val)) := by
          simp +decide [ Finset.subset_iff ];
          rintro x j hj₁ hj₂ hj₃ rfl; exact ⟨ by linarith, Nat.le_sub_one_of_lt <| Fin.is_lt j, Nat.le_sub_of_add_le <| by linarith ⟩ ;
        refine le_trans ( Finset.card_le_card h_num_j_bound ) ?_ ; norm_num +zetaDelta at *; (
        cases le_total ( s_lo + ℓ - 2 - i ) ( 2 * n - 1 ) <;> simp +decide [ * ];
        · omega;
        · omega);
      rwa [ Finset.card_image_of_injective _ fun x y hxy => by simpa [ Fin.ext_iff ] using hxy ] at h_num_j_bound
    simp [h_num_j] at *; (
    exact le_trans ( Nat.cast_le.mpr h_num_j ) ( by rw [ Nat.cast_pred ] ; linarith ) ;);
  -- Applying the bound on the number of $j$ to each term in the sum.
  have h_sum_pairs_bound' : ∑ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then (c i : ℝ) else 0) ≤ (ℓ - 1) * ∑ i ∈ contributing_bins n ℓ s_lo, (c i : ℝ) ∧ ∑ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then (c j : ℝ) else 0) ≤ (ℓ - 1) * ∑ i ∈ contributing_bins n ℓ s_lo, (c i : ℝ) := by
    constructor <;> rw [ Finset.mul_sum _ _ _ ];
    · exact Finset.sum_le_sum fun i hi => by simpa [ Finset.sum_ite ] using mul_le_mul_of_nonneg_right ( h_num_j i hi ) ( Nat.cast_nonneg _ ) ;
    · rw [ Finset.sum_comm ];
      exact Finset.sum_le_sum fun i hi => by simpa [ add_comm, Finset.sum_ite ] using mul_le_mul_of_nonneg_right ( h_num_j i hi ) ( Nat.cast_nonneg ( c i ) ) ;
  -- Applying the bound on the number of $j$ to the third term in the sum.
  have h_sum_pairs_bound'' : ∑ i ∈ contributing_bins n ℓ s_lo, ∑ j ∈ contributing_bins n ℓ s_lo, (if i.val + j.val ∈ Finset.Icc s_lo (s_lo + ℓ - 2) then (1 : ℝ) else 0) ≤ (ℓ - 1) * (contributing_bins n ℓ s_lo).card := by
    convert Finset.sum_le_sum h_num_j using 1 ; norm_num [ mul_comm ];
    ring;
  rw [ hW ] ; nlinarith [ show ( m : ℝ ) > 0 by positivity, mul_div_cancel₀ ( ∑ i ∈ contributing_bins n ℓ s_lo, ( c i : ℝ ) ) ( by positivity : ( m : ℝ ) ≠ 0 ) ] ;