/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ca2199a4-f9ec-431a-80dc-429d498d8afa

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  let conv := MeasureTheory.convolution f f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume
  let norm_inf := (MeasureTheory.eLpNorm conv ⊤ MeasureTheory.volume).toReal
  let integral := MeasureTheory.integral MeasureTheory.volume f
  norm_inf / (integral ^ 2)

noncomputable def autoconvolution_constant : ℝ :=
  sInf {r : ℝ | ∃ (f : ℝ → ℝ), (∀ x, 0 ≤ f x) ∧ (Function.support f ⊆ Set.Ioo (-1/4) (1/4)) ∧ r = autoconvolution_ratio f}

def discrete_autoconvolution {d : ℕ} (a : Fin d → ℝ) (k : ℕ) : ℝ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then a i * a j else 0

noncomputable def test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) (ℓ s_lo : ℕ) : ℝ :=
  let d := 2 * n
  let a : Fin d → ℝ := fun i => (4 * n : ℝ) / m * (c i : ℝ)
  let conv := discrete_autoconvolution a
  let sum_conv := ∑ k ∈ Finset.Icc s_lo (s_lo + ℓ - 2), conv k
  (1 / (4 * n * ℓ : ℝ)) * sum_conv

noncomputable def max_test_value (n m : ℕ) (c : Fin (2 * n) → ℕ) : ℝ :=
  let d := 2 * n
  let range_ell := Finset.Icc 2 (2 * d)
  let range_s_lo := Finset.range (2 * d) -- Sufficient range to cover the convolution
  let values := range_ell.biUnion (fun ℓ => range_s_lo.image (fun s_lo => test_value n m c ℓ s_lo))
  if h : values.Nonempty then values.max' h else 0

def is_composition (n m : ℕ) (c : Fin (2 * n) → ℕ) : Prop :=
  ∑ i, c i = m

noncomputable def bin_masses (f : ℝ → ℝ) (n : ℕ) : Fin (2 * n) → ℝ :=
  fun i =>
    let δ := 1 / (4 * n : ℝ)
    let a := -(1/4 : ℝ) + i * δ
    let b := -(1/4 : ℝ) + (i + 1) * δ
    MeasureTheory.integral MeasureTheory.volume (Set.indicator (Set.Ico a b) f)

noncomputable def canonical_discretization (f : ℝ → ℝ) (n m : ℕ) : Fin (2 * n) → ℕ :=
  fun i =>
    let masses := bin_masses f n
    let total_mass := ∑ j, masses j
    let cum_mass (k : ℕ) := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
    let target_cum (k : ℕ) := (cum_mass k) / total_mass * m
    let discrete_cum (k : ℕ) := ⌊target_cum k⌋.natAbs
    if i.1 + 1 < 2 * n then discrete_cum (i.1 + 1) - discrete_cum i.1
    else m - discrete_cum i.1

def contributing_bins (n : ℕ) (ℓ s_lo : ℕ) : Finset (Fin (2 * n)) :=
  let d := 2 * n
  Finset.filter (fun i => ∃ j : Fin d, s_lo ≤ i.1 + j.1 ∧ i.1 + j.1 ≤ s_lo + ℓ - 2) Finset.univ

noncomputable def canonical_cumulative_distribution (f : ℝ → ℝ) (n m : ℕ) (k : ℕ) : ℕ :=
  let masses := bin_masses f n
  let total_mass := ∑ j, masses j
  let cum_mass := ∑ j : Fin (2 * n), if j.1 < k then masses j else 0
  let target_cum := cum_mass / total_mass * m
  ⌊target_cum⌋.natAbs

theorem canonical_discretization_eq (f : ℝ → ℝ) (n m : ℕ) (i : Fin (2 * n)) :
    canonical_discretization f n m i =
    if i.1 + 1 < 2 * n then
      canonical_cumulative_distribution f n m (i.1 + 1) - canonical_cumulative_distribution f n m i.1
    else
      m - canonical_cumulative_distribution f n m i.1 := by
        unfold canonical_discretization canonical_cumulative_distribution;
        simp +zetaDelta at *

theorem canonical_cumulative_distribution_zero (f : ℝ → ℝ) (n m : ℕ) :
    canonical_cumulative_distribution f n m 0 = 0 := by
      unfold canonical_cumulative_distribution; aesop;

theorem canonical_cumulative_distribution_2n (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_pos : ∑ j : Fin (2 * n), bin_masses f n j ≠ 0) :
    canonical_cumulative_distribution f n m (2 * n) = m := by
      unfold canonical_cumulative_distribution; aesop;

theorem bin_masses_nonneg (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n : ℕ) (i : Fin (2 * n)) :
    0 ≤ bin_masses f n i := by
      apply_rules [ MeasureTheory.integral_nonneg, Set.indicator_nonneg ] ; aesop

theorem canonical_discretization_sum_zero_mass (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_zero : ∑ j : Fin (2 * n), bin_masses f n j = 0) :
    ∑ i : Fin (2 * n), canonical_discretization f n m i = m := by
      rw [ Finset.sum_eq_single ⟨ 2 * n - 1, Nat.sub_lt ( by positivity ) ( by positivity ) ⟩ ] <;> norm_num [ canonical_discretization ];
      · rw [ Nat.sub_add_cancel ( by linarith ) ] ; aesop;
      · simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg, bin_masses_nonneg ];
        exact fun i hi₁ hi₂ => False.elim <| hi₁ <| Fin.ext <| by linarith [ Fin.is_lt i, Nat.sub_add_cancel <| show 1 ≤ 2 * n from by linarith ] ;

theorem canonical_discretization_eq_diff (f : ℝ → ℝ) (n m : ℕ)
    (h_D_2n : canonical_cumulative_distribution f n m (2 * n) = m) (i : Fin (2 * n)) :
    canonical_discretization f n m i = canonical_cumulative_distribution f n m (i.1 + 1) - canonical_cumulative_distribution f n m i.1 := by
      convert canonical_discretization_eq f n m i using 1;
      grind

theorem sum_fin_telescope {M : Type*} [AddCommGroup M] (f : ℕ → M) (n : ℕ) :
    ∑ i : Fin n, (f (i + 1) - f i) = f n - f 0 := by
      convert Finset.sum_range_sub ( fun i => f i ) n using 1;
      rw [ Finset.sum_range ]

theorem canonical_cumulative_distribution_mono (f : ℝ → ℝ) (hf_nonneg : ∀ x, 0 ≤ f x) (n m : ℕ) :
    Monotone (canonical_cumulative_distribution f n m) := by
      -- Since the sum of non-negative terms is non-negative, the floor of that sum is also non-negative.
      have h_floor_nonneg : ∀ k l : ℕ, k ≤ l → ⌊(∑ j : Fin (2 * n), if j.1 < k then bin_masses f n j else 0) / (∑ j : Fin (2 * n), bin_masses f n j) * m⌋ ≤ ⌊(∑ j : Fin (2 * n), if j.1 < l then bin_masses f n j else 0) / (∑ j : Fin (2 * n), bin_masses f n j) * m⌋ := by
        intros k l hkl
        have h_sum_le : (∑ j : Fin (2 * n), if j.1 < k then bin_masses f n j else 0) ≤ (∑ j : Fin (2 * n), if j.1 < l then bin_masses f n j else 0) := by
          exact Finset.sum_le_sum fun i _ => by split_ifs <;> linarith [ show 0 ≤ bin_masses f n i from by exact MeasureTheory.integral_nonneg fun x => by exact Set.indicator_nonneg ( fun x hx => hf_nonneg x ) _ ] ;
        gcongr;
        exact Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _;
      intro k l hkl; specialize h_floor_nonneg k l hkl; simp_all +decide [ canonical_cumulative_distribution ] ;
      rw [ ← Int.ofNat_le, Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr _ ), Int.natAbs_of_nonneg ( Int.floor_nonneg.mpr _ ) ];
      · convert h_floor_nonneg using 1;
      · exact mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact bin_masses_nonneg f hf_nonneg n _ ; norm_num ] ) ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _ ) ) ( Nat.cast_nonneg _ );
      · exact mul_nonneg ( div_nonneg ( Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact bin_masses_nonneg f hf_nonneg n _ ; exact le_rfl ] ) ( Finset.sum_nonneg fun _ _ => bin_masses_nonneg f hf_nonneg n _ ) ) ( Nat.cast_nonneg _ )

theorem canonical_discretization_sum_eq_telescope (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_pos : ∑ j : Fin (2 * n), bin_masses f n j ≠ 0) :
    ∑ i : Fin (2 * n), canonical_discretization f n m i =
    ∑ i : Fin (2 * n), (canonical_cumulative_distribution f n m (i + 1) - canonical_cumulative_distribution f n m i) := by
      convert Finset.sum_congr rfl fun i _ => canonical_discretization_eq_diff f n m (canonical_cumulative_distribution_2n f n m hn hm h_mass_pos) i

theorem sum_fin_telescope_nat (f : ℕ → ℕ) (n : ℕ) (h_mono : Monotone f) :
    ∑ i : Fin n, (f (i + 1) - f i) = f n - f 0 := by
      have h_telescope : ∀ (n : ℕ), ∑ i ∈ Finset.range n, (f (i + 1) - f i) = f n - f 0 := by
        exact?;
      rw [ ← h_telescope, Finset.sum_range ]

theorem sum_fin_telescope_nat_v2 (f : ℕ → ℕ) (n : ℕ) (h_mono : Monotone f) :
    ∑ i : Fin n, (f (i + 1) - f i) = f n - f 0 := by
      -- Apply the telescoping series sum theorem with the monotonicity condition.
      apply sum_fin_telescope_nat f n h_mono

theorem canonical_discretization_sum_eq_m (f : ℝ → ℝ) (n m : ℕ) (hn : n > 0) (hm : m > 0)
    (h_mass_pos : ∑ j : Fin (2 * n), bin_masses f n j ≠ 0)
    (hf_nonneg : ∀ x, 0 ≤ f x) :
    ∑ i : Fin (2 * n), canonical_discretization f n m i = m := by
      rw [canonical_discretization_sum_eq_telescope f n m hn hm h_mass_pos]
      rw [sum_fin_telescope_nat_v2 (canonical_cumulative_distribution f n m) (2 * n) (canonical_cumulative_distribution_mono f hf_nonneg n m)]
      rw [canonical_cumulative_distribution_2n f n m hn hm h_mass_pos]
      rw [canonical_cumulative_distribution_zero]
      simp

noncomputable def f_restricted (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n)) : ℝ → ℝ :=
  let δ := 1 / (4 * n : ℝ)
  let a := -(1/4 : ℝ) + i * δ
  let b := -(1/4 : ℝ) + (i + 1) * δ
  Set.indicator (Set.Ico a b) f

theorem f_restricted_integral (n : ℕ) (f : ℝ → ℝ) (i : Fin (2 * n)) :
    MeasureTheory.integral MeasureTheory.volume (f_restricted f n i) = bin_masses f n i := by
  unfold f_restricted bin_masses
  rfl

theorem f_ge_f_restricted (n : ℕ) (f : ℝ → ℝ) (hf : ∀ x, 0 ≤ f x) (i : Fin (2 * n)) :
    ∀ x, f x ≥ f_restricted f n i x ∧ f_restricted f n i x ≥ 0 := by
      -- By definition of $f_restricted$, we know that $f_restricted f n i x = f x$ if $x \in [a_i, b_i)$ and $0$ otherwise.
      intros x
      simp [f_restricted];
      -- The indicator function is either 0 or 1, so it is always less than or equal to f(x) and non-negative.
      simp [Set.indicator] at *; aesop;

theorem convolution_comm_real (f g : ℝ → ℝ) :
    MeasureTheory.convolution f g (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume =
    MeasureTheory.convolution g f (ContinuousLinearMap.mul ℝ ℝ) MeasureTheory.volume := by
      ext x;
      -- By substitution using $ u = x - t $, we can show that the integrals are equal.
      have h_subst : ∀ {f g : ℝ → ℝ}, (∫ t, f t * g (x - t)) = (∫ t, g t * f (x - t)) := by
        intro f g; rw [ ← MeasureTheory.integral_sub_left_eq_self ] ; congr; ext; ring;
      exact h_subst

theorem f_has_compact_support (f : ℝ → ℝ) (hf_supp : Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4)) :
    HasCompactSupport f := by
      -- The closure of the support of $f$ is the closed interval $[-1/4, 1/4]$, which is compact.
      have h_closure : closure (Function.support f) ⊆ Set.Icc (-1 / 4 : ℝ) (1 / 4) := by
        -- Since the support of $f$ is a subset of $(-1/4, 1/4)$, its closure is a subset of the closure of $(-1/4, 1/4)$, which is $[-1/4, 1/4]$.
        have h_closure_subset : closure (Function.support f) ⊆ closure (Set.Ioo (-1 / 4 : ℝ) (1 / 4)) := by
          -- Apply the fact that the closure of a subset is contained within the closure of the larger set.
          apply closure_mono hf_supp;
        exact h_closure_subset.trans ( by rw [ closure_Ioo ( by norm_num ) ] );
      exact CompactIccSpace.isCompact_Icc.of_isClosed_subset ( isClosed_closure ) h_closure

theorem f_restricted_integrable (f : ℝ → ℝ) (n : ℕ) (i : Fin (2 * n))
    (h_int : MeasureTheory.Integrable f MeasureTheory.volume) :
    MeasureTheory.Integrable (f_restricted f n i) MeasureTheory.volume := by
  unfold f_restricted
  apply MeasureTheory.Integrable.indicator h_int measurableSet_Ico