/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d81b0331-c62b-4e49-9984-48699f6cc89f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of integer dynamic threshold and floating-point margins for the autoconvolution constant proof.

We define the integer convolution `conv` and window sum `window_sum`, and the dynamic threshold `dyn_it`.
We prove:
1. `dyn_it_conservative`: The computed threshold is conservative (at least as high as the exact value).
2. `conv_bounded`: Convolution entries are bounded by m^2.
3. `conv_total_eq_m_squared`: The total sum of convolution entries is m^2.
4. `m_sq_int32`: For m <= 200, m^2 fits in a 32-bit integer.
5. `pruning_soundness`: Pruning with the computed threshold implies pruning with the exact threshold.

These results verify Claims 2.4, 5.1, and 5.2 regarding the soundness of the integer-space threshold computation.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The computed dynamic threshold (B) is at least as large as the exact mathematical threshold (A), ensuring the pruning is conservative.
-/
theorem dyn_it_conservative (c_target : ℝ) (m n ℓ W_int : ℕ)
    (hm : 0 < m) (hn : 0 < n) (hℓ : 0 < ℓ) (hW : W_int ≤ m) (hct : 0 ≤ c_target)
    (hct_upper : c_target ≤ 2) (hm_upper : m ≤ 200) :
    let A := (c_target * (m : ℝ)^2 + 1 + 2 * (W_int : ℝ)) * ((ℓ : ℝ) / (4 * (n : ℝ)))
    let B := (c_target * (m : ℝ)^2 + 1 + 1e-9 * (m : ℝ)^2 + 2 * (W_int : ℝ)) *
             ((ℓ : ℝ) / (4 * (n : ℝ))) * (1 - 4 * 2.22e-16)
    ⌊A⌋ ≤ ⌊B⌋ := by
  refine' Int.floor_mono _;
  -- We'll use that $W \leq m$ to simplify the inequality.
  have h_W_le_m : (W_int : ℝ) ≤ m := by
    norm_cast;
  -- We'll use that $m \leq 200$ to simplify the inequality.
  have h_m_le_200 : (m : ℝ) ≤ 200 := by
    norm_cast;
  field_simp;
  norm_num; nlinarith [ show ( 1 : ℝ ) ≤ m ^ 2 by exact_mod_cast pow_pos hm 2 ] ;

/-
The convolution entries are bounded by m^2.
-/
theorem conv_bounded {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) (k : ℕ) :
    Finset.univ.sum (fun i => Finset.univ.sum (fun j => if i.1 + j.1 = k then c i * c j else 0)) ≤ m ^ 2 := by
  rw [ ← hc, sq, Finset.sum_mul ];
  exact Finset.sum_le_sum fun i _ => by rw [ Finset.mul_sum _ _ _ ] ; exact Finset.sum_le_sum fun j _ => by split_ifs <;> nlinarith;

/-
The total sum of the convolution entries equals m^2.
-/
theorem conv_total_eq_m_squared {d : ℕ} (c : Fin d → ℕ) (m : ℕ) (hc : ∑ i, c i = m) :
    ∑ k ∈ Finset.range (2 * d - 1),
      (∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then c i * c j else 0) = m ^ 2 := by
  rw [ sq, ← hc, Finset.sum_comm ];
  -- Let's simplify the expression inside the sum.
  have h_simp : ∀ y : Fin d, ∑ x ∈ Finset.range (2 * d - 1), ∑ j : Fin d, (if y + j = x then c y * c j else 0) = ∑ j : Fin d, c y * c j := by
    intro y; rw [ Finset.sum_comm ] ; simp +decide [ Finset.sum_ite ] ;
    rw [ Finset.filter_true_of_mem fun x hx => lt_tsub_iff_left.mpr <| by linarith [ Fin.is_lt y, Fin.is_lt x ] ];
  simp +decide only [h_simp, ← Finset.mul_sum _ _ _, ← Finset.sum_mul]

/-
For m <= 200, m^2 fits in a 32-bit signed integer.
-/
theorem m_sq_int32 (m : ℕ) (hm : m ≤ 200) : m ^ 2 ≤ 2 ^ 31 - 1 := by
  interval_cases m <;> trivial

/-
Definitions of integer convolution and window sum.
-/
def conv {d : ℕ} (c : Fin d → ℕ) (k : ℕ) : ℕ :=
  ∑ i : Fin d, ∑ j : Fin d, if i.1 + j.1 = k then c i * c j else 0

def window_sum {d : ℕ} (c : Fin d → ℕ) (s_lo ℓ : ℕ) : ℕ :=
  ∑ k ∈ Finset.Ico s_lo (s_lo + ℓ - 1), conv c k

/-
Definition of the dynamic threshold used for pruning.
-/
noncomputable def dyn_it (c_target : ℝ) (m n ℓ W_int : ℕ) : ℤ :=
  ⌊(c_target * (m : ℝ)^2 + 1 + 1e-9 * (m : ℝ)^2 + 2 * (W_int : ℝ)) *
   ((ℓ : ℝ) / (4 * (n : ℝ))) * (1 - 4 * 2.22e-16)⌋

/-
Pruning with the computed threshold implies pruning with the exact threshold, ensuring soundness.
-/
def pruning_condition (ws : ℕ) (threshold : ℤ) : Prop :=
  (ws : ℤ) > threshold

theorem pruning_soundness (c_target : ℝ) (m n ℓ W_int : ℕ) (ws : ℕ)
    (hm : 0 < m) (hn : 0 < n) (hℓ : 0 < ℓ) (hW : W_int ≤ m) (hct : 0 ≤ c_target)
    (hct_upper : c_target ≤ 2) (hm_upper : m ≤ 200) :
    let A := (c_target * (m : ℝ)^2 + 1 + 2 * (W_int : ℝ)) * ((ℓ : ℝ) / (4 * (n : ℝ)))
    let exact_threshold := ⌊A⌋
    let computed_threshold := dyn_it c_target m n ℓ W_int
    pruning_condition ws computed_threshold → pruning_condition ws exact_threshold := by
  -- By definition of `pruning_condition`, we know that if `pruning_condition ws computed_threshold` holds, then `ws > computed_threshold`.
  intro A exact_threshold computed_threshold h_pruning
  have h_computed_gt_exact : computed_threshold ≥ exact_threshold := by
    convert dyn_it_conservative c_target m n ℓ W_int hm hn hℓ hW hct hct_upper hm_upper using 1
  exact h_pruning.trans_le' h_computed_gt_exact