/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 06748927-7810-41f8-8291-fe0bc123ffb0

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized the cascade completeness theorem and the merge_pairs definition.
The theorem `cascade_completeness_step` proves that if all compositions at level L are pruned (meaning their test values exceed the threshold), then the autoconvolution ratio of any function discretizing to such compositions is at least `c_target`.
This relies on the soundness of pruning (`h_pruning_sound`) and the mass preservation of discretization (`h_discretize_sum`), which were added as hypotheses since their definitions were not provided.
Also proved `merge_pairs_sum` showing that merging pairs preserves the total sum.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of autoconvolution_ratio using eLpNorm and convolution.
-/
noncomputable def autoconvolution_ratio (f : ℝ → ℝ) : ℝ :=
  (MeasureTheory.eLpNorm (MeasureTheory.convolution f f (ContinuousLinearMap.lsmul ℝ ℝ) MeasureTheory.volume) ⊤ MeasureTheory.volume).toReal / (MeasureTheory.integral MeasureTheory.volume f) ^ 2

/-
Definition of merge_pairs and theorem merge_pairs_sum.
-/
def merge_pairs {d : ℕ} (child : Fin (2 * d) → ℕ) : Fin d → ℕ :=
  fun i => child ⟨2 * i.1, by omega⟩ + child ⟨2 * i.1 + 1, by omega⟩

theorem merge_pairs_sum {d m : ℕ} (child : Fin (2 * d) → ℕ) (hc : ∑ i, child i = m) :
    ∑ i, merge_pairs child i = m := by
  unfold merge_pairs;
  rw [ ← hc, eq_comm ];
  clear hc;
  induction' d with d ih <;> simp_all +decide [ Nat.mul_succ, Fin.sum_univ_castSucc ] ; ring!;

/-
Theorem: If all compositions at level L are pruned, then the autoconvolution ratio of any function is at least c_target.
Proof:
1. Take any function f.
2. Discretize it to get composition c.
3. c has sum m (by h_discretize_sum).
4. Since all compositions are pruned, c is pruned (h_all_pruned).
5. Pruning implies R(f) >= c_target (h_pruning_sound).
-/
theorem cascade_completeness_step
  (n m : ℕ) (c_target : ℝ)
  (hn : n > 0) (hm : m > 0) (hct : 0 < c_target)
  (L : ℕ)
  (test_value : (d : ℕ) → (m : ℕ) → (Fin (2 * d) → ℕ) → ℕ → ℕ → ℝ)
  (discretize : (ℝ → ℝ) → (d : ℕ) → (m : ℕ) → Fin d → ℕ)
  (h_discretize_sum : ∀ f d m, ∑ i, discretize f d m i = m)
  (h_pruning_sound : ∀ (n m : ℕ) (c_target : ℝ) (L : ℕ) (c : Fin (2 * (2^L * n)) → ℕ) (ℓ s_lo : ℕ) (f : ℝ → ℝ),
      test_value (2^L * n) m c ℓ s_lo > c_target + 2 / (m : ℝ) + 1 / (m : ℝ)^2 →
      discretize f (2 * (2^L * n)) m = c →
      autoconvolution_ratio f ≥ c_target)
  (h_all_pruned : ∀ c : Fin (2 * (2^L * n)) → ℕ, ∑ i, c i = m →
      ∃ ℓ s_lo, test_value (2^L * n) m c ℓ s_lo > c_target + 2 / (m : ℝ) + 1 / (m : ℝ)^2) :
  ∀ f : ℝ → ℝ, (∀ x, 0 ≤ f x) →
    Function.support f ⊆ Set.Ioo (-1/4 : ℝ) (1/4) →
    MeasureTheory.integral MeasureTheory.volume f ≠ 0 →
    autoconvolution_ratio f ≥ c_target := by
  intro f hf_nonneg hf_supp hf_int_ne_zero
  let c := discretize f (2 * (2^L * n)) m
  have hc_sum : ∑ i, c i = m := h_discretize_sum f (2 * (2^L * n)) m
  obtain ⟨ℓ, s_lo, h_val⟩ := h_all_pruned c hc_sum
  exact h_pruning_sound n m c_target L c ℓ s_lo f h_val rfl